Repository kobotoolbox/kpi, pull requests merged in 2018-07, with the labels that each got.

#1837 add colors for alertify messages
  jsapp/scss/components/_kobo.alertify-overrides.scss
  jsapp/scss/libs/_mdl.scss
Labels: coded

#1838 Fiz dropzone Firefox issue
  jsapp/js/components/formEditors.es6
  jsapp/js/components/searchcollectionlist.es6
  jsapp/scss/components/_kobo.bem.ui.scss
  jsapp/scss/components/_kobo.modal.scss
  package.json
Labels: coded

#1836 Show better error message for update profile
  jsapp/js/actions.es6
  jsapp/js/bem.es6
  jsapp/js/components/accountSettings.es6
  jsapp/js/components/textBox.es6
  jsapp/scss/components/_kobo.account-settings.scss
  jsapp/scss/components/_kobo.bem.ui.scss
  jsapp/scss/components/_kobo.text-box.scss
  jsapp/scss/main.scss
Labels: coded, ui

#1846 Use babel-polyfill to support IE11
  jsapp/js/main.es6
Labels: coded

#1847 Update base image on every Fabric build
  fabfile/docker.py
Labels: coded

#1848 Remove jquery.scrollTo library.
  jsapp/js/app.es6
  jsapp/xlform/src/view.rowSelector.coffee
  package.json
  test/index.js
Labels: coded

#1850 add info about icons to readme
  README.md
Labels: coded

#1855 Fix #1854: Submission modal fails to load when form definition is mis…
  jsapp/js/components/submission.es6
Labels: coded

#1856 fix icons alignment
  jsapp/k-icons-css-template.hbs
  jsapp/scss/components/_kobo.alertify-overrides.scss
  jsapp/scss/stylesheets/partials/form_builder/_card_settings.scss
Labels: coded

#1867 *._isSelectQuestion undefined fix
  jsapp/xlform/src/mv.skipLogicHelpers.coffee
Labels: coded

#1813 Feature: Form Templates
  jsapp/js/actions.es6
  jsapp/js/app.es6
  jsapp/js/bem.es6
  jsapp/js/components/assetrow.es6
  jsapp/js/components/drawer.es6
  jsapp/js/components/formEditors.es6
  jsapp/js/components/formEditors/templatesList.es6
  jsapp/js/components/formLanding.es6
  jsapp/js/components/formSubScreens.es6
  jsapp/js/components/formSummary.es6
  jsapp/js/components/header.es6
  jsapp/js/components/librarySidebar.es6
  jsapp/js/components/list.es6
  jsapp/js/components/map.es6
  jsapp/js/components/modal.es6
  jsapp/js/components/reports.es6
  jsapp/js/components/searchcollectionlist.es6
  jsapp/js/components/sharingForm.es6
  jsapp/js/components/submission.es6
  jsapp/js/components/table.es6
  jsapp/js/components/tableColumnFilter.es6
  jsapp/js/constants.es6
  jsapp/js/dataInterface.es6
  jsapp/js/editorMixins/assetNavigator.es6
  jsapp/js/editorMixins/editableForm.es6
  jsapp/js/lists/library.es6
  jsapp/js/lists/sidebarForms.es6
  jsapp/js/mixins.es6
  jsapp/js/stores.es6
  jsapp/js/ui.es6
  jsapp/scss/components/_kobo.alertify-overrides.scss
  jsapp/scss/components/_kobo.asset-row.scss
  jsapp/scss/components/_kobo.bem.ui.scss
  jsapp/scss/components/_kobo.collection-asset-list.scss
  jsapp/scss/components/_kobo.form-builder.scss
  jsapp/scss/components/_kobo.lib-list.scss
  jsapp/scss/components/_kobo.lib-nav.scss
  jsapp/scss/components/_kobo.modal.scss
  jsapp/scss/components/_kobo.report-view.scss
  jsapp/scss/components/_kobo.select-underlined.scss
  jsapp/scss/components/_kobo.sharing-modal.scss
  jsapp/scss/components/_kobo.table.scss
  jsapp/scss/components/_kobo.templates-list.scss
  jsapp/scss/libs/_mdl.scss
  jsapp/scss/libs/alertify.scss
  jsapp/scss/libs/react-select.scss
  jsapp/scss/libs/react-tagsinput.scss
  jsapp/scss/main.scss
  jsapp/scss/stylesheets/pages/form_builder.scss
  jsapp/scss/stylesheets/partials/form_builder/_form_settings.scss
  jsapp/svg-icons/kobo.svg
  jsapp/xlform/src/model.row.coffee
  jsapp/xlform/src/view.surveyApp.coffee
  jsapp/xlform/src/view.surveyApp.templates.coffee
  kpi/filters.py
  kpi/templates/browser_tests.html
  test/index.js
  test/tests_hot.html
  webpack/dev.server.js
  webpack/prod.config.js
Labels: ui

#1844 New map features
  dependencies/pip/dev_requirements.txt
  dependencies/pip/external_services.txt
  dependencies/pip/requirements.txt
  jsapp/js/actions.es6
  jsapp/js/components/formSummary.es6
  jsapp/js/components/map.es6
  jsapp/js/components/mapSettings.es6
  jsapp/js/dataInterface.es6
  jsapp/js/ui.es6
  jsapp/js/utils.es6
  jsapp/scss/components/_kobo.form-summary.scss
  jsapp/scss/components/_kobo.map.marker-colors.scss
  jsapp/scss/components/_kobo.map.scss
  jsapp/scss/main.scss
  kpi/fields.py
  kpi/migrations/0022_assetfile.py
  kpi/models/__init__.py
  kpi/models/asset_file.py
  kpi/serializers.py
  kpi/tests/test_api_assets.py
  kpi/urls.py
  kpi/views.py
  package.json
Labels: coded

#1888 Improve Needs save logic
  jsapp/xlform/src/_utils.coffee
  jsapp/xlform/src/model.base.coffee
  jsapp/xlform/src/mv.skipLogicHelpers.coffee
  jsapp/xlform/src/mv.validationLogicHelpers.coffee
  jsapp/xlform/src/view.choices.coffee
  jsapp/xlform/src/view.row.coffee
  jsapp/xlform/src/view.rowDetail.SkipLogic.coffee
  jsapp/xlform/src/view.surveyApp.coffee
Labels: coffeescript
