Repository kobotoolbox/kpi, pull requests merged in 2020-11, with the labels that each got.

#2852 Adding `__filtered_queryset` variable to prevent double calls of `filter_queryset()`
  kpi/views/v2/asset.py
Labels: backend, enhancement

#2859 Make `access_type` an array
  kpi/serializers/v2/asset.py
  kpi/tests/api/v2/test_api_collections.py
Labels: API, backend

#2858 Give priority to collections on sorting with param `collections_first`
  kpi/filters.py
  kpi/models/asset.py
  kpi/tests/api/v2/test_api_assets.py
  kpi/views/v2/asset.py
Labels: API, backend, enhancement

#2857 Removing nested children from asset detail endpoint
  kpi/serializers/v2/asset.py
  kpi/tests/kpi_test_case.py
Labels: enhancement

#2871 Delete users in both database at once
  hub/actions.py
  hub/admin.py
  kobo/settings/base.py
  kpi/deployment_backends/kc_access/utils.py
  kpi/signals.py
Labels: backend, bug-fix, enhancement

#2862 Removing exported file on delete
  kpi/models/import_export_task.py
  kpi/tests/api/v1/test_api_assets.py
Labels: API, backend, enhancement

#2861 Reducing service_health timeout
  kobo/apps/service_health/views.py
Labels: backend, enhancement

#2883 Control `EXPOSE_GIT_REV` through django-constance
  kobo/settings/base.py
  kpi/serializers/current_user.py
Labels: low priority

#2886 Allow for publicly shared data permissions to be merged with user
  kpi/models/object_permission.py
  kpi/tests/api/v2/test_api_submissions.py
  kpi/tests/test_mock_data_exports.py
Labels: backend, bug-fix
