Repository kobotoolbox/kpi, pull requests merged in 2020-10, with the labels that each got.

#2816 [Public collections] Simplify asset permissions
  kobo/apps/reports/views.py
  kpi/constants.py
  kpi/fields/__init__.py
  kpi/fields/generic_hyperlinked_related.py
  kpi/filters.py
  kpi/management/commands/sync_kobocat_xforms.py
  kpi/migrations/0025_copy_collections_to_assets.py
  kpi/migrations/0027_remove_objectpermission_generic_relation.py
  kpi/models/asset.py
  kpi/models/object_permission.py
  kpi/serializers/v1/object_permission.py
  kpi/serializers/v2/user.py
  kpi/signals.py
  kpi/tests/api/v1/test_api_permissions.py
  kpi/tests/test_collections.py
  kpi/views/v2/asset.py
Labels: enhancement

#2839 [Public collections] Verify parent write access before moving a child from/to a collection.
  kpi/models/object_permission.py
  kpi/serializers/v2/asset.py
  kpi/tests/api/v2/test_api_collections.py
Labels: API

#2572 Improved XML rendering in assets list endpoint
  kpi/deployment_backends/kobocat_backend.py
  kpi/renderers.py
  kpi/views/v2/asset.py
  kpi/views/v2/data.py
Labels: enhancement

#2830 Updating default search behaviour when no explicit term is given by user
  kpi/constants.py
  kpi/exceptions.py
  kpi/filters.py
  kpi/tests/api/v2/test_api_assets.py
  kpi/tests/test_utils.py
  kpi/utils/query_parser/query_parser.py
Labels: API, enhancement

#2844 updating semantics from member_since to date_joined
  kpi/serializers/v1/user.py
  kpi/serializers/v2/user.py
Labels: backend
