Repository kobotoolbox/kpi, pull requests merged in 2020-12, with the labels that each got.

#2906 Require unnamed translation to be named before…
  jsapp/js/components/modalForms/translationSettings.es6
Labels: high priority

#2916 Fixed: Forms cannot be shared publicly
  kpi/deployment_backends/kobocat_backend.py
Labels: bug-fix, high priority

#2924 Improvements for release 2.020.50
  kpi/models/asset.py
  kpi/serializers/v2/asset_permission_assignment.py
Labels: backend, bug-fix, enhancement

#2904 Cherry pick bug fix about publicly shared permissions for granted users
  kpi/models/object_permission.py
  kpi/tests/api/v2/test_api_submissions.py
  kpi/tests/test_mock_data_exports.py
Labels: bug-fix

#2931 Fix permission lookup that was causing a 500 error
  kpi/models/asset.py
Labels: CRITICAL, bug

#2897 [UNHCR] Duplicate submissions feature
  kpi/deployment_backends/kobocat_backend.py
  kpi/deployment_backends/mock_backend.py
  kpi/exceptions.py
  kpi/permissions.py
  kpi/tests/api/v2/test_api_submissions.py
  kpi/views/v2/data.py
Labels: API, backend, enhancement

#2938 Fix "Data column name" regression
  jsapp/js/editorMixins/editableForm.es6
  jsapp/js/utils.es6
  jsapp/xlform/src/view.rowDetail.coffee
Labels: CRITICAL
