Repository kobotoolbox/kpi, pull requests merged in 2021-05, with the labels that each got.

#3118 Link export with export-settings
  dependencies/pip/dev_requirements.txt
  dependencies/pip/external_services.txt
  dependencies/pip/requirements.in
  dependencies/pip/requirements.txt
  dependencies/pip/travis_ci.txt
  kpi/serializers/v2/export_task.py
  kpi/tests/api/v2/test_api_exports.py
Labels: API, backend, enhancement

#3216 Fix `AnonymousUser` listed permissions on public asset
  kpi/tests/api/v2/test_api_asset_permission_assignment.py
  kpi/tests/api/v2/test_api_permissions.py
  kpi/utils/object_permission_helper.py
Labels: API, backend, bug-fix

#3219 Assigning "Change submissions" implies "Add submissions"
  jsapp/js/actions.es6
  jsapp/js/components/assetrow.es6
  jsapp/js/components/modalForms/submission.es6
  jsapp/js/components/permissions/permissionsMocks.es6
  jsapp/js/components/permissions/userAssetPermsEditor.es6
  kpi/models/asset.py
  kpi/permissions.py
  kpi/tests/api/v2/test_api_submissions.py
  kpi/tests/test_permissions.py
Labels: backend, bug-fix, high priority

#3223 Fixed GenericForeignKey errors with shadow models
  hub/admin.py
  kobo/apps/shadow_model/__init__.py
  kobo/apps/usage_statistics/__init__.py
  kobo/apps/usage_statistics/admin.py
  kobo/apps/usage_statistics/templates/user_statistics.html
  kobo/apps/user_statistics/__init__.py
  kobo/settings/base.py
  kpi/constants.py
  kpi/db_routers.py
  kpi/deployment_backends/kc_access/shadow_models.py
Labels: bug-fix

#3174 Allow users to migrate their XForms from kobocat
  kpi/views/v2/user.py
Labels: API, backend, enhancement, high priority
