Repository kobotoolbox/kpi, pull requests merged in 2021-02, with the labels that each got.

#2966 2778 in app messages
  kobo/apps/help/admin.py
Labels: backend

#2955 Fix to allow for child assets to be visible in public collections when unsubscribed or non-owner
  kpi/filters.py
  kpi/tests/api/v2/test_api_collections.py
Labels: API, backend, bug-fix

#2989 Remove deprecated KC content types
  kobo/settings/base.py
Labels: high priority

#3015 Fix reports view returns a 500
  kobo/apps/reports/views.py
  kpi/models/object_permission.py
Labels: API, backend, bug-fix

#3027 Make assets without versions cloneable
  kpi/models/asset.py
  kpi/tests/test_cloning.py
Labels: backend, bug-fix
