Repository kobotoolbox/kpi, pull requests merged in 2021-12, with the labels that each got.

#3592 Add support to multi architecture docker image
  Dockerfile
  dependencies/pip/dev_requirements.txt
Labels: enhancement

#3515 Add management command to sync permissions between KPI and KoBoCAT
  kpi/deployment_backends/kc_access/utils.py
  kpi/management/commands/sync_kobocat_perms.py
  kpi/management/commands/sync_kobocat_xforms.py
Labels: backend

#3590 Add support for OAuth2 authenticated request to API.
  kobo/settings/base.py
Labels: API, bug-fix, backend

#3598 removed translation wrappers from country and language lists
  kobo/static_lists.py
Labels: translations

#3588 Fix 500 errors returned when trying to delete a user from admin platform
  kpi/deployment_backends/kc_access/shadow_models.py
  kpi/deployment_backends/kc_access/utils.py
Labels: bug-fix, backend

#3575 Fix filtering repeat groups in export
  kpi/models/import_export_task.py
  kpi/tests/test_mock_data_exports.py
Labels: bug-fix, backend

#3605 Fix submission bulk edit XML handling
  kpi/deployment_backends/kobocat_backend.py
  kpi/tests/test_utils.py
  kpi/utils/xml.py
Labels: bug-fix, backend
