Repository kobotoolbox/kpi, pull requests merged in 2021-08, with the labels that each got.

#3400 `Manage project` broken assignment fix
  jsapp/js/components/permissions/permParser.es6
Labels: bug-fix, frontend

#3357 Include `form_title` in xlsform export
  kpi/mixins/xls_exportable.py
  kpi/tests/test_assets.py
Labels: bug-fix, backend

#3334 Filter `_index` in advanced exports
  jsapp/js/constants.ts
  kpi/models/import_export_task.py
  kpi/tests/test_mock_data_exports.py
Labels: enhancement, backend

#3331 Enable XLS types in export
  dependencies/pip/dev_requirements.txt
  dependencies/pip/external_services.txt
  dependencies/pip/requirements.in
  dependencies/pip/requirements.txt
  dependencies/pip/travis_ci.txt
  jsapp/js/components/projectDownloads/exportsConstants.es6
  jsapp/js/components/projectDownloads/projectExportsCreator.es6
  kpi/models/import_export_task.py
  kpi/serializers/v2/export_task.py
  kpi/tests/test_mock_data_exports.py
Labels: enhancement, backend, frontend

#3444 Update XLS types export
  dependencies/pip/dev_requirements.txt
  dependencies/pip/external_services.txt
  dependencies/pip/requirements.in
  dependencies/pip/requirements.txt
  dependencies/pip/travis_ci.txt
  jsapp/js/components/projectDownloads/exportsConstants.es6
  jsapp/js/components/projectDownloads/projectExportsCreator.es6
  kpi/models/import_export_task.py
  kpi/serializers/v2/export_task.py
Labels: enhancement
