Repository kobotoolbox/kpi, pull requests merged in 2022-12, with the labels that each got.

#4170 Set the default start date of admin reports to the first day of month
  kobo/apps/superuser_stats/views.py
Labels: bug-fix, backend

#4181 [NLP] Hotfix for "access denied error"
  kobo/apps/subsequences/utils/__init__.py
Labels: CRITICAL

#4172 Update KoboToolbox logo in top bar menu and login page
  .github/workflows/pytest.yml
  Dockerfile
  jsapp/img/kobologo.svg
  static/kobologo.svg
Labels: enhancement, UI & UX

#4174 Fix failing exports when the project name contains invalid characters
  kpi/models/asset.py
  kpi/models/asset_file.py
  kpi/models/import_export_task.py
  kpi/tests/api/v2/test_api_assets.py
  kpi/tests/api/v2/test_api_exports.py
  kpi/tests/api/v2/test_api_imports.py
Labels: bug-fix, backend

#4178 Add support for list properties in JSON fields to query parser
  hub/models.py
  hub/tests/test_user_details.py
  kobo/apps/languages/tests/api/v2/test_api_services.py
  kobo/apps/languages/views/language.py
  kobo/apps/languages/views/transcription_service.py
  kobo/apps/languages/views/translation_service.py
  kobo/settings/dev.py
  kpi/exceptions.py
  kpi/filters.py
  kpi/management/commands/standardize_searchable_fields.py
  kpi/migrations/0044_standardize_searchable_jsonb_fields.py
  kpi/mixins/__init__.py
  kpi/mixins/standardize_searchable_field.py
  kpi/models/asset.py
  kpi/tests/api/v1/test_api_users.py
  kpi/tests/api/v2/test_api_assets.py
  kpi/tests/test_assets.py
  kpi/tests/test_cloning.py
  kpi/tests/test_utils.py
  kpi/utils/query_parser/canopy_autogenerated_parser/__init__.py
  kpi/utils/query_parser/query_parser.py
  kpi/views/v2/asset.py
Labels: enhancement

#4195 Optimize number of DB queries in asset list endpoint of ProjectView app
  dependencies/pip/dev_requirements.txt
  dependencies/pip/requirements.in
  dependencies/pip/requirements.txt
  kobo/apps/project_views/views.py
  kobo/apps/subsequences/tests/test_submission_extras_api_post.py
  kpi/mixins/object_permission.py
  kpi/paginators.py
  kpi/serializers/v2/asset.py
  kpi/views/v2/asset.py
Labels: backend

#4196 Allow user to see asset detail if view_asset perm assigned to project view
  kpi/tests/api/v2/test_api_assets.py
  kpi/views/v2/asset.py
Labels: backend
