Repository kobotoolbox/kpi, pull requests merged in 2022-10, with the labels that each got.

#4042 Shorten toast notification duration to 5 seconds
  jsapp/js/app.es6
Labels: UI & UX

#4040 Duplicate attachments with duplicated submissions
  kpi/deployment_backends/kobocat_backend.py
  kpi/deployment_backends/mock_backend.py
  kpi/tests/api/v2/test_api_attachments.py
  kpi/tests/api/v2/test_api_submissions.py
Labels: enhancement, API, backend

#3770 Superuser Reports
  dependencies/pip/dev_requirements.txt
  dependencies/pip/requirements.in
  dependencies/pip/requirements.txt
  kobo/apps/superuser_stats/admin.py
  kobo/apps/superuser_stats/models.py
  kobo/apps/superuser_stats/tasks.py
  kobo/apps/superuser_stats/templates/submissions_by_country.html
  kobo/apps/superuser_stats/templates/superuser_stats_change_list.html
  kobo/apps/superuser_stats/templates/user_statistics.html
  kobo/apps/superuser_stats/urls.py
  kobo/apps/superuser_stats/views.py
  kpi/urls/__init__.py
Labels: backend
