Repository kobotoolbox/kpi, pull requests merged in 2022-01, with the labels that each got.

#3602 Fix export filtering with attachments
  kpi/models/import_export_task.py
  kpi/tests/test_mock_data_exports.py
Labels: API, bug-fix, backend

#3633 Remove archive button when project not deployed
  jsapp/js/components/modalForms/projectSettings.es6
Labels: bug-fix, frontend

#3586 Synchronous exports
  kpi/mixins/export_object.py
  kpi/models/import_export_task.py
  kpi/renderers.py
  kpi/serializers/v2/asset_export_settings.py
  kpi/tests/api/v2/test_api_asset_export_settings.py
  kpi/tests/api/v2/test_api_exports.py
  kpi/utils/models.py
  kpi/views/v1/export_task.py
  kpi/views/v2/data.py
Labels: enhancement, API, backend

#3631 Stopped KeyError from throwing exceptions
  kpi/deployment_backends/kobocat_backend.py
Labels: bug-fix

#3634 Fixed KobocatUser.sync bug
  kpi/deployment_backends/kc_access/shadow_models.py
Labels: bug-fix
