Repository kobotoolbox/kpi, pull requests merged in 2022-08, with the labels that each got.

#3965 500 error fix when fetching API environment endpoint
  kpi/tests/api/test_api_environment.py
  kpi/views/environment.py
Labels: API, bug-fix, backend

#3969 Optimize code to avoid loading not required fields
  kobo/apps/reports/report_data.py
  kpi/exceptions.py
  kpi/mixins/object_permission.py
  kpi/models/asset.py
  kpi/models/paired_data.py
  kpi/utils/viewset_mixins.py
  kpi/views/v2/asset_snapshot.py
Labels: API, backend

#3970 Generate the external XML data of connected parent projects faster
  kobo/apps/reports/constants.py
  kpi/models/paired_data.py
  kpi/serializers/v2/asset.py
  kpi/serializers/v2/paired_data.py
  kpi/tests/test_paired_data.py
  kpi/utils/xml.py
  kpi/views/v2/paired_data.py
Labels: API, blocked, bug-fix, backend

#3786 Upgrade to Django 3.2
  Dockerfile
  dependencies/pip/dev_requirements.txt
  dependencies/pip/external_services.in
  dependencies/pip/external_services.txt
  dependencies/pip/requirements.in
  dependencies/pip/requirements.txt
  docker/init.bash
  hub/migrations/0005_perusersetting.py
  hub/migrations/0007_alter_jsonfield_to_jsonbfield.py
  hub/models.py
  kobo/apps/help/migrations/0001_initial.py
  kobo/apps/help/models.py
  kobo/apps/hook/migrations/0001_tables_creation.py
  kobo/apps/hook/models/hook.py
  kobo/settings/base.py
  kpi/deployment_backends/kc_access/shadow_models.py
  kpi/deployment_backends/kc_access/storage.py
  kpi/deployment_backends/kobocat_backend.py
  kpi/fields/lazy_default_jsonb.py
  kpi/migrations/0004_default_permissions_1910.py
  kpi/migrations/0015_assetversion.py
  kpi/migrations/0016_asset_settings.py
  kpi/migrations/0017_assetversion_uid_aliases_20170608.py
  kpi/migrations/0019_add_report_custom_field.py
  kpi/migrations/0022_assetfile.py
  kpi/migrations/0023_partial_permissions.py
  kpi/migrations/0024_alter_jsonfield_to_jsonbfield.py
  kpi/migrations/0032_asset_export_settings_model.py
  kpi/migrations/0040_synchronous_export.py
  kpi/models/asset.py
  kpi/models/asset_export_settings.py
  kpi/models/asset_file.py
  kpi/models/asset_snapshot.py
  kpi/models/asset_user_partial_permission.py
  kpi/models/asset_version.py
  kpi/models/import_export_task.py
  kpi/tests/api/v1/test_api_assets.py
  kpi/utils/jsonbfield_helper.py
Labels: backend

#3978 Avoid crash when kobocat database does not exist
  kpi/utils/two_database_configuration_checker.py
Labels: high priority
