Repository kobotoolbox/kpi, pull requests merged in 2022-09, with the labels that each got.

#3767 Extended Django Admin User View
  kobo/apps/superuser_stats/admin.py
  kpi/deployment_backends/kc_access/shadow_models.py
Labels: blocked

#3997 404 error fix when using the "Login as" button in Admin interface
  kobo/urls.py
Labels: bug-fix, backend

#3983 Use a service account to authenticate KPI requests to KoBoCAT
  .github/workflows/pytest.yml
  dependencies/pip/dev_requirements.txt
  dependencies/pip/requirements.in
  dependencies/pip/requirements.txt
  jsapp/js/components/formViewTabs.es6
  kobo/settings/base.py
  kpi/deployment_backends/kc_access/shadow_models.py
  kpi/deployment_backends/kobocat_backend.py
Labels: backend

#4025 Fix "different root names" Enketo error when editing a submission
  kpi/models/asset.py
  kpi/renderers.py
  kpi/serializers/v2/asset_snapshot.py
  kpi/tests/api/v2/test_api_submissions.py
  kpi/tests/test_asset_snapshots.py
  kpi/tests/test_assets.py
  kpi/tests/utils/mock.py
  kpi/tests/utils/xml.py
  kpi/utils/xml.py
  kpi/views/v2/data.py
Labels: bug-fix, backend

#3735 Wrap KoBoCAT DB writes into transactions where needed
  kpi/deployment_backends/kc_access/shadow_models.py
  kpi/deployment_backends/kc_access/utils.py
  kpi/deployment_backends/kobocat_backend.py
  kpi/management/commands/grant_default_permissions.py
  kpi/management/commands/sync_kobocat_perms.py
  kpi/mixins/object_permission.py
  kpi/models/asset.py
  kpi/models/import_export_task.py
  kpi/views/__init__.py
  kpi/views/token.py
  kpi/views/v1/object_permission.py
Labels: enhancement, backend

#4033 Use latest deployed version of the form for submission edits
  kpi/tests/api/v2/test_api_submissions.py
  kpi/views/v2/data.py
Labels: high priority, bug-fix, backend

#4027 Log submissions delete actions
  kobo/apps/audit_log/__init__.py
  kobo/apps/audit_log/admin.py
  kobo/apps/audit_log/migrations/0001_initial.py
  kobo/apps/audit_log/migrations/__init__.py
  kobo/apps/audit_log/models.py
  kobo/apps/audit_log/permissions.py
  kobo/apps/audit_log/serializers.py
  kobo/apps/audit_log/signals.py
  kobo/apps/audit_log/tests/__init__.py
  kobo/apps/audit_log/tests/test_api_audit_log.py
  kobo/apps/audit_log/urls.py
  kobo/apps/audit_log/views.py
  kobo/settings/base.py
  kpi/deployment_backends/base_backend.py
  kpi/deployment_backends/kc_access/shadow_models.py
  kpi/deployment_backends/kobocat_backend.py
  kpi/deployment_backends/mock_backend.py
  kpi/management/commands/sync_kobocat_xforms.py
  kpi/tests/api/v2/test_api_submissions.py
  kpi/urls/__init__.py
  kpi/views/v2/data.py
Labels: enhancement, blocked, backend
