Repository kobotoolbox/kpi, pull requests merged in 2022-05, with the labels that each got.

#3648 Fix parsing of submission XML for bulk editing
  kpi/deployment_backends/kobocat_backend.py
  kpi/deployment_backends/mock_backend.py
  kpi/tests/api/v2/test_api_submissions.py
Labels: bug-fix

#3805 Pin pip version
  Dockerfile
Labels: high priority

#3773 change password message
  kpi/templates/registration/password_reset_done.html
Labels: UI & UX

#3819 Add `nlp_features_enabled` boolean to restrict ASR/MT usage for specified user list
  kobo/apps/subsequences/api_view.py
  kobo/settings/base.py
  kpi/views/environment.py
Labels: API, backend
