Repository kobotoolbox/kpi, pull requests merged in 2022-03, with the labels that each got.

#3707 Allow Enketo editing to use existing KPI authentication
  kpi/authentication.py
  kpi/constants.py
  kpi/tests/api/v2/test_api_submissions.py
  kpi/views/v2/asset_snapshot.py
  kpi/views/v2/data.py
Labels: enhancement, high priority, backend

#3700 Fix synchronous export failure on insufficient permissions
  kpi/mixins/export_object.py
  kpi/models/import_export_task.py
  kpi/renderers.py
  kpi/tests/api/v2/test_api_exports.py
  kpi/utils/drf_exceptions.py
Labels: bug-fix, backend

#3709 Add django-environ and refactor environment variable setting
  dependencies/pip/dev_requirements.txt
  dependencies/pip/external_services.txt
  dependencies/pip/requirements.in
  dependencies/pip/requirements.txt
  kobo/settings/base.py
  kobo/settings/testing.py
  kpi/utils/redis_helper.py
Labels: backend

#3717 Pass REDIS connection as an URL to `django-redis-session`
  kobo/settings/base.py
Labels: high priority, bug-fix, backend

#3728 Fixed 500 error from get_or_create()
  kpi/deployment_backends/kc_access/shadow_models.py
Labels: bug-fix

#3734 Use latest deployed version of a form when editing a submission
  kpi/views/v2/data.py
Labels: backend

#3730 Fix autonaming for KoboRank and KoboScore
  kpi/tests/test_asset_content.py
  kpi/utils/autoname.py
Labels: bug-fix, backend
