Repository kobotoolbox/kpi, pull requests merged in 2022-06, with the labels that each got.

#3849 Add export API documentation for `lang` field
  kpi/views/v2/export_task.py
Labels: documentation

#3852 Select x from file
  jsapp/js/assetUtils.ts
  jsapp/js/constants.ts
  jsapp/svg-icons/qt-select-many-from-file-lock.svg
  jsapp/svg-icons/qt-select-many-from-file.svg
  jsapp/svg-icons/qt-select-one-from-file-lock.svg
  jsapp/svg-icons/qt-select-one-from-file.svg
Labels: frontend

#3618 [NLP] Static ASR and MT Language Lists
  kobo/static_lists.py
  kpi/tests/api/test_api_environment.py
  kpi/views/environment.py
Labels: API, backend

#3855 Fix `sync_kobocat_xforms` Excel format issue
  kpi/management/commands/sync_kobocat_xforms.py
Labels: bug-fix, backend

#3869 Permission assignments bug fix
  kpi/serializers/v2/asset_permission_assignment.py
  kpi/tests/api/v2/test_api_asset_permission_assignment.py
  kpi/tests/test_sorting.py
Labels: CRITICAL, API, bug-fix, backend

#3838 Support for mongodb replica set
  kobo/settings/base.py
Labels: backend

#3877 Fix submission edit authentication loop
  kpi/models/asset.py
  kpi/tests/api/v2/test_api_submissions.py
Labels: high priority, bug-fix, backend

#3874 Make GitHub Actions pytest routine stop failing on a particular case
  kpi/tests/api/v2/test_api_submissions.py
Labels: bug-fix, backend

#3885 Avoid using cache for dynamic settings while running unit tests
  kobo/apps/hook/tests/test_api_hook.py
  kobo/apps/hook/tests/test_ssrf.py
  kobo/settings/testing.py
Labels: bug-fix, backend

#3674 [ MFA ] Make the help message editable
  hub/tests/test_globalsettings.py
  hub/utils/i18n.py
  jsapp/js/actions/mfaActions.ts
  jsapp/js/components/account/accountSettings.scss
  jsapp/js/components/account/accountSettingsRoute.es6
  jsapp/js/components/account/accountSidebar.scss
  jsapp/js/components/account/accountSidebar.tsx
  jsapp/js/components/account/mfaModals.scss
  jsapp/js/components/account/mfaModals.tsx
  jsapp/js/components/account/securityRoute.scss
  jsapp/js/components/account/securityRoute.tsx
  jsapp/js/components/bigModal/bigModal.es6
  jsapp/js/components/common/button.tsx
  jsapp/js/components/common/modal.es6
  jsapp/js/components/formLanding.es6
  jsapp/js/components/modalForms/formMedia.es6
  jsapp/js/components/modalForms/formMedia.scss
  jsapp/js/components/modalForms/translationSettings.es6
  jsapp/js/components/permissions/permConfig.ts
  jsapp/js/components/permissions/sharingForm.es6
  jsapp/js/components/projectDownloads/legacyExports.es6
  jsapp/js/components/reports/reports.es6
  jsapp/js/dataInterface.ts
  jsapp/js/editorMixins/cascadeMixin.es6
  jsapp/js/envStore.ts
  jsapp/js/utils.ts
  jsapp/scss/components/_kobo.form-view.scss
  jsapp/scss/components/_kobo.project-downloads.scss
  jsapp/scss/main.scss
  jsapp/scss/stylesheets/partials/_mfa_token.scss
  kobo/apps/mfa/admin.py
  kobo/apps/mfa/models.py
  kobo/apps/mfa/templates/mfa_token.html
  kobo/settings/base.py
  kpi/context_processors.py
  kpi/fields/jsonschema_form_field.py
  kpi/templates/base.html
  kpi/templates/index.html
  kpi/tests/api/test_api_environment.py
  kpi/views/environment.py
Labels: backend, frontend
