Repository kobotoolbox/kpi, pull requests merged in 2022-11, with the labels that each got.

#3955 New API endpoint to expose all languages
  kobo/apps/languages/__init__.py
  kobo/apps/languages/admin.py
  kobo/apps/languages/exceptions.py
  kobo/apps/languages/fixtures/test_data.json
  kobo/apps/languages/forms.py
  kobo/apps/languages/migrations/0001_initial.py
  kobo/apps/languages/migrations/__init__.py
  kobo/apps/languages/models/__init__.py
  kobo/apps/languages/models/base.py
  kobo/apps/languages/models/language.py
  kobo/apps/languages/models/transcription.py
  kobo/apps/languages/models/translation.py
  kobo/apps/languages/serializers/__init__.py
  kobo/apps/languages/serializers/base.py
  kobo/apps/languages/serializers/language.py
  kobo/apps/languages/serializers/transcription.py
  kobo/apps/languages/serializers/translation.py
  kobo/apps/languages/signals.py
  kobo/apps/languages/templates/admin/languages_change_list.html
  kobo/apps/languages/templates/admin/languages_import.html
  kobo/apps/languages/tests/__init__.py
  kobo/apps/languages/tests/api/__init__.py
  kobo/apps/languages/tests/api/v2/__init__.py
  kobo/apps/languages/tests/api/v2/base.py
  kobo/apps/languages/tests/api/v2/test_api_languages.py
  kobo/apps/languages/tests/api/v2/test_api_services.py
  kobo/apps/languages/tests/base.py
  kobo/apps/languages/tests/test_services.py
  kobo/apps/languages/urls.py
  kobo/apps/languages/views/__init__.py
  kobo/apps/languages/views/base.py
  kobo/apps/languages/views/language.py
  kobo/apps/languages/views/transcription_service.py
  kobo/apps/languages/views/translation_service.py
  kobo/settings/base.py
  kobo/static_lists.py
  kpi/filters.py
  kpi/tests/api/test_api_environment.py
  kpi/urls/__init__.py
  kpi/utils/query_parser/query_parser.py
  kpi/views/environment.py
Labels: enhancement, API, backend

#4133 Improve audit log API documentation
  kobo/apps/audit_log/views.py
Labels: enhancement, API, backend

#4143 Fix error "Failed to list assets" when some projects are invalid but still appear in the UI
  kpi/deployment_backends/kobocat_backend.py
  kpi/exceptions.py
Labels: bug-fix, backend

#4144 Fix 500 error when fetching data from service usage endpoint
  kpi/deployment_backends/kobocat_backend.py
Labels: API, bug-fix, backend

#4150 Fix timeout when superusers try to open MFA user's details Admin UI
  kobo/apps/mfa/models.py
Labels: bug-fix, backend

#4149 Fix service usage endpoint all time calculation
  kpi/deployment_backends/base_backend.py
  kpi/deployment_backends/kobocat_backend.py
  kpi/deployment_backends/mock_backend.py
  kpi/serializers/v2/service_usage.py
  kpi/views/v2/service_usage.py
Labels: API, bug-fix, backend

#4156 Fix metadata handling in user details export
  kobo/apps/superuser_stats/tasks.py
Labels: bug-fix, backend

#4159 Use months range for users statistics report
  kobo/apps/superuser_stats/views.py
Labels: enhancement, backend

#4160 Fix 404 when date range parameters are omitted
  kobo/apps/superuser_stats/tasks.py
  kobo/apps/superuser_stats/views.py
Labels: bug-fix, backend
