Repository kobotoolbox/kpi, pull requests merged in 2022-04, with the labels that each got.

#3727 Consider user auth requirement as `False` when user has no extra settings
  kpi/permissions.py
  kpi/tests/api/v2/test_api_paired_data.py
Labels: bug-fix, backend

#3744 Always return a HTTP 401 on failure when editing a submission
  kpi/permissions.py
  kpi/tests/api/v1/test_api_submissions.py
  kpi/tests/api/v2/test_api_submissions.py
  kpi/views/v2/asset_snapshot.py
  kpi/views/v2/data.py
Labels: API, bug-fix, backend

#3771 Bulk permission assignment optimization
  dependencies/pip/dev_requirements.txt
  dependencies/pip/external_services.txt
  dependencies/pip/requirements.txt
  kpi/mixins/object_permission.py
  kpi/models/asset.py
  kpi/models/asset_user_partial_permission.py
  kpi/serializers/v2/asset_permission_assignment.py
  kpi/tests/api/v2/test_api_asset_permission_assignment.py
  kpi/views/v2/asset_permission_assignment.py
Labels: high priority
