Repository kobotoolbox/kpi, pull requests merged in 2023-03, with the labels that each got.

#4309 Add Organization Owner's email to Organization model
  kobo/apps/organizations/models.py
  kobo/settings/base.py
Labels: bug-fix, Back end

#4311 Harden CSP and remove all inline JavaScript
  hub/models.py
  jsapp/js/components/submissions/submissionUtils.mocks.es6
  jsapp/js/dataInterface.ts
  jsapp/xlform/src/view.utils.coffee
  kobo/apps/accounts/mfa/templates/mfa_token.html
  kobo/apps/accounts/templates/account/base.html
  kobo/apps/accounts/templates/account/login.html
  kobo/apps/accounts/templates/account/signup.html
  kobo/settings/base.py
  kpi/serializers/v1/asset.py
  kpi/serializers/v2/asset.py
  kpi/templates/base.html
  kpi/templates/design_system.html
  kpi/templates/global_t.html
  kpi/templates/index.html
  kpi/templates/koboform.html
  kpi/templates/snippets/modern_browsers_redirect.html
  kpi/urls/__init__.py
  kpi/views/v2/asset.py
  kpi/views/v2/asset_file.py
  static/js/README
  static/js/global_t.js
  static/js/google_analytics.js
  static/js/mfa_token.js
  static/js/redirect_obsolete_browsers.js
  static/js/sentry.js
  static/js/sso_buttons.js
Labels: high priority

#4328 Reorganize the Asset class methods alphabetically
  kpi/models/asset.py
Labels: Back end

#4327 Use new field `date_deployed` to retrieve deployed assets faster
  kpi/models/asset.py
Labels: Back end

#4332 Fix `Log in as user` button doing nothing with new (stricter) CSP
  hub/admin.py
  hub/static/admin/loginas/script.js
  hub/templates/admin/loginas/change_form.html
  kobo/apps/superuser_stats/admin.py
Labels: bug-fix, Back end
