Repository kobotoolbox/kpi, pull requests merged in 2023-10, with the labels that each got.

#4666 Cache service usage endpoint
  jsapp/js/account/usage.api.ts
  jsapp/js/account/usage.component.tsx
  jsapp/js/account/usage.module.scss
  jsapp/js/account/useUsage.hook.ts
  jsapp/js/api.ts
  jsapp/js/utils.ts
  kobo/apps/organizations/models.py
  kobo/apps/organizations/views.py
  kobo/apps/stripe/views.py
  kobo/settings/base.py
  kpi/serializers/v2/service_usage.py
  kpi/tests/api/v2/test_api_service_usage.py
  kpi/views/v2/service_usage.py
Labels: API, Back end, Front end

#4673 Make Usage page show correct date for single users with a Plan
  kobo/apps/organizations/views.py
  kpi/serializers/v2/service_usage.py
  kpi/tests/api/v2/test_api_service_usage.py
Labels: API, Back end

#4664 Fix mini audio play button requiring two clicks to play
  jsapp/js/components/common/miniAudioPlayer.scss
  jsapp/js/components/common/miniAudioPlayer.tsx
Labels: bug-fix, Front end

#4677 Enforce `Default` when only one form disclaimer is set
  kobo/apps/form_disclaimer/forms.py
Labels: bug-fix, Back end

#4659 Use Object.assign() instead of npm package 'object-assign'
  jsapp/js/app.js
  jsapp/js/assetParserUtils.ts
  jsapp/js/components/drawer.es6
  jsapp/js/components/formViewSideTabs.es6
  jsapp/js/components/metadataEditor.es6
  jsapp/js/components/permissions/userAssetPermsEditor.es6
  jsapp/js/components/reports/reportStyleSettings.es6
  jsapp/js/dataInterface.ts
  jsapp/js/editorMixins/editableForm.es6
  jsapp/js/libs/reactBemComponents.es6
  jsapp/js/mixins.tsx
  jsapp/js/searches.es6
  jsapp/js/stores.es6
  jsapp/js/utils.ts
  package-lock.json
  package.json
Labels: dependencies, Front end

#4679 Fix 500 error when previewing multilanguage forms with disclaimer message
  kobo/apps/form_disclaimer/models.py
  kpi/tests/api/v2/test_api_asset_snapshots.py
  kpi/utils/xml.py
Labels: bug-fix

#4682 Make `name` field required by default
  kobo/apps/accounts/tests/test_email_content.py
  kobo/settings/base.py
  kpi/migrations/0051_set_free_tier_thresholds_to_default.py
  kpi/migrations/0053_set_user_fullname_required_by_default.py
  kpi/tests/test_registration.py
Labels: Back end

#4686 Fix 500 error when loading projects list with PostgreSQL 13 and older
  kpi/filters.py
  kpi/utils/django_orm_helper.py
Labels: bug-fix

#4681 [ TASK-164 ] Do not use soft deleted attachments
  kpi/deployment_backends/kc_access/shadow_models.py
  kpi/deployment_backends/kobocat_backend.py
Labels: Back end

#4697 Make Button component more closely follow ARIA conventions
  jsapp/js/components/common/button.scss
  jsapp/js/components/common/button.tsx
Labels: enhancement, Front end
