Repository kobotoolbox/kpi, pull requests merged in 2023-09, with the labels that each got.

#4606 Use fuzzy integer for tests which assert of number of queries
  kobo/apps/accounts/tests/test_current_user.py
  kobo/apps/accounts/tests/test_social_account.py
  kobo/apps/organizations/tests/test_organizations_api.py
  kobo/apps/subsequences/tests/test_submission_extras_api_post.py
Labels: Back end

#4600 Updated UI based on figma changes for billing
  jsapp/js/account/plan.component.tsx
  jsapp/js/account/plan.module.scss
Labels: Front end

#4613 Fix edit not available in in-app messages Admin section
  kobo/apps/help/admin.py
Labels: high priority, bug-fix, Back end

#4573 Block API endpoints access to users when their password has been invalidated by a superuser
  hub/models/extra_user_detail.py
  jsapp/js/router/invalidatedPassword.component.tsx
  kobo/apps/accounts/mfa/views.py
  kobo/apps/accounts/tests/test_current_user.py
  kobo/apps/accounts/tests/test_email.py
  kobo/apps/accounts/tests/test_social_account.py
  kobo/apps/accounts/views.py
  kobo/apps/audit_log/permissions.py
  kobo/apps/help/permissions.py
  kobo/apps/languages/views/base.py
  kobo/apps/organizations/permissions.py
  kobo/apps/organizations/tests/test_organizations_api.py
  kobo/apps/organizations/views.py
  kobo/apps/project_views/views.py
  kobo/apps/stripe/views.py
  kobo/apps/subsequences/tests/test_submission_extras_api_post.py
  kobo/settings/base.py
  kpi/exceptions.py
  kpi/mixins/validation_password_permission.py
  kpi/password_validation.py
  kpi/permissions.py
  kpi/serializers/current_user.py
  kpi/tests/api/test_api_current_user.py
  kpi/tests/api/test_api_environment.py
  kpi/tests/api/v2/test_api_imports.py
  kpi/tests/api/v2/test_api_invalid_password_access.py
  kpi/tests/base_test_case.py
  kpi/tests/test_passwords.py
  kpi/views/current_user.py
  kpi/views/v2/asset_usage.py
  kpi/views/v2/service_usage.py
  kpi/views/v2/user.py
Labels: API, Back end

#4624 Fix wrong language (i.e. English) being picked instead of detected language in language selector
  hub/middleware.py
  kobo/settings/base.py
Labels: bug-fix, Back end

#4610 Add UI language support for Thai, Nepali, Vietnamese, and Indonesian
  kobo/settings/base.py
Labels: translations, Back end

#4601 Update copy/styling for usage limit banners and modals
  jsapp/js/account/plan.component.tsx
  jsapp/js/account/stripe.api.ts
  jsapp/js/account/usage.component.tsx
  jsapp/js/components/common/button.scss
  jsapp/js/components/usageContainer.module.scss
  jsapp/js/components/usageContainer.tsx
  jsapp/js/components/usageLimits/limitNotifications.component.tsx
  jsapp/js/components/usageLimits/overLimitBanner.component.tsx
  jsapp/js/components/usageLimits/overLimitBanner.module.scss
  jsapp/js/components/usageLimits/overLimitModal.component.tsx
  jsapp/js/components/usageLimits/overLimitModal.module.scss
  jsapp/js/components/usageLimits/usageCalculations.ts
  jsapp/js/hooks/README.md
  jsapp/js/hooks/useWhen.hook.ts
  jsapp/js/hooks/useWhenStripeIsEnabled.hook.ts
  jsapp/js/projects/customViewRoute.tsx
  jsapp/js/projects/myProjectsRoute.tsx
Labels: Front end

#4634 Fixes annual price showing as a large monthly amount
  jsapp/js/account/plan.component.tsx
Labels: Front end

#4637 Allow `gif` and `webp` extensions to be uploaded in markdown editor
  kobo/settings/base.py
Labels: enhancement, Back end

#4635 Account for null XForm instances in service_usage endpoint
  kpi/deployment_backends/kc_access/shadow_models.py
  kpi/serializers/v2/service_usage.py
  kpi/tests/api/v2/test_api_asset_usage.py
Labels: API, Back end

#4510 Rename tracker tests to get picked up by pytest
  kobo/apps/trackers/tests/__init__.py
  kobo/apps/trackers/tests/test_trackers.py
Labels: Back end

#4647 Fix CSP problem with language picker on login/signup page
  kobo/apps/accounts/templates/account/base.html
  static/js/language_dropdown.js
Labels: Front end

#4640 Stripe endpoint improvements
  kobo/apps/stripe/tests/test_link_creation_api.py
  kobo/apps/stripe/views.py
Labels: enhancement, API, Back end

#4658 Support animated pictures on drap&drop upload with Admin markdown editor.
  kobo/apps/markdownx_uploader/forms.py
Labels: bug-fix, Back end

#4653 Add check that `SOCIALACCOUNT_PROVIDERS` don't use kobo as ID
  kobo/apps/accounts/apps.py
Labels: bug, Back end
