Repository kobotoolbox/kpi, pull requests merged in 2023-06, with the labels that each got.

#4444 Add Bengali, Myanmar, Nyanja/Chewa to interface translations list
  kobo/settings/base.py
Labels: translations

#4441 Fix spacing for customizable email template
  kobo/apps/accounts/templates/account/email/email_confirmation_signup_message.txt
Labels: Back end

#4435 Add `date_joined` filter for super user reports
  kobo/apps/superuser_stats/tasks.py
  kobo/apps/superuser_stats/views.py
Labels: reports, Back end

#4459 Add Nyanja language to supported Django languages
  kobo/static_lists.py
Labels: bug-fix
