Repository kobotoolbox/kpi, pull requests merged in 2023-02, with the labels that each got.

#4100 Allow non-owners to view asset versions
  kpi/permissions.py
  kpi/tests/api/v2/test_api_assets.py
  kpi/views/v2/asset_version.py
Labels: API, backend

#4268 Fix anonymous access regression
  jsapp/js/router/allRoutes.es6
  jsapp/js/router/routerConstants.ts
  jsapp/js/router/routerUtils.ts
Labels: high priority

#3984 Create endpoint for total and daily submission counts
  kobo/settings/base.py
  kpi/deployment_backends/base_backend.py
  kpi/deployment_backends/kobocat_backend.py
  kpi/deployment_backends/mock_backend.py
  kpi/serializers/v2/asset_counts.py
  kpi/tests/api/v2/test_api_asset_counts.py
  kpi/tests/api/v2/test_api_assets.py
  kpi/urls/router_api_v2.py
  kpi/utils/mongo_helper.py
  kpi/views/v2/asset.py
  kpi/views/v2/asset_counts.py
Labels: Back end

#4282 Always use autocomplete inputs for `User` field in Django Admin
  hub/admin.py
  kobo/apps/accounts/admin.py
  kobo/apps/accounts/models.py
Labels: enhancement, Back end

#4281 Validate usernames the same way in Django Admin and registration form
  hub/admin.py
  kobo/apps/accounts/admin.py
  kobo/apps/accounts/forms.py
  kobo/apps/accounts/models.py
  kobo/apps/superuser_stats/admin.py
Labels: bug-fix, Back end

#4267 Avoid redundant building steps on container start-up
  Dockerfile
  docker/init.bash
Labels: Back end

#4291 Add endpoint for Stripe's webhook
  kpi/urls/__init__.py
Labels: Back end
