Repository kobotoolbox/kpi, pull requests merged in 2023-01, with the labels that each got.

#4032 Remove obsolete `OneTimeAuthenticationKey`
  kpi/migrations/0045_remove_onetimeauthenticationkey.py
  kpi/models/__init__.py
  kpi/models/authorized_application.py
  kpi/serializers/__init__.py
  kpi/serializers/v1/one_time_authentication_key.py
  kpi/urls/__init__.py
  kpi/urls/router_api_v1.py
  kpi/urls/router_api_v2.py
  kpi/views/__init__.py
  kpi/views/v1/__init__.py
  kpi/views/v1/one_time_authentication_key.py
Labels: backend

#4225 Fix assets submission count missing with 'view_submissions' of project views
  jsapp/js/components/submissions/submissionModal.es6
  kobo/apps/project_views/migrations/0001_initial.py
  kobo/apps/project_views/models/project_view.py
  kpi/constants.py
  kpi/deployment_backends/base_backend.py
  kpi/deployment_backends/kobocat_backend.py
  kpi/deployment_backends/mock_backend.py
  kpi/mixins/object_permission.py
  kpi/permissions.py
  kpi/serializers/v2/asset.py
  kpi/serializers/v2/service_usage.py
  kpi/tests/api/v2/test_api_asset_snapshots.py
  kpi/tests/api/v2/test_api_assets.py
  kpi/tests/api/v2/test_api_service_usage.py
  kpi/tests/test_project_views_utils.py
  kpi/views/v2/asset.py
  kpi/views/v2/asset_snapshot.py
  kpi/views/v2/service_usage.py
Labels: API, blocked, backend

#4232 Add Kosovo to countries static list
  kobo/static_lists.py
Labels: API, backend

#4227 Allow 2FA with Single Sign-On
  kobo/apps/accounts/adapter.py
  kobo/apps/accounts/forms.py
  kobo/apps/accounts/mfa/forms.py
  kobo/apps/accounts/mfa/views.py
Labels: enhancement, backend
