Repository kobotoolbox/kpi, pull requests merged in 2023-07, with the labels that each got.

#4518 Set date and time correctly when project is deployed
  kpi/models/asset_version.py
  kpi/tests/test_asset_versions.py
Labels: bug-fix, Back end

#4280 Add NLP usage to Users' Statistics superuser report
  kobo/apps/superuser_stats/tasks.py
Labels: Back end

#4533 Validate password based on (Constance) settings in Django Admin
  dependencies/pip/dev_requirements.txt
  dependencies/pip/requirements.in
  dependencies/pip/requirements.txt
  hub/migrations/0012_add_common_passwords_file.py
  hub/migrations/0013_alter_configurationfile_slug.py
  hub/models.py
  hub/tests/test_configurationfile.py
  kobo/apps/accounts/forms.py
  kobo/apps/accounts/tests/test_email_content.py
  kobo/apps/subsequences/constants.py
  kobo/settings/base.py
  kobo/settings/testing.py
  kpi/password_validation.py
  kpi/serializers/current_user.py
  kpi/tests/api/test_api_current_user.py
  kpi/tests/api/test_api_environment.py
  kpi/tests/test_passwords.py
  kpi/tests/test_registration.py
  kpi/views/environment.py
Labels: API, Back end

#4547 Bump `pip-tools` version to 7.x.x
  .github/workflows/pytest.yml
  Dockerfile
Labels: bug-fix, Back end

#4543 Restrict MFA based on subscription when Stripe is enabled
  jsapp/js/account/security/mfa/mfaSection.component.tsx
  jsapp/js/account/security/mfa/mfaSection.scss
  jsapp/js/account/stripe.utils.ts
  jsapp/js/actions/mfaActions.ts
  kobo/apps/accounts/adapter.py
  kobo/apps/accounts/mfa/serializers.py
  kobo/apps/accounts/mfa/tests/test_login.py
  kobo/apps/accounts/mfa/views.py
  kobo/apps/accounts/utils.py
  kobo/apps/stripe/tests/test_mfa_login.py
Labels: Back end

#4497 Add labels to User and Project metadata
  jsapp/scss/stylesheets/partials/_registration.scss
  kobo/apps/accounts/forms.py
  kobo/apps/accounts/tests/test_forms.py
  kobo/settings/base.py
  kpi/fields/jsonschema_form_field.py
Labels: Back end
