Repository kobotoolbox/kpi, pull requests merged in 2023-11, with the labels that each got.

#4696 Update ChangePlanView
  kobo/apps/organizations/models.py
  kobo/apps/organizations/views.py
  kobo/apps/stripe/serializers.py
  kobo/apps/stripe/tests/test_customer_portal_api.py
  kobo/apps/stripe/tests/test_modify_subscription_api.py
  kobo/apps/stripe/views.py
  kpi/serializers/v2/service_usage.py
Labels: API, Back end

#4676 Added logic to support all audio formats in the player
  jsapp/js/components/common/miniAudioPlayer.tsx
  jsapp/js/components/submissions/submissionUtils.ts
Labels: Front end

#4738 Don't prevent users from saving an existing social application due to provider ID validation
  kobo/apps/django_allauth/admin.py
Labels: bug, Back end
