Repository kobotoolbox/kpi, pull requests merged in 2023-12, with the labels that each got.

#4741 Allow service account to fetch external xml for connected projects
  .gitlab-ci.yml
  kobo/settings/base.py
  kpi/permissions.py
Labels: API, Back end

#4749 Require "edit submissions", not "add submissions", for working with transcripts and translations
  kobo/apps/subsequences/api_view.py
  kobo/apps/subsequences/tests/test_submission_extras_api_post.py
Labels: API, Back end

#4692 Add Storage add-ons to the Plans page
  .gitignore
  jsapp/js/account/accountSidebar.tsx
  jsapp/js/account/dataStorage.scss
  jsapp/js/account/plans/addOnList.component.tsx
  jsapp/js/account/plans/addOnList.module.scss
  jsapp/js/account/plans/billingButton.component.tsx
  jsapp/js/account/plans/billingButton.module.scss
  jsapp/js/account/plans/confirmChangeModal.component.tsx
  jsapp/js/account/plans/confirmChangeModal.module.scss
  jsapp/js/account/plans/plan.component.tsx
  jsapp/js/account/plans/plan.module.scss
  jsapp/js/account/plans/planButton.component.tsx
  jsapp/js/account/routes.tsx
  jsapp/js/account/stripe.api.ts
  jsapp/js/account/stripe.types.ts
  jsapp/js/account/stripe.utils.ts
  jsapp/js/account/subscriptionStore.ts
  jsapp/js/account/usage/usage.api.ts
  jsapp/js/account/usage/usage.component.tsx
  jsapp/js/account/usage/usage.module.scss
  jsapp/js/account/usage/usageContainer.module.scss
  jsapp/js/account/usage/usageContainer.tsx
  jsapp/js/account/usage/useUsage.hook.ts
  jsapp/js/api.endpoints.ts
  jsapp/js/api.ts
  jsapp/js/components/languages/languagesListStore.ts
  jsapp/js/components/usageLimits/limitNotifications.component.tsx
  jsapp/js/components/usageLimits/useExceedingLimits.hook.ts
  jsapp/js/projects/customViewRoute.tsx
  jsapp/js/projects/customViewStore.ts
  jsapp/js/projects/myProjectsRoute.tsx
  jsapp/js/utils.ts
  jsapp/scss/sizes.scss
  kobo/apps/stripe/tests/test_modify_subscription_api.py
  kobo/apps/stripe/views.py
Labels: Front end

#4765 Fix npm front-end build error when starting container
  Dockerfile
Labels: bug-fix

#4748 Fix /organizations/{ORG ID}/service_usage/ and /stripe/products/ endpoint cache misses
  dependencies/pip/dev_requirements.txt
  dependencies/pip/requirements.in
  dependencies/pip/requirements.txt
  kobo/apps/organizations/views.py
  kobo/apps/stripe/views.py
  kobo/settings/base.py
  kpi/serializers/v2/service_usage.py
  kpi/views/v2/service_usage.py
Labels: bug-fix, Back end

#4774 Handle edits of submissions lacking UUIDs in XML
  kobo/apps/subsequences/models.py
  kpi/deployment_backends/base_backend.py
  kpi/deployment_backends/kobocat_backend.py
  kpi/deployment_backends/mock_backend.py
  kpi/models/asset_snapshot.py
  kpi/tests/api/v2/test_api_submissions.py
  kpi/tests/utils/mock.py
  kpi/views/v2/data.py
Labels: Back end

#4776 Lint, test, fix mongo helper partial permissions
  kpi/models/asset_user_partial_permission.py
  kpi/serializers/v2/asset_permission_assignment.py
  kpi/tests/api/v2/test_api_asset_permission_assignment.py
  kpi/tests/test_mongo_helper.py
  kpi/utils/mongo_helper.py
  kpi/views/v2/asset_permission_assignment.py
  pyproject.toml
Labels: Back end

#4779 Fix XLSX bulk library import, broken by #3765
  kpi/tests/api/v2/test_api_imports.py
  kpi/utils/rename_xls_sheet.py
Labels: Back end

#4762 Prevent bulk edit if the project is archived
  jsapp/js/components/submissions/tableBulkOptions.es6
Labels: Front end
