Repository kobotoolbox/kpi, pull requests merged in 2024-11, with the labels that each got.

#5118 [TASK-977] Switch account sidenav to style module
  jsapp/js/account/accountSidebar.module.scss
  jsapp/js/account/accountSidebar.scss
  jsapp/js/account/accountSidebar.tsx
Labels: Front end

#4925 [TASK-659] [TASK-556] Add NLP support for background-audio questions
  jsapp/js/assetUtils.ts
  jsapp/js/components/metadataEditor.es6
  jsapp/js/components/modalForms/bulkEditSubmissionsForm.es6
  jsapp/js/components/processing/nlpUsageLimitBlockModal/nlpUsageLimitBlockModal.component.tsx
  jsapp/js/components/processing/nlpUsageLimitBlockModal/nlpUsageLimitBlockModal.module.scss
  jsapp/js/components/processing/processingUtils.tests.ts
  jsapp/js/components/processing/processingUtils.ts
  jsapp/js/components/processing/routes.utils.ts
  jsapp/js/components/processing/sidebar/sidebarDisplaySettings.tsx
  jsapp/js/components/processing/sidebar/sidebarSubmissionMedia.tsx
  jsapp/js/components/processing/singleProcessingHeader.tsx
  jsapp/js/components/processing/singleProcessingStore.ts
  jsapp/js/components/processing/transcript/stepBegin.component.tsx
  jsapp/js/components/processing/transcript/stepConfig.component.tsx
  jsapp/js/components/submissions/submissionDataTable.tsx
  jsapp/js/components/submissions/submissionModal.tsx
  jsapp/js/components/submissions/table.tsx
  jsapp/js/components/submissions/tableConstants.ts
  jsapp/js/components/submissions/tableMediaPreview.es6
  jsapp/js/components/submissions/tableUtils.mocks.ts
  jsapp/js/components/submissions/tableUtils.tests.ts
  jsapp/js/components/submissions/tableUtils.ts
  jsapp/js/constants.ts
  jsapp/js/editorMixins/editableForm.es6
  jsapp/svg-icons/background-rec.svg
  kobo/apps/subsequences/actions/automatic_transcription.py
  kobo/apps/subsequences/actions/keyword_search.py
  kobo/apps/subsequences/actions/manual_transcription.py
  kobo/apps/subsequences/actions/qual.py
  kobo/apps/subsequences/actions/translation.py
  kobo/apps/subsequences/constants.py
  test/index.js
Labels: UI & UX, bug-fix, Back end, Front end

#5210 [TASK-882] [TASK-1186] Project activity details modal
  jsapp/js/components/activity/activity.constants.ts
  jsapp/js/components/activity/activityLogs.query.ts
  jsapp/js/components/activity/activityMessage.component.tsx
  jsapp/js/components/activity/activityMessage.module.scss
  jsapp/js/components/activity/formActivity.module.scss
  jsapp/js/components/activity/formActivity.tsx
Labels: Front end

#5137 feat(OpenRosa): support XLSForm `name` setting TASK-1074
  kobo/apps/openrosa/apps/viewer/models/data_dictionary.py
  kpi/constants.py
  kpi/tests/test_assets.py
Labels: Back end

#5216 refactor(AccessLogsExport): export in background TASK-1145
  kobo/apps/project_views/views.py
  kpi/tasks.py
  kpi/tests/test_export_tasks.py
Labels: Back end

#5222 refactor(billingAddons): normalize NLP usage naming TASK-1015
  kobo/apps/stripe/constants.py
  kobo/apps/stripe/tests/test_organization_usage.py
  kobo/apps/stripe/utils.py
  kobo/apps/trackers/tests/test_utils.py
Labels: Back end

#5226 chore(CODEOWNERS): fix typos
  .github/CODEOWNERS
Labels: workflow

#5219 feat(organizations): update page access permissions TASK-977
  jsapp/js/account/organizations/requireOrgOwner.component.tsx
  jsapp/js/account/organizations/validateOrgPermissions.component.tsx
  jsapp/js/account/routes.tsx
Labels: Front end

#5223 feat(projectHistoryLogs): create project history logs when related objects change TASK-944
  kobo/apps/audit_log/audit_actions.py
  kobo/apps/audit_log/base_views.py
  kobo/apps/audit_log/models.py
  kobo/apps/audit_log/tests/test_models.py
  kobo/apps/audit_log/tests/test_project_history_logs.py
  kobo/apps/hook/views/v2/hook.py
  kpi/models/asset_file.py
  kpi/models/paired_data.py
  kpi/views/v2/asset_file.py
  kpi/views/v2/paired_data.py
Labels: Back end

#5232 feat(organizations): remove hardcoded team label env var TASK-1083
  jsapp/js/envStore.ts
Labels: Front end

#5126 Upgrade pyxform to v2.1.1
  dependencies/pip/dev_requirements.txt
  dependencies/pip/requirements.in
  dependencies/pip/requirements.txt
  kobo/apps/openrosa/apps/api/tests/fixtures/Transportation Form.xml
  kobo/apps/openrosa/apps/main/tests/fixtures/transportation/transportation.xml
  kobo/apps/openrosa/apps/viewer/models/data_dictionary.py
  kpi/tests/test_asset_snapshots.py
  kpi/utils/pyxform_compatibility.py
Labels: Back end

#5196 feat(organizations): Add `mongo_uuid` field to XForm model and populate it TASK-957
  kobo/apps/openrosa/apps/api/tests/viewsets/test_xform_viewset.py
  kobo/apps/openrosa/apps/logger/migrations/0038_add_mongo_uuid_field_to_xform.py
  kobo/apps/openrosa/apps/logger/models/xform.py
  kobo/apps/openrosa/apps/viewer/models/parsed_instance.py
  kobo/apps/project_ownership/tests/api/v2/test_api.py
  kobo/apps/project_ownership/utils.py
  kpi/deployment_backends/openrosa_backend.py
  kpi/fixtures/conflicting_versions.json
  kpi/tests/test_mock_data_conflicting_version_exports.py
Labels: Back end

#5236 fix(projectsTable): use default cursor for non-clickable message row
  jsapp/js/projects/projectViews.module.scss
  jsapp/js/projects/projectsTable/projectsTableRow.module.scss
Labels: Front end

#5237 refactor(dataInterface): update organization prop from AccountResponse TS interface
  jsapp/js/dataInterface.ts
Labels: Front end

#5238 feat(xlsform): support `background-geopoint`… TASK-1195
  dependencies/pip/dev_requirements.txt
  dependencies/pip/requirements.in
  dependencies/pip/requirements.txt
Labels: Back end

#5229 style(projects): cleanup files and organize imports
  jsapp/js/projects/customViewRoute.tsx
  jsapp/js/projects/customViewStore.ts
  jsapp/js/projects/myProjectsRoute.tsx
  jsapp/js/projects/projectViews/projectsFieldsSelector.tsx
  jsapp/js/projects/projectViews/projectsFilter.tsx
  jsapp/js/projects/projectViews/projectsFilterEditor.tsx
  jsapp/js/projects/projectViews/viewSwitcher.tsx
  jsapp/js/projects/projectsTable/bulkActions/bulkDeletePrompt.tsx
  jsapp/js/projects/projectsTable/projectBulkActions.tsx
  jsapp/js/projects/projectsTable/projectQuickActions.tsx
  jsapp/js/projects/projectsTable/projectsTable.tsx
  jsapp/js/projects/projectsTable/projectsTableHeader.tsx
  jsapp/js/projects/projectsTable/projectsTableRow.tsx
  jsapp/js/projects/projectsTable/sortableProjectColumnHeader.tsx
Labels: Front end

#5243 fix(projectOwnership): allow re-requests for project transfers with expired invites TASK-1237
  kobo/apps/project_ownership/models/invite.py
  kobo/apps/project_ownership/tasks.py
  kobo/settings/base.py
  kpi/serializers/v2/asset.py
  kpi/tests/api/v1/test_api_assets.py
  kpi/tests/api/v2/test_api_assets.py
Labels: bug-fix, Back end

#5227 fix(billing): handle string usage limits TASK-1232
  kobo/apps/stripe/tests/test_organization_usage.py
  kobo/apps/stripe/utils.py
  kobo/apps/trackers/tests/test_utils.py
Labels: Back end

#5246 feat(organizations): always return `use_team_label` config value TASK-1167
  kpi/tests/api/test_api_environment.py
  kpi/views/environment.py
Labels: Back end

#5250 fix(button): projects filter button styles
  jsapp/js/components/common/button.scss
  jsapp/js/projects/projectViews/projectsFilter.module.scss
Labels: Front end

#5218 feat(organizations): add new asset endpoint for owners and admins TASK-960
  hub/models/extra_user_detail.py
  kobo/apps/hook/tests/hook_test_case.py
  kobo/apps/hook/utils/tests/__init__.py
  kobo/apps/hook/utils/tests/mixins.py
  kobo/apps/kobo_auth/models.py
  kobo/apps/openrosa/apps/api/viewsets/xform_submission_api.py
  kobo/apps/openrosa/apps/logger/models/xform.py
  kobo/apps/openrosa/libs/filters.py
  kobo/apps/openrosa/libs/utils/logger_tools.py
  kobo/apps/organizations/constants.py
  kobo/apps/organizations/exceptions.py
  kobo/apps/organizations/migrations/0006_update_organization_name.py
  kobo/apps/organizations/models.py
  kobo/apps/organizations/permissions.py
  kobo/apps/organizations/serializers.py
  kobo/apps/organizations/tests/test_organizations.py
  kobo/apps/organizations/tests/test_organizations_api.py
  kobo/apps/organizations/views.py
  kobo/apps/stripe/tests/test_customer_portal_api.py
  kobo/apps/stripe/tests/test_organization_usage.py
  kobo/apps/stripe/tests/test_subscription_api.py
  kobo/settings/base.py
  kpi/backends.py
  kpi/db_routers.py
  kpi/filters.py
  kpi/mixins/object_permission.py
  kpi/paginators.py
  kpi/permissions.py
  kpi/serializers/v2/asset.py
  kpi/tests/api/v2/test_api_asset_permission_assignment.py
  kpi/tests/api/v2/test_api_assets.py
  kpi/tests/api/v2/test_api_collections.py
  kpi/tests/api/v2/test_api_permissions.py
  kpi/tests/api/v2/test_api_submissions.py
  kpi/tests/base_test_case.py
  kpi/tests/kpi_test_case.py
  kpi/tests/test_organization.py
  kpi/tests/test_permissions.py
  kpi/tests/test_usage_calculator.py
  kpi/tests/utils/mixins.py
  kpi/utils/project_views.py
  kpi/views/v2/asset.py
  kpi/views/v2/asset_file.py
  kpi/views/v2/asset_snapshot.py
Labels: API, Back end

#5252 fix(organizations): styling for organization badge
  jsapp/js/components/header/mainHeader.component.tsx
  jsapp/js/components/header/mainHeader.module.scss
  jsapp/js/components/header/organizationBadge.module.scss
Labels: Front end

#5231 feat(service_health): combine legacy kobocat service check into primary TASK-931
  kobo/apps/openrosa/apps/main/service_health.py
  kobo/apps/openrosa/apps/main/urls.py
  kobo/apps/service_health/test_service_health.py
  kobo/apps/service_health/views.py
Labels: Back end

#5230 feat(projectHistoryLogs): record project history logs for imports TASK-944
  kobo/apps/audit_log/audit_actions.py
  kobo/apps/audit_log/models.py
  kobo/apps/audit_log/signals.py
  kobo/apps/audit_log/tests/test_models.py
  kobo/apps/audit_log/tests/test_project_history_logs.py
  kpi/fixtures/asset_with_settings_and_qa.json
  kpi/models/import_export_task.py
  kpi/tasks.py
  kpi/tests/api/v2/test_api_imports.py
  kpi/views/v1/import_task.py
  kpi/views/v2/import_task.py
Labels: Back end

#5251 refactor(projects): deduplicate code via UniversalProjectsRoute
  jsapp/js/components/permissions/transferProjects/projectOwnershipTransferModalWithBanner.tsx
  jsapp/js/components/permissions/transferProjects/projectTransferInviteBanner.module.scss
  jsapp/js/components/permissions/transferProjects/projectTransferInviteBanner.tsx
  jsapp/js/projects/customViewRoute.tsx
  jsapp/js/projects/myProjectsRoute.module.scss
  jsapp/js/projects/myProjectsRoute.tsx
  jsapp/js/projects/projectViews.module.scss
  jsapp/js/projects/projectViews/constants.ts
  jsapp/js/projects/universalProjectsRoute.tsx
Labels: Front end

#5260 style(universalTable) use Array<T> for columns prop
  jsapp/js/universalTable/paginatedQueryUniversalTable.component.tsx
Labels: Front end

#5262 refactor(organizations): add configurable redirect route to org validator TASK-975
  jsapp/js/account/routes.tsx
  jsapp/js/router/validateOrgPermissions.component.tsx
Labels: Front end

#5248 refactor(billing): normalize asr/mt limit naming TASK-1015
  jsapp/js/account/plans/planContainer.component.tsx
  jsapp/js/account/stripe.api.ts
  jsapp/js/account/stripe.types.ts
  jsapp/js/account/usage/usage.component.tsx
  jsapp/js/components/usageLimits/useExceedingLimits.hook.ts
Labels: Front end

#5256 refactor(organizations): update admin models for improved clarity TASK-965
  kobo/apps/organizations/admin/__init__.py
  kobo/apps/organizations/admin/organization.py
  kobo/apps/organizations/admin/organization_invite.py
  kobo/apps/organizations/admin/organization_owner.py
  kobo/apps/organizations/admin/organization_user.py
Labels: Back end

#5255 feat(organizations): manage member permissions on addition or removal via Django Admin TASK-965
  hub/admin/extend_user.py
  kobo/apps/kobo_auth/models.py
  kobo/apps/openrosa/apps/viewer/models/parsed_instance.py
  kobo/apps/organizations/admin/__init__.py
  kobo/apps/organizations/admin/organization.py
  kobo/apps/organizations/admin/organization_invite.py
  kobo/apps/organizations/admin/organization_owner.py
  kobo/apps/organizations/admin/organization_user.py
  kobo/apps/organizations/forms.py
  kobo/apps/organizations/tasks.py
  kobo/apps/organizations/utils.py
  kobo/apps/project_ownership/migrations/0003_create_proxy_and_add_invite_type.py
  kobo/apps/project_ownership/models/invite.py
  kobo/apps/project_ownership/models/transfer.py
  kobo/apps/project_ownership/serializers/invite.py
  kobo/apps/project_ownership/utils.py
  kobo/settings/base.py
Labels: Back end

#5254 refactor(organization): use autocomplete fields in Admin UI for organizations TASK-965
  hub/admin/extend_user.py
  hub/static/admin/css/inline_as_fieldset.css
  kobo/apps/kobo_auth/models.py
  kobo/apps/openrosa/apps/viewer/models/parsed_instance.py
  kobo/apps/organizations/admin.py
  kobo/apps/organizations/admin/__init__.py
  kobo/apps/organizations/admin/organization.py
  kobo/apps/organizations/admin/organization_invite.py
  kobo/apps/organizations/admin/organization_owner.py
  kobo/apps/organizations/admin/organization_user.py
  kobo/apps/organizations/forms.py
  kobo/apps/organizations/models.py
  kobo/apps/organizations/tasks.py
  kobo/apps/organizations/utils.py
  kobo/apps/project_ownership/migrations/0003_create_proxy_and_add_invite_type.py
  kobo/apps/project_ownership/models/invite.py
  kobo/apps/project_ownership/models/transfer.py
  kobo/apps/project_ownership/serializers/invite.py
  kobo/apps/project_ownership/utils.py
  kobo/settings/base.py
Labels: blocked, Back end

#5241 feat(projectHistoryLog): log exports TASK-944
  kobo/apps/audit_log/audit_actions.py
  kobo/apps/audit_log/base_views.py
  kobo/apps/audit_log/models.py
  kobo/apps/audit_log/tests/test_project_history_logs.py
  kpi/models/import_export_task.py
  kpi/views/v1/export_task.py
  kpi/views/v2/export_task.py
Labels: Back end

#5267 fix(InlineMessage): link styles
  jsapp/js/components/common/inlineMessage.scss
Labels: Front end

#5240 feat(organization): add new route for organization projects TASK-975
  jsapp/js/api.endpoints.ts
  jsapp/js/projects/myOrgProjectsRoute.tsx
  jsapp/js/projects/projectViews/constants.ts
  jsapp/js/projects/projectViews/viewSwitcher.tsx
  jsapp/js/projects/routes.tsx
  jsapp/js/router/router.tsx
  jsapp/js/router/routerConstants.ts
Labels: Front end

#5225 feat(projectHistoryLogs): remove audit logs according to constance configuration TASK-972
  jsapp/js/envStore.ts
  kobo/apps/audit_log/tasks.py
  kobo/apps/audit_log/tests/test_tasks.py
  kobo/settings/base.py
  kpi/tests/api/test_api_environment.py
  kpi/views/environment.py
Labels: Back end

#5271 fix: update failing export test with correct default support email TASK-1264
  kpi/tests/test_export_tasks.py
Labels: Back end

#5275 feat(Badge): add light-green and make label optional
  jsapp/js/components/common/badge.module.scss
  jsapp/js/components/common/badge.stories.tsx
  jsapp/js/components/common/badge.tsx
Labels: Front end

#5234 feat(organizations): account sidenav update for MMOs TASK-977
  jsapp/js/account/accountSidebar.module.scss
  jsapp/js/account/accountSidebar.tsx
  jsapp/svg-icons/users.svg
Labels: Front end

#5112 feat(openrosa): extract and return customized confirmation message
  kobo/apps/openrosa/apps/api/tests/viewsets/test_xform_submission_api.py
  kobo/apps/openrosa/apps/api/utils/xml.py
  kobo/apps/openrosa/apps/api/viewsets/xform_submission_api.py
  kobo/apps/openrosa/apps/main/tests/fixtures/transportation/instances/transport_with_custom_attribute/1335783522563.jpg
  kobo/apps/openrosa/apps/main/tests/fixtures/transportation/instances/transport_with_custom_attribute/transport_with_custom_attribute_01.xml
  kobo/apps/openrosa/apps/main/tests/fixtures/transportation/instances/transport_with_custom_attribute/transport_with_custom_attribute_02.xml
  kobo/apps/openrosa/apps/main/tests/fixtures/transportation/instances/transport_with_custom_attribute/transport_with_custom_attribute_and_different_root.xml
  kobo/apps/openrosa/apps/main/tests/fixtures/transportation/instances/transport_with_custom_attribute/transport_with_no_custom_attribute.xml
  kobo/apps/openrosa/libs/serializers/data_serializer.py
Labels: Back end

#5268 feat(Avatar): add more options TASK-980
  jsapp/js/components/common/avatar.module.scss
  jsapp/js/components/common/avatar.stories.tsx
  jsapp/js/components/common/avatar.tsx
  jsapp/js/components/header/accountMenu.tsx
  jsapp/scss/components/_kobo.navigation.scss
Labels: Front end

#5279 fix(MainHeader): disappearing on small screens
  jsapp/scss/components/_kobo.navigation.scss
Labels: Front end

#5278 fix(AccountSidebar): avoid top gap when scrollbar appears
  jsapp/js/account/accountSidebar.module.scss
Labels: Front end

#5244 fix(mediaFiles): fix wrong path when syncing media files to OpenRosa server storage TASK-1238
  kpi/deployment_backends/openrosa_backend.py
  kpi/tests/api/v2/test_api_submissions.py
  kpi/tests/test_deployment_backends.py
  kpi/tests/test_extended_file_field.py
Labels: Back end

#5264 test(jest): replace mocha-chrome with jest TASK-1234
  .github/workflows/npm-test.yml
  jsapp/jest/coffeeTransformer.js
  jsapp/jest/setupUnitTest.ts
  jsapp/jest/unit.config.ts
  jsapp/js/constants.ts
  package-lock.json
  package.json
  patches/mocha-chrome+2.2.0.patch
  scripts/hints.js
  test/helper/fauxChai.coffee
  test/xlform/group.tests.coffee
  test/xlform/inputParser.tests.coffee
  test/xlform/model.tests.coffee
  test/xlform/utils.tests.coffee
Labels: workflow, bug-fix, Front end

#5269 chore: remove in-browser mocha test environment
  jsapp/jest/unit.config.ts
  kobo/settings/base.py
  kpi/templates/browser_tests.html
  kpi/urls/__init__.py
  kpi/views/__init__.py
  package-lock.json
  package.json
  scripts/hints.js
  test/helper/phantomjs-shims.js
  test/index.js
  test/tests.html
  webpack/dev.server.js
  webpack/prod.config.js
  webpack/test.autobuild.js
  webpack/test.config.js
Labels: Back end, Front end

#5285 feat(organizations): auto-refresh on orgId change TASK-1247
  jsapp/js/account/stripe.api.ts
  jsapp/js/api.endpoints.ts
Labels: Front end

#5286 refactor(organizations): rename organizations directory
  jsapp/js/account/accountSidebar.tsx
  jsapp/js/account/organization/OrganizationSettingsRoute.tsx
  jsapp/js/account/organization/organization.utils.tsx
  jsapp/js/account/routes.constants.ts
Labels: Front end

#5287 feat(organizations): handle query error once at root TASK-1271
  jsapp/js/account/routes.tsx
  jsapp/js/account/stripe.api.ts
  jsapp/js/app.jsx
  jsapp/js/projects/routes.tsx
  jsapp/js/router/RequireOrg.tsx
  jsapp/js/router/RequireOrgPermissions.component.tsx
Labels: Front end

#5288 refactor(organizations): move useOrganizationQuery to separate file TASK-1219
  jsapp/js/account/accountSidebar.tsx
  jsapp/js/account/add-ons/addOnList.component.tsx
  jsapp/js/account/add-ons/oneTimeAddOnRow.component.tsx
  jsapp/js/account/billingContextProvider.component.tsx
  jsapp/js/account/organization/organizationQuery.ts
  jsapp/js/account/plans/plan.component.tsx
  jsapp/js/account/plans/planButton.component.tsx
  jsapp/js/account/routes.tsx
  jsapp/js/account/stripe.api.ts
  jsapp/js/account/stripe.types.ts
  jsapp/js/account/usage/usageProjectBreakdown.tsx
  jsapp/js/account/usage/useUsage.hook.ts
  jsapp/js/components/header/organizationBadge.component.tsx
  jsapp/js/projects/myOrgProjectsRoute.tsx
  jsapp/js/projects/projectViews/viewSwitcher.tsx
  jsapp/js/router/RequireOrg.tsx
  jsapp/js/router/RequireOrgPermissions.component.tsx
Labels: Front end

#5274 feat(organizations): update organizations endpoint to block post and delete requests TASK-964
  kobo/apps/organizations/tests/test_organizations_api.py
  kobo/apps/organizations/views.py
Labels: Back end

#5291 refactor(account): rename kebab-case dirs to camelCase
  jsapp/js/account/addOns/addOnList.component.tsx
  jsapp/js/account/addOns/addOnList.module.scss
  jsapp/js/account/addOns/addOns.component.tsx
  jsapp/js/account/addOns/addOns.module.scss
  jsapp/js/account/addOns/oneTimeAddOnRow.component.tsx
  jsapp/js/account/addOns/updateBadge.component.tsx
  jsapp/js/account/plans/plan.component.tsx
  jsapp/js/account/routes.constants.ts
  jsapp/js/account/usage/oneTimeAddOnUsageModal/oneTimeAddOnList/oneTimeAddOnList.component.tsx
  jsapp/js/account/usage/oneTimeAddOnUsageModal/oneTimeAddOnList/oneTimeAddOnList.module.scss
  jsapp/js/account/usage/oneTimeAddOnUsageModal/oneTimeAddOnUsageModal.component.tsx
  jsapp/js/account/usage/oneTimeAddOnUsageModal/oneTimeAddOnUsageModal.module.scss
  jsapp/js/account/usage/usageContainer.tsx
Labels: Front end

#5292 build(tsconfig): set lib to allow ES2021 functionalities
  tsconfig.json
Labels: Front end

#5293 style(subscriptionStore): linter cleanup
  jsapp/js/account/subscriptionStore.ts
Labels: Front end

#5294 refactor(organizations): simplify shouldUseTeamLabel
  jsapp/js/account/organization/organization.utils.tsx
Labels: Front end

#5233 feat(organizations): disable email updates for regular organization members TASK-997
  jsapp/js/account/security/email/emailSection.component.tsx
  jsapp/js/account/security/email/emailSection.module.scss
Labels: Front end

#5235 feat(organizations): add endpoints to handle organization members TASK-963
  kobo/apps/organizations/permissions.py
  kobo/apps/organizations/serializers.py
  kobo/apps/organizations/tests/test_organization_members_api.py
  kobo/apps/organizations/tests/test_organizations_api.py
  kobo/apps/organizations/views.py
  kpi/urls/router_api_v2.py
Labels: Back end

#5261 feat(organizations): members table TASK-980
  jsapp/js/account/organization/MembersRoute.tsx
  jsapp/js/account/organization/membersQuery.ts
  jsapp/js/account/organization/membersRoute.module.scss
  jsapp/js/account/routes.constants.ts
  jsapp/js/account/routes.tsx
  jsapp/js/api.endpoints.ts
  jsapp/js/query/queryKeys.ts
  jsapp/js/universalTable/universalTable.component.tsx
Labels: blocked, Front end

#5298 refactor(usage): rename ##placeholder## to :placeholder in urls for consistency sake
  jsapp/js/account/usage/usage.api.ts
Labels: Front end

#5301 chore: remove deprecated imports
  kobo/apps/accounts/tests/test_backend.py
  kobo/apps/audit_log/tests/test_models.py
  kobo/apps/audit_log/tests/test_signals.py
  kobo/apps/help/views.py
  kobo/apps/openrosa/apps/api/viewsets/xform_list_api.py
  kobo/apps/openrosa/apps/logger/tests/models/test_instance.py
  kobo/apps/openrosa/apps/logger/tests/test_form_submission.py
  kobo/apps/openrosa/apps/viewer/tasks.py
  kobo/apps/openrosa/libs/data/tests/test_tools.py
  kobo/apps/openrosa/libs/mixins/openrosa_headers_mixin.py
  kobo/apps/openrosa/libs/utils/logger_tools.py
  kobo/apps/stripe/tests/test_organization_usage.py
  kobo/apps/subsequences/actions/base.py
  kpi/deployment_backends/openrosa_backend.py
  kpi/models/import_export_task.py
  kpi/serializers/v2/user.py
  kpi/tests/test_asset_versions.py
  kpi/tests/test_deployment_backends.py
  kpi/tests/test_export_tasks.py
  kpi/tests/test_mock_data_exports.py
  kpi/utils/mongo_helper.py
  kpi/views/v2/open_rosa.py
Labels: Back end

#5270 feat(projectHistoryLogs): project history logs for bulk actions TASK-1229
  kobo/apps/audit_log/base_views.py
  kobo/apps/audit_log/middleware.py
  kobo/apps/audit_log/models.py
  kobo/apps/audit_log/tests/test_project_history_logs.py
  kpi/serializers/v2/asset.py
Labels: Back end

#5272 fix(OpenRosa): correct detection of root node tag name for XForm surveys TASK-1258
  kobo/apps/openrosa/apps/logger/models/xform.py
  kobo/apps/openrosa/apps/logger/tests/test_simple_submission.py
  kobo/apps/openrosa/apps/viewer/management/commands/mark_start_times.py
  kobo/apps/openrosa/apps/viewer/management/commands/set_uuid_in_xml.py
  kobo/apps/openrosa/apps/viewer/models/data_dictionary.py
  kobo/apps/openrosa/libs/utils/logger_tools.py
  kpi/models/asset_snapshot.py
  kpi/utils/xml.py
Labels: bug-fix, Back end

#5305 feat(InlineMessage): add new type TASK-987
  jsapp/js/components/common/inlineMessage.scss
  jsapp/js/components/common/inlineMessage.tsx
Labels: Front end

#5303 refactor(organizations): add of useSession hook TASK-1305
  jsapp/js/stores/useSession.tsx
Labels: Front end

#5307 chore(attachmentStorage): Update sync management command to support no lock during execution
  kobo/apps/openrosa/apps/logger/constants.py
  kobo/apps/openrosa/apps/logger/management/commands/update_attachment_storage_bytes.py
  kobo/apps/openrosa/apps/logger/tasks.py
  kpi/tasks.py
Labels: Back end

#5306 refactor(subscriptionStore): move planName TASK-987
  jsapp/js/account/subscriptionStore.ts
  jsapp/js/account/usage/yourPlan.component.tsx
Labels: Front end

#5289 feat(organizations): update is_mmo to identify mmo subscriptions TASK-1231
  kobo/apps/organizations/models.py
  kobo/apps/organizations/tests/test_organizations_api.py
  kobo/apps/organizations/views.py
  kobo/apps/stripe/tests/test_organization_usage.py
  kobo/apps/stripe/tests/utils.py
  kpi/tests/test_usage_calculator.py
Labels: Back end

#5290 refactor(organizations): code cleanup and patch data cleanup in account settings and tos view TASK-1292
  jsapp/js/account/account.utils.ts
  jsapp/js/account/accountFieldsEditor.component.tsx
  jsapp/js/account/accountSettingsRoute.tsx
  jsapp/js/tos/tosForm.component.tsx
Labels: Front end
