Repository kobotoolbox/kpi, pull requests merged in 2024-02, with the labels that each got.

#4834 Optimization: Avoid fetching all anonymous user permissions every time
  kpi/mixins/object_permission.py
  kpi/serializers/v2/asset.py
  kpi/views/v2/asset.py
Labels: enhancement, Back end

#4832 Handle submission XML with namespace or encoding declaration
  kpi/deployment_backends/base_backend.py
  kpi/deployment_backends/kobocat_backend.py
  kpi/deployment_backends/mock_backend.py
  kpi/tests/api/v2/test_api_submissions.py
  kpi/tests/test_utils.py
  kpi/tests/utils/mock.py
  kpi/utils/xml.py
  kpi/views/v2/data.py
Labels: Back end

#4850 Fix broken admin reports
  kobo/apps/superuser_stats/tasks.py
  kobo/apps/superuser_stats/views.py
  kpi/models/asset_file.py
Labels: bug-fix, Back end

#4856 [TASK-604] Fix infinite spinner with speechless audio file
  kobo/apps/subsequences/exceptions.py
  kobo/apps/subsequences/integrations/google/google_transcribe.py
  kobo/apps/subsequences/models.py
Labels: bug-fix, Back end
