Repository kobotoolbox/kpi, pull requests merged in 2024-01, with the labels that each got.

#4792 Add $nin and $not to allowed query operators
  kpi/utils/mongo_helper.py
Labels: enhancement, API, Back end

#4608 Update mass user email script
  scripts/mass_user_emails.py
Labels: Back end

#4605 Return a 401 HTTP code when user is not authenticated
  kobo/apps/audit_log/tests/test_api_audit_log.py
  kobo/apps/languages/tests/api/v2/test_api_languages.py
  kobo/apps/languages/tests/api/v2/test_api_services.py
  kobo/apps/organizations/tests/test_organizations_api.py
  kobo/apps/stripe/tests/test_customer_portal_api.py
  kobo/apps/stripe/tests/test_link_creation_api.py
  kobo/apps/stripe/tests/test_modify_subscription_api.py
  kobo/apps/stripe/tests/test_one_time_addons_api.py
  kobo/apps/stripe/tests/test_subscription_api.py
  kobo/settings/base.py
  kpi/authentication.py
  kpi/tests/api/v2/test_api_asset_bulk_actions.py
  kpi/tests/api/v2/test_api_asset_usage.py
  kpi/tests/api/v2/test_api_authentication.py
  kpi/tests/api/v2/test_api_permissions.py
  kpi/tests/api/v2/test_api_service_usage.py
  kpi/tests/api/v2/test_api_users.py
  kpi/tests/test_token.py
Labels: API, Back end

#4811 `Could not find attachment` fix with filenames which contain non-latin characters.
  jsapp/js/components/processing/singleProcessingSubmissionDetails.tsx
  jsapp/js/components/submissions/submissionDataTable.tsx
  jsapp/js/components/submissions/submissionUtils.mocks.es6
  jsapp/js/components/submissions/submissionUtils.tests.es6
  jsapp/js/components/submissions/submissionUtils.ts
  jsapp/js/components/submissions/table.es6
  jsapp/js/dataInterface.ts
  kpi/constants.py
  kpi/deployment_backends/kc_access/shadow_models.py
  kpi/deployment_backends/kc_access/storage.py
  kpi/deployment_backends/kobocat_backend.py
  kpi/models/asset.py
  kpi/serializers/v2/user.py
Labels: bug-fix, Back end, Front end

#4825 Fix NLP translation editing
  kobo/apps/subsequences/actions/translation.py
  kobo/apps/subsequences/tests/test_submission_extras_api_post.py
Labels: CRITICAL

#4828 Fix 500 error when loading table view
  kpi/models/asset.py
  kpi/tests/test_asset_content.py
Labels: CRITICAL, bug-fix
