Repository kobotoolbox/kpi, pull requests merged in 2024-08, with the labels that each got.

#4884 Add endpoints that redirect to Enketo for editing or viewing a submission
  kpi/tests/api/v2/test_api_submissions.py
  kpi/views/v2/data.py
Labels: Back end

#5051 Add toast error message for invalid email addresses when changing email
  jsapp/js/account/security/email/emailSection.component.tsx
Labels: Front end

#5049 Update English wording
  jsapp/js/i18nMissingStrings.es6
  jsapp/xlform/src/view.rowDetail.SkipLogic.coffee
Labels: Front end

#5035 Update audit logs for faster querying
  kobo/apps/audit_log/migrations/0007_alter_auditlog_action_and_more.py
  kobo/apps/audit_log/models.py
Labels: Back end

#5044 Get source from requests
  dependencies/pip/dev_requirements.in
  dependencies/pip/dev_requirements.txt
  dependencies/pip/requirements.in
  dependencies/pip/requirements.txt
  kobo/apps/openrosa/apps/viewer/tests/test_viewer_tools.py
  kobo/apps/openrosa/libs/utils/viewer_tools.py
Labels: Back end

#5048 [Task 931] Minimal health-check middleware
  hub/middleware.py
  kobo/apps/openrosa/apps/main/service_health.py
  kobo/apps/openrosa/apps/main/tests/test_service_health_minimal.py
  kobo/apps/openrosa/apps/main/urls.py
  kobo/apps/service_health/middleware.py
  kobo/apps/service_health/test_service_health_minimal.py
  kobo/apps/service_health/urls.py
  kobo/apps/service_health/views.py
  kobo/settings/base.py
Labels: Back end

#5001 Set up React Query to simplify state management
  .eslintrc.js
  jsapp/js/alertify.ts
  jsapp/js/app.jsx
  jsapp/js/formbuild/renderInBackbone.es6
  jsapp/js/query/queryClient.ts
  package-lock.json
  package.json
Labels: UI & UX, workflow, dependencies, Front end

#5055 Record all logins as access logs
  kobo/apps/accounts/tests/test_backend.py
  kobo/apps/audit_log/models.py
  kobo/apps/audit_log/signals.py
  kobo/apps/audit_log/tests/api/v2/test_api_audit_log.py
  kobo/apps/audit_log/tests/test_models.py
  kobo/apps/audit_log/tests/test_signals.py
  kobo/apps/openrosa/apps/viewer/tests/test_viewer_tools.py
  kpi/constants.py
Labels: Back end

#5037 Code refactoring - Replace shadow models imports with their openrosa app counterparts
  hub/admin/extend_user.py
  hub/models/extra_user_detail.py
  kobo/apps/accounts/mfa/models.py
  kobo/apps/form_disclaimer/models.py
  kobo/apps/kobo_auth/models.py
  kobo/apps/openrosa/apps/logger/models/__init__.py
  kobo/apps/openrosa/apps/logger/models/attachment.py
  kobo/apps/openrosa/apps/logger/models/xform.py
  kobo/apps/openrosa/apps/logger/tests/test_simple_submission.py
  kobo/apps/openrosa/apps/main/models/user_profile.py
  kobo/apps/project_ownership/tests/api/v2/test_api.py
  kobo/apps/project_ownership/utils.py
  kobo/apps/shadow_model/__init__.py
  kobo/apps/subsequences/tests/test_submission_extras_api_post.py
  kobo/apps/superuser_stats/migrations/0001_initial.py
  kobo/apps/superuser_stats/migrations/__init__.py
  kobo/apps/superuser_stats/models.py
  kobo/apps/superuser_stats/tasks.py
  kobo/apps/trackers/submission_utils.py
  kobo/apps/trash_bin/models/project.py
  kpi/deployment_backends/base_backend.py
  kpi/deployment_backends/kc_access/shadow_models.py
  kpi/deployment_backends/kobocat_backend.py
  kpi/deployment_backends/mock_backend.py
  kpi/management/commands/sync_kobocat_perms.py
  kpi/management/commands/sync_kobocat_xforms.py
  kpi/serializers/v2/service_usage.py
  kpi/signals.py
  kpi/tests/api/v2/test_api_attachments.py
  kpi/tests/api/v2/test_api_paired_data.py
  kpi/tests/utils/mock.py
  kpi/utils/database.py
  kpi/utils/project_view_exports.py
  kpi/views/v2/attachment.py
Labels: Back end

#5070 fix thumbnail resizing with FileSystemStorage
  kobo/apps/openrosa/libs/utils/image_tools.py
Labels: bug-fix, Back end

#5071 Black format audit logs
  kobo/apps/audit_log/__init__.py
  kobo/apps/audit_log/migrations/0001_initial.py
  kobo/apps/audit_log/migrations/0001_squashed_0006_remove_index_together.py
  kobo/apps/audit_log/migrations/0003_alter_auditlog_user.py
  kobo/apps/audit_log/migrations/0004_populate_user_uids.py
  kobo/apps/audit_log/migrations/0007_alter_auditlog_action_and_more.py
  kobo/apps/audit_log/models.py
  kobo/apps/audit_log/permissions.py
  kobo/apps/audit_log/serializers.py
  kobo/apps/audit_log/tests/api/v2/test_api_audit_log.py
  kobo/apps/audit_log/tests/test_models.py
  kobo/apps/audit_log/tests/test_signals.py
  kobo/apps/audit_log/views.py
Labels: Back end

#5069 (backport) Fix 500 error when submitting data after changing the password
  dependencies/pip/dev_requirements.txt
  dependencies/pip/requirements.in
  dependencies/pip/requirements.txt
  kobo/settings/base.py
Labels: bug-fix, Back end

#5059 Fix bug causing large asynchronous translations to fail
  jsapp/js/components/processing/README.md
  jsapp/js/components/processing/processingActions.ts
  jsapp/js/components/processing/singleProcessingStore.ts
  jsapp/js/components/processing/translations/stepConfigAuto.component.tsx
  jsapp/js/components/processing/transxSelector.tsx
  jsapp/js/components/submissions/table.scss
  kobo/apps/subsequences/actions/automatic_transcription.py
  kobo/apps/subsequences/actions/translation.py
  kobo/apps/subsequences/constants.py
  kobo/apps/subsequences/exceptions.py
  kobo/apps/subsequences/integrations/google/__init__.py
  kobo/apps/subsequences/integrations/google/base.py
  kobo/apps/subsequences/integrations/google/google_transcribe.py
  kobo/apps/subsequences/integrations/google/google_translate.py
  kobo/apps/subsequences/integrations/misc.py
  kobo/apps/subsequences/integrations/translate.py
  kobo/apps/subsequences/models.py
  kobo/apps/subsequences/tasks/__init__.py
  kobo/apps/subsequences/tasks/handle_translation_operation.py
  kobo/apps/subsequences/tasks/handlers.py
  kobo/apps/subsequences/tasks/queues.py
  kobo/apps/subsequences/tests/test_automatic_transcription.py
  kobo/apps/subsequences/tests/test_nlp_integration.py
  kobo/apps/subsequences/tests/test_proj_advanced_features.py
  kobo/apps/subsequences/tests/test_submission_extras_api_post.py
  kobo/apps/subsequences/tests/test_submission_extras_content.py
  kobo/settings/base.py
Labels: bug-fix, Back end, Front end

#5063 Categorize audit logs by log type
  kobo/apps/audit_log/migrations/0008_auditlog_log_type.py
  kobo/apps/audit_log/models.py
  kobo/apps/audit_log/serializers.py
  kobo/apps/audit_log/tests/api/v2/test_api_audit_log.py
  kobo/apps/audit_log/tests/test_models.py
  kobo/apps/audit_log/views.py
  kobo/apps/trash_bin/tasks.py
  kobo/apps/trash_bin/tests/test_utils.py
  kobo/apps/trash_bin/utils.py
  kpi/tests/api/v2/test_api_submissions.py
  kpi/views/v2/data.py
Labels: Back end

#5065 Record one-time authentications as access logs
  kobo/apps/audit_log/mixins.py
  kobo/apps/audit_log/models.py
  kobo/apps/audit_log/tests/test_one_time_auth.py
  kobo/apps/openrosa/libs/authentication.py
  kobo/settings/base.py
  kpi/authentication.py
  kpi/constants.py
Labels: Back end

#5072 Fix broken tests
  kobo/apps/audit_log/tests/test_one_time_auth.py
  kpi/authentication.py
Labels: Back end

#5066 Fix audit log api documentation
  kobo/apps/audit_log/migrations/0009_alter_auditlog_action.py
  kobo/apps/audit_log/models.py
  kobo/apps/audit_log/serializers.py
  kobo/apps/audit_log/tests/api/v2/test_api_audit_log.py
  kobo/apps/audit_log/views.py
Labels: Back end

#5074 Fix bug causing transcriptions/translations and qualitative analysis responses to not be displayed in the Data table
  jsapp/js/components/submissions/table.tsx
Labels: bug-fix, Front end

#5076 Fix import formatting
  kobo/apps/audit_log/migrations/0001_initial.py
  kobo/apps/audit_log/migrations/0001_squashed_0006_remove_index_together.py
  kobo/apps/audit_log/migrations/0003_alter_auditlog_user.py
  kobo/apps/audit_log/models.py
  kobo/apps/audit_log/serializers.py
  kobo/apps/audit_log/urls.py
  pyproject.toml
Labels: Back end

#5042 Code refactoring - Remove shadow models and KobocatDeploymentBackend class
  kobo/apps/openrosa/apps/logger/models/xform.py
  kobo/apps/openrosa/apps/main/models/user_profile.py
  kobo/apps/shadow_model/__init__.py
  kobo/settings/base.py
  kpi/constants.py
  kpi/deployment_backends/backends.py
  kpi/deployment_backends/kc_access/shadow_models.py
  kpi/deployment_backends/kc_access/utils.py
  kpi/deployment_backends/kobocat_backend.py
  kpi/deployment_backends/openrosa_backend.py
  kpi/management/commands/copy_kc_profile.py
  kpi/management/commands/sync_kobocat_xforms.py
  kpi/migrations/0011_explode_asset_deployments.py
  kpi/serializers/v2/service_usage.py
  kpi/tasks.py
  kpi/views/v2/data.py
Labels: Back end

#5041 Code refactoring: Remove RestService
  kobo/apps/hook/constants.py
  kobo/apps/hook/exceptions.py
  kobo/apps/hook/models/hook_log.py
  kobo/apps/hook/models/service_definition_interface.py
  kobo/apps/hook/tasks.py
  kobo/apps/hook/tests/hook_test_case.py
  kobo/apps/hook/tests/test_api_hook.py
  kobo/apps/hook/tests/test_email.py
  kobo/apps/hook/tests/test_ssrf.py
  kobo/apps/hook/tests/test_utils.py
  kobo/apps/hook/utils.py
  kobo/apps/hook/utils/__init__.py
  kobo/apps/hook/utils/lazy.py
  kobo/apps/hook/utils/services.py
  kobo/apps/hook/views/v1/__init__.py
  kobo/apps/hook/views/v1/hook_signal.py
  kobo/apps/hook/views/v2/__init__.py
  kobo/apps/hook/views/v2/hook.py
  kobo/apps/hook/views/v2/hook_log.py
  kobo/apps/hook/views/v2/hook_signal.py
  kobo/apps/openrosa/apps/api/tests/viewsets/test_xform_viewset.py
  kobo/apps/openrosa/apps/logger/migrations/0035_remove_xform_has_kpi_hooks_and_instance_posted_to_kpi.py
  kobo/apps/openrosa/apps/logger/models/instance.py
  kobo/apps/openrosa/apps/logger/models/xform.py
  kobo/apps/openrosa/apps/main/migrations/0015_drop_old_restservice_tables.py
  kobo/apps/openrosa/apps/restservice/RestServiceInterface.py
  kobo/apps/openrosa/apps/restservice/__init__.py
  kobo/apps/openrosa/apps/restservice/app.py
  kobo/apps/openrosa/apps/restservice/management/__init__.py
  kobo/apps/openrosa/apps/restservice/management/commands/__init__.py
  kobo/apps/openrosa/apps/restservice/management/commands/update_kpi_hooks_endpoint.py
  kobo/apps/openrosa/apps/restservice/migrations/0001_initial.py
  kobo/apps/openrosa/apps/restservice/migrations/0002_add_related_name_with_delete_on_cascade.py
  kobo/apps/openrosa/apps/restservice/migrations/0003_remove_deprecated_services.py
  kobo/apps/openrosa/apps/restservice/migrations/__init__.py
  kobo/apps/openrosa/apps/restservice/models.py
  kobo/apps/openrosa/apps/restservice/services/__init__.py
  kobo/apps/openrosa/apps/restservice/services/kpi_hook.py
  kobo/apps/openrosa/apps/restservice/signals.py
  kobo/apps/openrosa/apps/restservice/tasks.py
  kobo/apps/openrosa/apps/restservice/templates/add-service.html
  kobo/apps/openrosa/apps/restservice/tests/__init__.py
  kobo/apps/openrosa/apps/restservice/tests/fixtures/dhisform.xls
  kobo/apps/openrosa/apps/restservice/tests/test_restservice.py
  kobo/apps/openrosa/apps/restservice/utils.py
  kobo/apps/openrosa/apps/viewer/models/parsed_instance.py
  kobo/apps/openrosa/libs/constants.py
  kobo/apps/openrosa/libs/serializers/xform_serializer.py
  kobo/settings/base.py
  kpi/deployment_backends/base_backend.py
  kpi/deployment_backends/mock_backend.py
  kpi/deployment_backends/openrosa_backend.py
  kpi/signals.py
  kpi/tests/api/v2/test_api_invalid_password_access.py
  kpi/urls/router_api_v1.py
  kpi/urls/router_api_v2.py
Labels: Back end

#5064 Add created_by and last_modified_by fields to asset model
  kpi/management/commands/populate_asset_created_and_modified_by.py
  kpi/migrations/0058_add_created_by_and_last_modified_by_to_asset.py
  kpi/models/asset.py
  kpi/serializers/v2/asset.py
  kpi/tests/api/v2/test_api_assets.py
  kpi/views/v2/asset.py
Labels: Back end

#5067 Create new endpoints for viewing access logs
  kobo/apps/audit_log/filters.py
  kobo/apps/audit_log/models.py
  kobo/apps/audit_log/serializers.py
  kobo/apps/audit_log/tests/api/v2/test_api_audit_log.py
  kobo/apps/audit_log/urls.py
  kobo/apps/audit_log/views.py
Labels: API, Back end

#5012 Use Node 20, and add it to CI
  .github/workflows/npm-test.yml
  .github/workflows/pytest.yml
  .node-version
  .nvmrc
  Dockerfile
  package-lock.json
  package.json
  patches/mocha-chrome+2.2.0.patch
  scripts/hints.js
Labels: workflow, dependencies, Front end
