Repository kobotoolbox/kpi, pull requests merged in 2024-12, with the labels that each got.

#5295 ci: skip tests if unaffected TASK-1316
  .github/filters.yml
  .github/workflows/ci.yml
  .github/workflows/darker.yml
  .github/workflows/npm-test.yml
  .github/workflows/pytest.yml
Labels: workflow

#5258 feat(accessLogExport)!: create new AccessLogExportTask to generate a csv of access logs TASK-871
  jsapp/js/constants.ts
  kobo/apps/audit_log/models.py
  kobo/apps/audit_log/tests/test_project_history_logs.py
  kobo/apps/trash_bin/utils.py
  kpi/migrations/0060_rename_exporttask_submissionexporttask_and_more.py
  kpi/models/__init__.py
  kpi/models/import_export_task.py
  kpi/serializers/v1/export_task.py
  kpi/serializers/v2/export_task.py
  kpi/tasks.py
  kpi/tests/api/v1/test_api_assets.py
  kpi/tests/api/v1/test_api_exports.py
  kpi/tests/api/v2/test_api_exports.py
  kpi/tests/test_access_logs_export_task.py
  kpi/tests/test_mock_data_conflicting_version_exports.py
  kpi/tests/test_mock_data_exports.py
  kpi/utils/data_exports.py
  kpi/views/v1/export_task.py
  kpi/views/v2/asset_export_settings.py
  kpi/views/v2/export_task.py
Labels: Back end

#5296 feat(organizations): org role logic for usage page plan update button TASK-999
  jsapp/js/account/usage/yourPlan.component.tsx
Labels: Front end

#5297 feat(ProjectHistoryLogs): create ph logs for permissions changes TASK-944
  kobo/apps/audit_log/audit_actions.py
  kobo/apps/audit_log/models.py
  kobo/apps/audit_log/signals.py
  kobo/apps/audit_log/tests/test_models.py
  kobo/apps/audit_log/tests/test_project_history_logs.py
  kobo/apps/audit_log/tests/test_signals.py
  kpi/mixins/object_permission.py
  kpi/models/asset.py
  kpi/utils/object_permission.py
  kpi/views/v2/asset_permission_assignment.py
Labels: Back end

#5253 feat(organizations): add badge to profile dropdown TASK-979
  jsapp/js/components/common/badge.module.scss
  jsapp/js/components/common/badge.tsx
  jsapp/js/components/header/accountMenu.tsx
  jsapp/js/components/header/mainHeader.component.tsx
  jsapp/js/components/header/mainHeader.module.scss
  jsapp/js/components/header/organizationBadge.component.tsx
  jsapp/js/components/header/organizationBadge.module.scss
  jsapp/scss/components/_kobo.navigation.scss
Labels: Front end

#5302 feat(projectHistoryLogs): record logs for cloned permissions TASK-944
  kobo/apps/audit_log/audit_actions.py
  kobo/apps/audit_log/models.py
  kobo/apps/audit_log/tests/test_project_history_logs.py
  kpi/views/v2/asset_permission_assignment.py
Labels: Back end

#5314 feat(organization): restrict user management to organization form
  kobo/apps/organizations/admin/__init__.py
  kobo/apps/organizations/admin/organization.py
  kobo/apps/organizations/admin/organization_invite.py
  kobo/apps/organizations/admin/organization_user.py
  kobo/apps/organizations/models.py
Labels: Back end

#5317 Restrict email updates to organization owners and admins only
  kobo/apps/accounts/serializers.py
  kobo/apps/accounts/tests/test_email.py
Labels: Back end

#5313 feat(projectHistoryLogs): record logs for transfering ownership TASK-944
  kobo/apps/audit_log/audit_actions.py
  kobo/apps/audit_log/models.py
  kobo/apps/audit_log/tests/test_project_history_logs.py
  kobo/apps/project_ownership/views/invite.py
Labels: Back end

#5312 feat(organizations): add `owner_label` field to `AssetSerializer` TASK-1181
  kobo/apps/organizations/models.py
  kpi/serializers/v2/asset.py
  kpi/tests/api/v1/test_api_assets.py
  kpi/tests/api/v2/test_api_assets.py
  kpi/views/v2/asset.py
Labels: Back end

#5325 fix: use django storage to handle file objects
  kpi/tests/test_access_logs_export_task.py
Labels: bug-fix, Back end

#5304 feat(accessLogsExport): create new endpoints TASK-1147 
  kobo/apps/audit_log/tests/api/v2/test_api_audit_log.py
  kobo/apps/audit_log/urls.py
  kobo/apps/audit_log/views.py
  kpi/tests/test_export_tasks.py
Labels: Back end

#5324 perf(organization): reduce DB queries even further for owner label in asset list
  kobo/apps/organizations/views.py
  kpi/serializers/v2/asset.py
  kpi/views/v2/asset.py
Labels: Back end

#5280 feat(organizations): hide organization fields from settings for mmo organizations - TASK-978
  jsapp/js/account/accountSettingsRoute.tsx
Labels: Front end

#5318 feat(organizations): mutation hook for updating organization settings TASK-1219
  jsapp/js/account/accountFieldsEditor.component.tsx
  jsapp/js/account/organization/organizationQuery.ts
Labels: Front end

#5281 feat(organizations): add functions for managing members TASK-985
  jsapp/js/account/organization/membersQuery.ts
  jsapp/js/account/organization/organizationQuery.ts
  jsapp/js/api.endpoints.ts
Labels: Front end

#5327 feat(organizations): Use `owner_label` for asset ownership display TASK-1181
  jsapp/js/assetUtils.ts
  jsapp/js/components/assetsTable/assetsTableRow.tsx
  jsapp/js/components/formSummaryProjectInfo.tsx
  jsapp/js/components/library/assetInfoBox.tsx
  jsapp/js/components/submissions/tableUtils.mocks.ts
  jsapp/js/dataInterface.ts
  jsapp/js/projects/projectsTable/projectsTableRow.tsx
Labels: Front end

#5249 feat(organizations): update usage limits modals and banners TASK-996
  jsapp/js/components/usageLimits/limitNotifications.component.tsx
  jsapp/js/components/usageLimits/overLimitBanner.component.tsx
  jsapp/js/components/usageLimits/overLimitBanner.module.scss
  jsapp/js/components/usageLimits/overLimitModal.component.tsx
  jsapp/js/components/usageLimits/overLimitModal.module.scss
  jsapp/js/components/usageLimits/useExceedingLimits.hook.ts
  jsapp/js/projects/universalProjectsRoute.tsx
  package-lock.json
  package.json
Labels: Front end

#5320 fix(projectHistoryLogs): rename incorrectly-formatted action TASK-944
  kobo/apps/audit_log/audit_actions.py
  kobo/apps/audit_log/migrations/0013_alter_auditlog_action.py
  kobo/apps/audit_log/views.py
Labels: API, Back end

#5331 refactor(organization): make organizations endpoint more "RESTful"
  kobo/apps/organizations/serializers.py
Labels: Back end

#5328 feat(accessLogsExport): add export button TASK-860
  jsapp/js/account/security/accessLogs/accessLogs.query.ts
  jsapp/js/account/security/accessLogs/accessLogsSection.component.tsx
  jsapp/js/api.endpoints.ts
  jsapp/js/components/exportToEmailButton/exportToEmailButton.component.tsx
Labels: Front end

#5333 feat(organizations)!: Restrict project usage access to admins and organization owners
  kobo/apps/organizations/permissions.py
  kobo/apps/organizations/tests/test_organizations_api.py
  kobo/apps/organizations/views.py
  kobo/apps/stripe/tests/test_organization_usage.py
  kobo/apps/trackers/tests/submission_utils.py
  kobo/apps/trackers/utils.py
  kpi/filters.py
  kpi/serializers/v2/service_usage.py
  kpi/tests/test_usage_calculator.py
  kpi/utils/usage_calculator.py
  kpi/views/v2/service_usage.py
Labels: Back end

#5329 Expose organization user created timestamp in members endpoint
  kobo/apps/organizations/serializers.py
Labels: Back end

#5339 docs(projectHistoryLogs): show correct URL in endpoint documentation
  kobo/apps/audit_log/views.py
Labels: API, Back end

#5336 feat(organizations): add specific email template for project ownership transfer to organization TASK-1339
  kobo/apps/project_ownership/models/invite.py
  kobo/apps/project_ownership/templates/emails/new_invite_org.html
  kobo/apps/project_ownership/templates/emails/new_invite_org.txt
  kobo/apps/project_ownership/tests/test_mail.py
Labels: Back end

#5341 feat(organizations): make website optional
  kobo/apps/organizations/serializers.py
  kobo/apps/organizations/tests/test_organizations_api.py
  kpi/serializers/current_user.py
Labels: Back end

#5335 feat(organizations): transfer projects to organization owner when the recipient belongs to a MMO TASK-1338
  kobo/apps/organizations/utils.py
  kobo/apps/project_ownership/models/invite.py
  kobo/apps/project_ownership/models/transfer.py
  kobo/apps/project_ownership/templates/emails/new_invite_org.html
  kobo/apps/project_ownership/templates/emails/new_invite_org.txt
  kobo/apps/project_ownership/tests/api/v2/test_api.py
  kobo/apps/project_ownership/tests/test_mail.py
  kobo/apps/project_ownership/tests/test_permissions.py
  kpi/serializers/v2/asset.py
Labels: Back end

#5340 chore(projectHistoryLogs): organize and rename methods
  kobo/apps/audit_log/models.py
  kobo/apps/audit_log/signals.py
  kobo/apps/audit_log/tests/test_models.py
  kobo/apps/audit_log/tests/test_project_history_logs.py
  kobo/apps/hook/views/v2/hook.py
  kpi/constants.py
  kpi/views/v1/export_task.py
  kpi/views/v2/asset_file.py
  kpi/views/v2/asset_permission_assignment.py
  kpi/views/v2/export_task.py
  kpi/views/v2/paired_data.py
Labels: Back end

#5342 refactor(organization): Update database migration files with more accurate names
  kobo/apps/organizations/migrations/0007_update_organization_name_website_and_type.py
  kobo/apps/organizations/migrations/0008_alter_mmo_override_verbose_name.py
  kobo/apps/organizations/migrations/0009_update_db_state_with_auth_user.py
Labels: Back end

#5309 feat(MembersRoute): add actions dropdown to the table of organization members TASK-987 TASK-990
  jsapp/js/account/organization/MemberActionsDropdown.tsx
  jsapp/js/account/organization/MemberRemoveModal.tsx
  jsapp/js/account/organization/MembersRoute.tsx
  jsapp/js/account/organization/OrganizationSettingsRoute.tsx
  jsapp/js/account/organization/memberActionsDropdown.module.scss
Labels: Front end

#5315 feat(organizations): member role selector TASK-986
  jsapp/js/account/organization/MemberRoleSelector.tsx
  jsapp/js/account/organization/MembersRoute.tsx
Labels: Front end

#5338 feat(UniversalTable): column pinning improvements TASK-1312
  jsapp/js/hooks/useViewportSize.ts
  jsapp/js/hooks/useWindowEvent.ts
  jsapp/js/universalTable/universalTable.component.tsx
  jsapp/js/universalTable/universalTable.module.scss
  jsapp/js/universalTable/universalTable.stories.tsx
Labels: Front end

#5348 feat(MembersRoute): pin action column to right side TASK-987
  jsapp/js/account/organization/MembersRoute.tsx
Labels: Front end

#5343 feat(projectHistoryLogs): fetch data from API TASK-881 TASK-1156
  jsapp/js/account/organization/membersQuery.ts
  jsapp/js/account/security/accessLogs/accessLogs.query.ts
  jsapp/js/api.endpoints.ts
  jsapp/js/components/activity/activity.constants.ts
  jsapp/js/components/activity/activityLogs.query.ts
  jsapp/js/components/activity/formActivity.tsx
  jsapp/js/universalTable/paginatedQueryUniversalTable.component.tsx
Labels: Front end

#5347 feat(projectHistoryLogs): hide export button behind feature flag TASK-1359
  jsapp/js/components/activity/formActivity.tsx
  jsapp/js/featureFlags.ts
Labels: Front end

#5354 feat(projectHistoryLogs): add action label and review all action items and texts TASK-1371
  jsapp/js/components/activity/activity.constants.ts
  jsapp/js/components/activity/activityLogs.query.ts
  jsapp/js/components/activity/activityMessage.component.tsx
  jsapp/js/components/activity/formActivity.module.scss
Labels: Front end

#5355 docs(projectHistoryLogs): correct PH log API docs
  kobo/apps/audit_log/views.py
Labels: API, Back end

#5359 docs: fix audit log endoint documentation typos
  kobo/apps/audit_log/views.py
Labels: API, Back end, documentation

#5352 fix: remove plan dropdown cropping in addons view TASK-1361
  jsapp/js/account/plans/plan.module.scss
Labels: Front end

#5351 fix(permissions): restore edit functionality for users with partial permissions TASK-1366
  kpi/deployment_backends/openrosa_backend.py
  kpi/tests/api/v1/test_api_submissions.py
  kpi/tests/api/v2/test_api_submissions.py
  kpi/tests/test_deployment_backends.py
  kpi/views/v2/asset_snapshot.py
Labels: bug-fix, Back end

#5361 feat(projectHistoryLogs): Sort filter options TASK-1381
  jsapp/js/components/activity/activity.constants.ts
  jsapp/js/components/activity/activityLogs.query.ts
Labels: Front end

#5334 fix(sso): 500 on admin login
  dependencies/pip/dev_requirements.txt
  dependencies/pip/requirements.txt
  kobo/apps/accounts/tests/test_backend.py
Labels: Back end

#5353 feat(organizations): implement `search_field` for asset filtering TASK-1334
  kobo/apps/organizations/apps.py
  kobo/apps/organizations/signals.py
  kobo/apps/organizations/tests/test_organizations_api.py
  kobo/apps/project_ownership/models/transfer.py
  kpi/migrations/0061_add_search_field_to_asset.py
  kpi/models/asset.py
  kpi/tests/test_assets.py
Labels: Back end

#5365 fix(projectOwnershipTransfer): ensure OpenRosa media files are synchronized when transferring project ownership TASK-1352
  kobo/apps/project_ownership/constants.py
  kobo/apps/project_ownership/utils.py
Labels: Back end

#5369 chore(Storybook): fix stories sorting (abc)
  .storybook/preview.js
Labels: Front end

#5367 fix(billing): check default plan limits on backend TASK-1364
  kobo/apps/stripe/tests/test_organization_usage.py
  kobo/apps/stripe/tests/utils.py
  kobo/apps/stripe/utils.py
Labels: Back end

#5368 refactor(projectHistoryLogs): use audit log base class for DataViewSet TASK-1340
  kpi/views/v2/data.py
Labels: Back end

#5378 fix(organizations): limit my org projects query to surveys TASK-1389
  jsapp/js/projects/myOrgProjectsRoute.tsx
Labels: Front end

#5311 ci(darker): improve comparison refs for focused errors
  .github/workflows/darker.yml
Labels: workflow, Back end

#5385 fix(projectOwnershipTransfer): ensure the path of OpenRosa media files is correct for transferred projects TASK-1352
  kobo/apps/long_running_migrations/jobs/0002_fix_project_ownership_transfer_with_media_files.py
  kobo/apps/long_running_migrations/migrations/0002_fix_failed_project_ownership_transfer_with_media_files.py
Labels: bug-fix, Back end

#5379 feat(migrations): introduce long-running migration system using Celery
  dependencies/pip/dev_requirements.in
  dependencies/pip/dev_requirements.txt
  kobo/apps/long_running_migrations/README.md
  kobo/apps/long_running_migrations/__init__.py
  kobo/apps/long_running_migrations/admin.py
  kobo/apps/long_running_migrations/jobs/0001_sample.py
  kobo/apps/long_running_migrations/jobs/0002_fix_project_ownership_transfer_with_media_files.py
  kobo/apps/long_running_migrations/jobs/__init__.py
  kobo/apps/long_running_migrations/migrations/0001_initial.py
  kobo/apps/long_running_migrations/migrations/0002_fix_failed_project_ownership_transfer_with_media_files.py
  kobo/apps/long_running_migrations/migrations/__init__.py
  kobo/apps/long_running_migrations/models.py
  kobo/apps/long_running_migrations/tasks.py
  kobo/apps/long_running_migrations/tests/__init__.py
  kobo/apps/long_running_migrations/tests/fixtures/__init__.py
  kobo/apps/long_running_migrations/tests/fixtures/sample_failure.py
  kobo/apps/long_running_migrations/tests/fixtures/sample_task.py
  kobo/apps/long_running_migrations/tests/test_case.py
  kobo/settings/base.py
  kpi/models/abstract_models.py
  kpi/tasks.py
Labels: Back end

#5386 fix(celery): correct crontab syntax for Celery Beat scheduler
  kobo/settings/base.py
Labels: bug-fix, Back end

#5364 feat(projectHistoryLogs): remove activity logs feature flag TASK-1385
  jsapp/js/components/formViewSideTabs.es6
  jsapp/js/featureFlags.ts
Labels: Front end

#5384 fix(organizations): restrict my organization projects to admins/owners TASK-1393
  jsapp/js/projects/projectViews/viewSwitcher.tsx
  jsapp/js/projects/routes.tsx
Labels: Front end

#5337 fix(NLP): NLP features broken on non-Stripe instances TASK-1322
  kobo/apps/subsequences/integrations/google/base.py
  kobo/apps/subsequences/tests/test_submission_extras_api_post.py
  kobo/apps/trackers/tests/test_utils.py
  kobo/apps/trackers/utils.py
  kpi/utils/usage_calculator.py
Labels: Back end

#5388 fix(organization): expose `owner_label` in ProjectView endpoint response TASK-1384
  kobo/apps/project_views/views.py
  kpi/mixins/asset.py
  kpi/serializers/v2/asset.py
  kpi/views/v2/asset.py
Labels: Back end

#5389 feat(migration): implement long-running migration for members' data transfer to organization TASK-1332
  kobo/apps/long_running_migrations/jobs/0003_transfer_members_data_ownership_to_org.py
  kobo/apps/long_running_migrations/migrations/0003_transfer_members_data_ownership_to_org.py
  kobo/settings/base.py
Labels: Back end

#5394 refactor(organization): Improve Django admin user-flow for long-running migrations and project ownership transfer
  kobo/apps/long_running_migrations/admin.py
  kobo/apps/long_running_migrations/app.py
  kobo/apps/long_running_migrations/models.py
  kobo/apps/project_ownership/__init__.py
  kobo/apps/project_ownership/admin.py
  kobo/apps/project_ownership/app.py
  kobo/apps/project_ownership/models/invite.py
  kobo/apps/project_ownership/static/admin/css/transfers_as_inline.css
  kobo/settings/base.py
Labels: Back end

#5358 feat(organizations): disable sorting for owner on projects table TASK-1336
  jsapp/js/projects/projectViews/constants.ts
Labels: Front end

#5382 feat(organizations): display org name for project owner in sharing form TASK-1383
  jsapp/js/components/permissions/sharingForm.component.tsx
Labels: Front end

#5383 feat(auditLogs): add endpoint for retrieving actions TASK-1365
  kobo/apps/audit_log/tests/api/v2/test_api_audit_log.py
  kobo/apps/audit_log/views.py
Labels: API, Back end

#5387 feat(projectHistoryLogs): log duplicated submissions TASK-1342
  kobo/apps/audit_log/audit_actions.py
  kobo/apps/audit_log/migrations/0014_add_submission_action.py
  kobo/apps/audit_log/models.py
  kobo/apps/audit_log/tests/test_project_history_logs.py
  kobo/apps/audit_log/views.py
  kpi/views/v2/data.py
Labels: Back end

#5390 fix: increase `FileField` maximum length to 380 characters
  kobo/apps/markdownx_uploader/migrations/0003_increase_content_max_length.py
  kobo/apps/markdownx_uploader/models.py
  kobo/apps/openrosa/apps/logger/migrations/0040_increase_file_fields_max_length.py
  kobo/apps/openrosa/apps/logger/models/xform.py
  kobo/apps/openrosa/apps/main/migrations/0018_increase_metadata_data_file_max_length.py
  kobo/apps/openrosa/apps/main/models/meta_data.py
  kpi/tasks.py
Labels: Back end

#5362 feat(organizations): update owner filtering on projects table TASK-1335
  jsapp/js/projects/projectViews/constants.ts
  jsapp/js/projects/projectViews/utils.tests.ts
  jsapp/js/projects/projectViews/utils.ts
Labels: Front end

#5392 feat(organizations): remove mmos feature flag TASK-1397
  jsapp/js/account/accountSidebar.tsx
  jsapp/js/account/organization/organizationQuery.ts
  jsapp/js/account/routes.tsx
  jsapp/js/account/usage/yourPlan.component.tsx
  jsapp/js/featureFlags.ts
Labels: Front end

#5399 fix: update type select after fetching default export settings TASK-1296
  jsapp/js/components/projectDownloads/projectExportsCreator.es6
Labels: Front end

#5396 fix(projectHistoryLogs): wrong error message
  jsapp/js/components/activity/activityLogs.query.ts
Labels: Front end

#5401 feat(projectHistoryLogs): fetch filter options from backend TASK-1403
  jsapp/js/api.endpoints.ts
  jsapp/js/components/activity/activityLogs.query.ts
  jsapp/js/components/activity/formActivity.tsx
Labels: Front end
