Repository kobotoolbox/kpi, pull requests merged in 2024-07, with the labels that each got.

#4988 Refactor `constance` setting assignments in tests to use `override_config`
  hub/tests/test_admin_validators.py
  kobo/apps/accounts/tests/test_current_user.py
Labels: Back end

#4992 Upgrade to React 18
  .swcrc
  jsapp/js/account/organizations/requireOrgOwner.component.tsx
  jsapp/js/account/plans/billingButton.component.tsx
  jsapp/js/account/plans/plan.component.tsx
  jsapp/js/account/security/email/emailSection.component.tsx
  jsapp/js/account/usage/usageContainer.tsx
  jsapp/js/components/assetsTable/assetActionButtons.tsx
  jsapp/js/components/common/tooltip.tsx
  jsapp/js/components/reports/reportTable.component.tsx
  jsapp/js/components/submissions/submissionUtils.tests.es6
  jsapp/js/components/submissions/table.tsx
  jsapp/js/main.es6
  jsapp/js/router/requireAuth.tsx
  package-lock.json
  package.json
  tsconfig.json
  webpack/webpack.common.js
Labels: dependencies, Front end

#4994 [TASK-461] Add modal(s) to NLP page when user is over limits
  jsapp/js/account/stripe.types.ts
  jsapp/js/account/usage/usage.component.tsx
  jsapp/js/account/usage/usageProjectBreakdown.tsx
  jsapp/js/account/usage/useUsage.hook.ts
  jsapp/js/components/processing/nlpUsageLimitBlockModal/nlpUsageLimitBlockModal.component.tsx
  jsapp/js/components/processing/nlpUsageLimitBlockModal/nlpUsageLimitBlockModal.module.scss
  jsapp/js/components/processing/transcript/stepConfig.component.tsx
  jsapp/js/components/processing/transcript/transcript.utils.ts
  jsapp/js/components/processing/translations/stepConfig.component.tsx
  jsapp/js/components/usageLimits/useExceedingLimits.hook.ts
  jsapp/js/utils.ts
Labels: Front end

#4998 Fix corrupted large ZIP files with AWS S3 storage
  kobo/apps/storage_backends/s3boto3.py
Labels: bug-fix, Back end

#4975 Add `provision_server` management command
  kpi/management/commands/provision_server.py
  kpi/tests/test_provision_server.py
Labels: Back end

#5003 [TASK-806] Duplicating submissions doesn’t copy extra submission details
  kpi/deployment_backends/base_backend.py
  kpi/tests/api/v2/test_api_submissions.py
  kpi/views/v2/data.py
Labels: Back end

#5002 [TASK-880] Fix 500 error when filtering fields with data endpoint
  kpi/tests/test_mock_data_exports.py
  kpi/utils/mongo_helper.py
Labels: API, bug-fix, Back end

#4989 Reject 2FA activation with API when option is disabled for that account #4556
  kobo/apps/accounts/adapter.py
  kobo/apps/accounts/mfa/permissions.py
  kobo/apps/accounts/mfa/tests/test_api.py
  kobo/apps/accounts/mfa/urls.py
  kobo/apps/accounts/mfa/views.py
  kobo/apps/accounts/utils.py
  kobo/apps/stripe/tests/test_mfa_login.py
Labels: API, Back end

#5009 [TASK-892] Fix Submission Modal pagination
  jsapp/js/components/bigModal/bigModal.es6
  jsapp/js/components/common/koboDropdown.tsx
  jsapp/js/components/common/koboSelect.scss
  jsapp/js/components/modals/koboModal.tsx
  jsapp/js/components/submissions/submissionDataTable.scss
  jsapp/js/components/submissions/submissionDataTable.tsx
  jsapp/js/components/submissions/submissionModal.scss
  jsapp/js/components/submissions/submissionModal.tsx
  jsapp/js/components/submissions/table.tsx
  jsapp/js/components/submissions/table.types.ts
  jsapp/js/pageState.store.ts
Labels: Front end

#5000 Update ESLint config to accept separate type imports in TS again
  .eslintrc.js
  package-lock.json
  package.json
Labels: workflow, dependencies, Front end

#5008 Fix project view table timeout
  kobo/apps/project_views/views.py
  kpi/paginators.py
Labels: Back end

#4997 Remove legacy contextTypes
  .eslintrc.js
  jsapp/js/app.jsx
  jsapp/js/components/RESTServices/RESTServiceLogs.es6
  jsapp/js/components/drawer.es6
  jsapp/js/components/formEditors.js
  jsapp/js/components/formLanding.js
  jsapp/js/components/formSubScreens.js
  jsapp/js/components/formViewSideTabs.es6
  jsapp/js/components/modalForms/libraryAssetForm.es6
  jsapp/js/components/modalForms/libraryNewItemForm.es6
  jsapp/js/components/modalForms/projectSettings.es6
  jsapp/js/formbuild/renderInBackbone.es6
  jsapp/js/libs/reactBemComponents.tsx
  jsapp/js/lists/sidebarForms.es6
  package-lock.json
  package.json
Labels: dependencies, Front end

#5011 Remove redundant filter in Project View table
  jsapp/js/projects/customViewRoute.tsx
  jsapp/js/projects/customViewStore.tests.ts
  jsapp/js/projects/customViewStore.ts
  test/index.js
Labels: Front end

#5022 Fix header logo
  jsapp/scss/components/_kobo.navigation.scss
Labels: bug-fix, Front end

#5023 Fix "Could not get data for your organization" when browsing as an anonymous user.
  jsapp/js/account/billingContextProvider.component.tsx
Labels: bug-fix, Front end

#5018 Small UI improvements
  jsapp/js/account/accountSettings.scss
  jsapp/js/account/accountSettingsRoute.tsx
  jsapp/js/components/common/inlineMessage.scss
  jsapp/js/components/common/inlineMessage.tsx
  jsapp/js/components/permissions/transferProjects/transferProjects.component.tsx
  jsapp/js/components/permissions/transferProjects/transferProjects.module.scss
  jsapp/js/projects/projectsTable/projectBulkActions.tsx
  jsapp/js/projects/projectsTable/projectQuickActions.tsx
  jsapp/js/projects/projectsTable/projectQuickActionsEmpty.tsx
Labels: Front end

#5020 [TASK-823] Create an abstract model which provides `date_created` and `date_modified` fields
  kobo/apps/accounts/mfa/migrations/0004_alter_mfamethod_date_created_and_more.py
  kobo/apps/accounts/mfa/models.py
  kobo/apps/hook/migrations/0008_alter_hooklog_date_created_and_more.py
  kobo/apps/hook/models/hook.py
  kobo/apps/hook/models/hook_log.py
  kobo/apps/openrosa/apps/logger/migrations/0035_alter_instance_date_created_and_more.py
  kobo/apps/openrosa/apps/logger/models/instance.py
  kobo/apps/openrosa/apps/logger/models/note.py
  kobo/apps/openrosa/apps/logger/models/xform.py
  kobo/apps/openrosa/apps/main/migrations/0015_alter_metadata_data_file_alter_metadata_date_created_and_more.py
  kobo/apps/openrosa/apps/main/models/meta_data.py
  kobo/apps/openrosa/apps/viewer/migrations/0005_alter_instancemodification_date_created_and_more.py
  kobo/apps/openrosa/apps/viewer/models/instance_modification.py
  kobo/apps/openrosa/libs/data/tests/test_tools.py
  kobo/apps/project_ownership/migrations/0002_alter_invite_date_created_alter_invite_date_modified_and_more.py
  kobo/apps/project_ownership/models/invite.py
  kobo/apps/project_ownership/models/transfer.py
  kobo/apps/subsequences/migrations/0003_alter_submissionextras_date_created_and_more.py
  kobo/apps/subsequences/models.py
  kobo/apps/trash_bin/migrations/0003_alter_accounttrash_date_created_and_more.py
  kobo/apps/trash_bin/models/__init__.py
  kpi/migrations/0057_assetexportsettings_date_created_and_more.py
  kpi/models/abstract_models.py
  kpi/models/asset.py
  kpi/models/asset_export_settings.py
  kpi/models/asset_file.py
  kpi/models/asset_user_partial_permission.py
  kpi/models/asset_version.py
Labels: Back end

#5026 Add UI support for Yoruba translations
  kobo/settings/base.py
  kobo/static_lists.py
Labels: translations, Back end

#5031 [TASK-856] Improve XML parsing with defusedxml
  kobo/apps/hook/tests/test_parser.py
  kpi/exceptions.py
  kpi/tests/api/v1/test_api_assets.py
  kpi/tests/api/v2/test_api_submissions.py
  kpi/tests/utils/mock.py
  kpi/tests/utils/xml.py
  kpi/utils/sluggify.py
  kpi/utils/xml.py
Labels: Back end

#5019 Fix session authentication bug which blocks media and legacy exports
  kobo/apps/accounts/adapter.py
  kobo/apps/accounts/tests/constants.py
  kobo/apps/accounts/tests/test_backend.py
  kobo/apps/accounts/tests/test_templatetags.py
Labels: high priority, bug-fix, Back end

#5029 Fix bug blocking qualitative analysis feature with "unhashable type dict" error
  kobo/apps/subsequences/tests/test_submission_stream.py
  kobo/apps/subsequences/utils/__init__.py
Labels: bug-fix, Back end

#5030 Fix bug affecting project deletion permissions in the project list table
  jsapp/js/projects/projectsTable/projectQuickActions.tsx
Labels: bug-fix, Front end

#5039 Format backend code in `kpi/views/v2/data.py`
  kpi/views/v2/data.py
Labels: Back end
