Repository kobotoolbox/kpi, pull requests merged in 2024-10, with the labels that each got.

#5135 Fix project transfer failure in some circumstances
  kobo/apps/openrosa/apps/logger/models/attachment.py
  kobo/apps/project_ownership/exceptions.py
  kobo/apps/project_ownership/management/__init__.py
  kobo/apps/project_ownership/management/commands/__init__.py
  kobo/apps/project_ownership/management/commands/resume_failed_transfers_2_024_25_fix.py
  kobo/apps/project_ownership/models/transfer.py
  kobo/apps/project_ownership/tasks.py
  kobo/apps/project_ownership/tests/api/v2/test_api.py
  kobo/apps/project_ownership/tests/test_transfer_status.py
  kpi/tests/utils/transaction.py
Labels: CRITICAL, bug-fix, Back end

#5086 Service usage cache and submissions suspended flag
  kobo/apps/openrosa/apps/api/tests/viewsets/test_xform_submission_api.py
  kobo/apps/openrosa/apps/logger/management/commands/populate_submission_counters.py
  kobo/apps/openrosa/apps/logger/management/commands/update_attachment_storage_bytes.py
  kobo/apps/openrosa/apps/logger/migrations/0029_populate_daily_xform_counters_for_year.py
  kobo/apps/openrosa/apps/logger/migrations/0030_backfill_lost_monthly_counters.py
  kobo/apps/openrosa/apps/logger/migrations/0031_remove_null_user_daily_counters.py
  kobo/apps/openrosa/apps/logger/migrations/0032_alter_daily_submission_counter_user.py
  kobo/apps/openrosa/apps/logger/migrations/0038_populate_counters.py
  kobo/apps/openrosa/apps/logger/models/instance.py
  kobo/apps/openrosa/apps/main/migrations/0017_userprofile_submissions_suspended.py
  kobo/apps/openrosa/apps/main/models/user_profile.py
  kobo/apps/organizations/migrations/0005_add_cached_usage_data.py
  kobo/apps/organizations/migrations/0006_auto_20240412_2049.py
  kobo/apps/organizations/migrations/0007_auto_20240415_1659.py
  kobo/apps/organizations/models.py
  kobo/apps/organizations/tests/test_organizations_api.py
  kobo/apps/organizations/utils.py
  kobo/apps/organizations/views.py
  kobo/apps/project_ownership/tests/api/v2/test_api.py
  kpi/deployment_backends/openrosa_backend.py
  kpi/serializers/v2/service_usage.py
  kpi/tests/api/v2/test_api_service_usage.py
  kpi/tests/test_cache_utils.py
  kpi/tests/test_usage_calculator.py
  kpi/utils/cache.py
  kpi/utils/usage_calculator.py
Labels: Back end

#5113 Group submission access logs
  kobo/apps/audit_log/models.py
  kobo/apps/audit_log/serializers.py
  kobo/apps/audit_log/tests/api/v2/test_api_audit_log.py
  kobo/apps/audit_log/tests/test_models.py
  kobo/apps/audit_log/tests/test_one_time_auth.py
  kobo/apps/audit_log/views.py
  kobo/apps/openrosa/apps/api/viewsets/xform_submission_api.py
  kpi/constants.py
  kpi/fields/relative_prefix_hyperlinked_related.py
Labels: API, Back end

#5141 [TASK-1105] DiffValue component for displaying value change
  jsapp/js/components/common/diffValue.component.tsx
  jsapp/js/components/common/diffValue.module.scss
  jsapp/js/components/common/diffValue.stories.tsx
Labels: Front end

#5075 Code refactoring: Improve error message when XForm does not exist
  kpi/deployment_backends/openrosa_backend.py
  kpi/exceptions.py
Labels: Back end

#5078 Code refactoring: Better error handling in new deployment back-end class
  kobo/apps/hook/tests/hook_test_case.py
  kobo/apps/openrosa/apps/api/tests/viewsets/test_xform_submission_api.py
  kobo/apps/openrosa/apps/api/viewsets/data_viewset.py
  kobo/apps/openrosa/apps/main/migrations/0015_drop_old_restservice_tables.py
  kobo/apps/openrosa/libs/utils/logger_tools.py
  kobo/apps/trash_bin/utils.py
  kpi/deployment_backends/base_backend.py
  kpi/deployment_backends/mock_backend.py
  kpi/deployment_backends/openrosa_backend.py
  kpi/models/asset.py
  kpi/views/v2/asset_snapshot.py
  kpi/views/v2/data.py
Labels: Back end

#5101 Fix automatic data refresh of remote source
  kobo/apps/openrosa/apps/logger/models/attachment.py
  kobo/apps/openrosa/apps/logger/models/xform.py
  kobo/apps/openrosa/apps/main/models/meta_data.py
  kobo/apps/openrosa/apps/main/tests/test_process.py
  kobo/apps/openrosa/libs/serializers/xform_serializer.py
  kobo/apps/openrosa/libs/utils/gravatar.py
  kobo/apps/openrosa/libs/utils/hash.py
  kobo/apps/openrosa/libs/utils/logger_tools.py
  kobo/settings/base.py
  kobo/settings/dev.py
  kpi/utils/hash.py
Labels: bug-fix, Back end

#5134 Record project history logs for deployment changes
  kobo/apps/audit_log/migrations/0011_projecthistorylog.py
  kobo/apps/audit_log/models.py
  kobo/apps/audit_log/tests/test_models.py
  kpi/constants.py
  kpi/tests/api/v2/test_api_assets.py
  kpi/views/v2/asset.py
Labels: Back end

#5109 [TASK-857] Add Access Log section to security route
  jsapp/js/account/security/accessLogs/accessLogsSection.component.tsx
  jsapp/js/account/security/apiToken/apiTokenSection.component.tsx
  jsapp/js/account/security/apiToken/apiTokenSection.module.scss
  jsapp/js/account/security/email/emailSection.component.tsx
  jsapp/js/account/security/email/emailSection.module.scss
  jsapp/js/account/security/mfa/mfaSection.component.tsx
  jsapp/js/account/security/mfa/mfaSection.module.scss
  jsapp/js/account/security/mfa/mfaSection.scss
  jsapp/js/account/security/password/passwordSection.component.tsx
  jsapp/js/account/security/password/passwordSection.module.scss
  jsapp/js/account/security/securityRoute.component.tsx
  jsapp/js/account/security/securityRoute.module.scss
  jsapp/js/account/security/sso/ssoSection.component.tsx
  jsapp/js/account/security/sso/ssoSection.module.scss
  jsapp/js/actions/mfaActions.ts
  jsapp/js/api.endpoints.ts
  jsapp/js/query/queries/accessLogs.query.ts
  jsapp/js/stores/session.ts
  jsapp/js/universalTable/universalTable.component.tsx
Labels: Front end

#5157 Group submission access logs
  kobo/apps/audit_log/models.py
  kobo/apps/audit_log/serializers.py
  kobo/apps/audit_log/tests/api/v2/test_api_audit_log.py
  kobo/apps/audit_log/tests/test_models.py
  kobo/apps/audit_log/tests/test_one_time_auth.py
  kobo/apps/audit_log/views.py
  kobo/apps/openrosa/apps/api/viewsets/xform_submission_api.py
  kpi/constants.py
  kpi/fields/relative_prefix_hyperlinked_related.py
Labels: Back end

#5158 Use @deprecated JSDoc tag
  jsapp/js/bem.ts
  jsapp/js/components/assetsTable/assetsTable.tsx
  jsapp/js/components/common/modal.tsx
  jsapp/js/global.d.ts
  jsapp/js/mixins.tsx
  jsapp/js/router/legacy.tsx
  jsapp/js/utils.ts
Labels: Front end, documentation

#5116 [TASK-1059] Handle submission groups in Access Log UI
  jsapp/js/account/security/accessLogs/accessLogsSection.component.tsx
  jsapp/js/projects/projectViews/viewSwitcher.module.scss
  jsapp/js/query/queries/accessLogs.query.ts
  jsapp/js/universalTable/paginatedQueryUniversalTable.component.tsx
  jsapp/js/universalTable/universalTable.component.tsx
Labels: blocked, Front end

#5144 [TASK-1113] Fix createsuperuser not creating a valid email address
  kobo/apps/kobo_auth/management/commands/createsuperuser.py
  kobo/apps/kobo_auth/tests.py
Labels: Back end

#5143 Improve audit log endpoint documentation
  kobo/apps/audit_log/tests/test_one_time_auth.py
  kobo/apps/audit_log/views.py
Labels: Back end

#5155 Add non-recursive ownership reset for media directory to improve KPI startup performance
  Dockerfile
  docker/entrypoint.sh
Labels: Back end

#5142 Reduce number of DB queries while transferring a project to another user
  kobo/apps/project_ownership/constants.py
  kobo/apps/project_ownership/management/commands/resume_failed_transfers_2_024_25_fix.py
  kobo/apps/project_ownership/utils.py
Labels: Back end

#5165 Fix stuck legacy exports issue introduced in `2.024.25`
  kobo/apps/openrosa/apps/api/mongo_helper.py
  kobo/apps/openrosa/apps/viewer/models/data_dictionary.py
  kobo/apps/openrosa/apps/viewer/models/parsed_instance.py
  kobo/apps/openrosa/apps/viewer/tests/test_export_builder.py
  kobo/apps/openrosa/libs/serializers/data_serializer.py
  kobo/apps/openrosa/libs/utils/export_tools.py
  kobo/apps/openrosa/libs/utils/logger_tools.py
  kobo/settings/base.py
  kpi/utils/mongo_helper.py
Labels: Back end

#5090 Improve legibility of registration links #5089 [TASK-1058]
  jsapp/scss/stylesheets/partials/_registration.scss
  kobo/apps/accounts/templates/account/login.html
  kobo/apps/accounts/templates/account/signup.html
  kobo/apps/accounts/templates/legal/registration_legal.html
  kobo/apps/accounts/templates/socialaccount/login.html
  kobo/apps/accounts/templates/socialaccount/signup.html
  kpi/templates/base.html
Labels: UI & UX, Front end

#5168 [TASK-1154] Update Avatar component
  jsapp/js/account/accountSettings.scss
  jsapp/js/account/accountSettingsRoute.tsx
  jsapp/js/account/changePasswordRoute.component.tsx
  jsapp/js/bemComponents.ts
  jsapp/js/components/common/avatar.module.scss
  jsapp/js/components/common/avatar.stories.tsx
  jsapp/js/components/common/avatar.tsx
  jsapp/js/components/formSummary.js
  jsapp/js/components/formSummary.scss
  jsapp/js/components/formSummaryProjectInfo.tsx
  jsapp/js/components/header/accountMenu.tsx
  jsapp/js/components/permissions/sharingForm.scss
  jsapp/js/components/permissions/userPermissionRow.component.tsx
  jsapp/js/projects/projectsTable/projectsTableRow.tsx
  jsapp/js/utils.ts
  jsapp/scss/components/_kobo.navigation.scss
Labels: Front end

#5172 [TASK-1164] Fix function that renders language in the downloads table
  jsapp/js/components/projectDownloads/projectExportsList.es6
Labels: bug-fix, Front end

#5166 Patch AlertifyJS to avoid errors during dialog transitions
  package-lock.json
  package.json
  patches/alertifyjs+1.14.0.patch
Labels: Front end

#5160 Drop support for Python 3.8
  .github/workflows/pytest.yml
  dependencies/pip/dev_requirements.in
  dependencies/pip/dev_requirements.txt
  kpi/utils/xml.py
Labels: Back end

#5175 [TASK-1155] Add spinner to UniversalTable
  jsapp/js/universalTable/paginatedQueryUniversalTable.component.tsx
  jsapp/js/universalTable/universalTable.component.tsx
  jsapp/js/universalTable/universalTable.module.scss
Labels: enhancement, Front end

#5174 [TASK-1165] Fix project header title serving old asset name
  jsapp/js/components/header/headerTitleEditor.tsx
Labels: bug-fix, Front end

#5159 [TASK-1108] Reset checkboxes in Projects Table after loading fresh results
  jsapp/js/projects/customViewRoute.tsx
  jsapp/js/projects/myProjectsRoute.tsx
  jsapp/js/projects/projectsTable/projectQuickActions.tsx
Labels: Front end

#5176 [TASK-1168] Implement feature flags functionality
  jsapp/js/components/formViewSideTabs.es6
  jsapp/js/featureFlags.ts
Labels: Front end

#5146 Fe project history logs
  jsapp/js/components/activity/formActivity.module.scss
  jsapp/js/components/activity/formActivity.tsx
  jsapp/js/components/formSubScreens.js
  jsapp/js/components/formViewSideTabs.es6
  jsapp/js/featureFlags.ts
  jsapp/js/query/queries/accessLogs.query.ts
  jsapp/js/query/queries/activityLogs.query.ts
  jsapp/js/query/queryKeys.ts
  jsapp/js/router/router.tsx
  jsapp/js/router/routerConstants.ts
Labels: Front end

#5177 [TASK-1078] Directly Access Organization Owners for Improved Performance
  kobo/apps/organizations/models.py
  kobo/apps/subsequences/tests/test_proj_advanced_features.py
  kpi/tests/test_organization.py
Labels: Back end

#5097 Delete expired access logs
  dependencies/pip/dev_requirements.txt
  dependencies/pip/requirements.in
  dependencies/pip/requirements.txt
  kobo/apps/audit_log/tasks.py
  kobo/apps/audit_log/tests/test_tasks.py
  kobo/settings/base.py
Labels: Back end

#5190 Change access log endpoints
  kobo/apps/audit_log/urls.py
  kobo/apps/audit_log/views.py
Labels: API, Back end

#5192 Apply Formatting and Linting to Python Codebase
  kobo/apps/openrosa/apps/logger/models/xform.py
Labels: Back end

#5178 [TASK-1076] Improve Role Access for Users in Organizations with Direct Properties
  kobo/apps/accounts/forms.py
  kobo/apps/kobo_auth/models.py
  kobo/apps/organizations/constants.py
  kobo/apps/organizations/models.py
  kpi/password_validation.py
  kpi/tests/test_organization.py
  kpi/tests/test_passwords.py
  kpi/tests/test_user.py
Labels: Back end

#5188 Refactor deployment project history logs
  kobo/apps/accounts/tests/test_backend.py
  kobo/apps/audit_log/audit_actions.py
  kobo/apps/audit_log/base_views.py
  kobo/apps/audit_log/middleware.py
  kobo/apps/audit_log/migrations/0012_alter_auditlog_action.py
  kobo/apps/audit_log/models.py
  kobo/apps/audit_log/tests/api/v2/test_api_audit_log.py
  kobo/apps/audit_log/tests/test_base_views.py
  kobo/apps/audit_log/tests/test_models.py
  kobo/apps/audit_log/tests/test_one_time_auth.py
  kobo/apps/audit_log/tests/test_project_history_logs.py
  kobo/apps/audit_log/tests/test_signals.py
  kobo/apps/trash_bin/tasks.py
  kobo/apps/trash_bin/tests/test_utils.py
  kobo/apps/trash_bin/utils.py
  kobo/settings/base.py
  kpi/fixtures/asset_with_settings_and_qa.json
  kpi/tests/api/v2/test_api_assets.py
  kpi/views/v2/asset.py
  kpi/views/v2/data.py
Labels: Back end

#5183 [TASK-1082] Add `mmo_override` field to Organization model with admin control
  kobo/apps/organizations/migrations/0005_add_mmo_override_field_to_organization.py
  kobo/apps/organizations/models.py
Labels: Back end

#5182 [TASK-1167] Expose Team or Organization wording to front end
  kobo/settings/base.py
  kpi/tests/api/test_api_environment.py
  kpi/views/environment.py
Labels: Back end

#5198 Add reminder for adding PR tags to template checklist
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Front end

#5131 NLP usage tracking and limits based on subscription plan and one time add ons
  kobo/apps/organizations/models.py
  kobo/apps/organizations/tests/test_organizations_model.py
  kobo/apps/organizations/types.py
  kobo/apps/stripe/constants.py
  kobo/apps/stripe/models.py
  kobo/apps/stripe/tests/test_one_time_addons_api.py
  kobo/apps/stripe/tests/test_organization_usage.py
  kobo/apps/stripe/utils.py
  kobo/apps/subsequences/integrations/google/google_transcribe.py
  kobo/apps/subsequences/tests/test_submission_extras_api_post.py
  kobo/apps/trackers/tests/test_utils.py
  kobo/apps/trackers/utils.py
  kpi/tests/test_usage_calculator.py
  kpi/utils/cache.py
  kpi/utils/django_orm_helper.py
  kpi/utils/usage_calculator.py
Labels: Back end

#5200 [TASK-1196] Enhance `/me` and Organization detail endpoints with additional properties
  hub/models/extra_user_detail.py
  kobo/apps/kobo_auth/models.py
  kobo/apps/kobo_auth/signals.py
  kobo/apps/organizations/migrations/0006_update_organization_name.py
  kobo/apps/organizations/serializers.py
  kobo/apps/organizations/tests/test_organization.py
  kobo/apps/organizations/tests/test_organizations_api.py
  kobo/apps/organizations/views.py
  kobo/settings/base.py
  kpi/mixins/standardize_searchable_field.py
  kpi/serializers/current_user.py
  kpi/tests/api/test_api_environment.py
  kpi/tests/test_user.py
  kpi/versioning.py
  kpi/views/__init__.py
  kpi/views/current_user.py
Labels: Back end

#5202 Update AssetResponse object to match latest BE response
  jsapp/js/assetUtils.ts
  jsapp/js/components/formGallery/formGallery.selectors.ts
  jsapp/js/components/metadataEditor.es6
  jsapp/js/components/permissions/permConstants.ts
  jsapp/js/components/reports/reportStyleSettings.component.tsx
  jsapp/js/components/submissions/mediaCell.tsx
  jsapp/js/components/submissions/submissionDataTable.tsx
  jsapp/js/components/submissions/table.tsx
  jsapp/js/dataInterface.ts
  jsapp/js/projects/customViewStore.ts
  jsapp/js/projects/projectsTable/projectsTableRow.tsx
  jsapp/js/router/permProtectedRoute.tsx
Labels: Front end

#5179 [TASK-958] Automatically assign Asset owner to Organization owner for Multi-Member Organizations
  hub/models/extra_user_detail.py
  kobo/apps/accounts/tests/test_backend.py
  kobo/apps/audit_log/audit_actions.py
  kobo/apps/audit_log/base_views.py
  kobo/apps/audit_log/middleware.py
  kobo/apps/audit_log/migrations/0012_alter_auditlog_action.py
  kobo/apps/audit_log/models.py
  kobo/apps/audit_log/tests/api/v2/test_api_audit_log.py
  kobo/apps/audit_log/tests/test_base_views.py
  kobo/apps/audit_log/tests/test_models.py
  kobo/apps/audit_log/tests/test_one_time_auth.py
  kobo/apps/audit_log/tests/test_project_history_logs.py
  kobo/apps/audit_log/tests/test_signals.py
  kobo/apps/kobo_auth/models.py
  kobo/apps/kobo_auth/signals.py
  kobo/apps/organizations/migrations/0005_add_mmo_override_field_to_organization.py
  kobo/apps/organizations/migrations/0006_update_organization_name.py
  kobo/apps/organizations/models.py
  kobo/apps/organizations/serializers.py
  kobo/apps/organizations/tests/test_organization.py
  kobo/apps/organizations/tests/test_organizations_api.py
  kobo/apps/organizations/views.py
  kobo/apps/trash_bin/tasks.py
  kobo/apps/trash_bin/tests/test_utils.py
  kobo/apps/trash_bin/utils.py
  kobo/settings/base.py
  kpi/fixtures/asset_with_settings_and_qa.json
  kpi/mixins/standardize_searchable_field.py
  kpi/serializers/current_user.py
  kpi/serializers/v2/asset.py
  kpi/tests/api/test_api_environment.py
  kpi/tests/api/v2/test_api_assets.py
  kpi/tests/test_user.py
  kpi/versioning.py
  kpi/views/__init__.py
  kpi/views/current_user.py
  kpi/views/environment.py
  kpi/views/v2/asset.py
  kpi/views/v2/data.py
Labels: Back end

#5164 refactor(account): query-ify OrganizationContext TASK-1194
  jsapp/js/account/accountSidebar.tsx
  jsapp/js/account/billingContextProvider.component.tsx
  jsapp/js/account/organizations/requireOrgOwner.component.tsx
  jsapp/js/account/organizations/useOrganization.hook.tsx
  jsapp/js/account/plans/plan.component.tsx
  jsapp/js/account/plans/planButton.component.tsx
  jsapp/js/account/stripe.api.ts
  jsapp/js/account/usage/usageProjectBreakdown.tsx
  jsapp/js/hooks/useApiFetcher.hook.ts
  jsapp/js/query/queryKeys.ts
Labels: Front end

#5194 [TASK-1083] Add utils for determining MMO labeling
  jsapp/js/account/organizations/organizations.utils.tsx
  jsapp/js/envStore.ts
Labels: Front end

#5167 Fix PlanAddOn creation logic
  kobo/apps/stripe/models.py
  kobo/apps/stripe/tests/test_one_time_addons_api.py
Labels: Back end

#5206 [TASK-1199] Fix geo-points now displaying in map
  jsapp/js/components/map.es6
Labels: Front end

#5197 [TASK-1096] Implementation of queries for organization
  jsapp/js/account/stripe.api.ts
  jsapp/js/account/stripe.types.ts
  jsapp/js/dataInterface.ts
Labels: Front end

#5193 Log project name and settings changes
  kobo/apps/audit_log/audit_actions.py
  kobo/apps/audit_log/base_views.py
  kobo/apps/audit_log/models.py
  kobo/apps/audit_log/tests/test_project_history_logs.py
  kpi/fixtures/asset_with_settings_and_qa.json
  kpi/models/asset.py
  kpi/views/v2/asset.py
Labels: Back end

#5212 Move accessLogs.query.ts file to feature directory
  jsapp/js/account/security/accessLogs/accessLogs.query.ts
  jsapp/js/account/security/accessLogs/accessLogsSection.component.tsx
Labels: Front end

#5214 Fix Help menu display bug - Task-1211
  jsapp/js/components/support/helpBubble.tsx
Labels: bug-fix, Front end

#5205 Fix SSRFProtect validation options to properly handle Constance settings
  kobo/apps/hook/models/service_definition_interface.py
  kobo/apps/hook/tests/test_ssrf.py
  kpi/tests/test_utils.py
  kpi/utils/strings.py
Labels: bug-fix, Back end

#5199 Log changes to project sharing
  kobo/apps/audit_log/audit_actions.py
  kobo/apps/audit_log/models.py
  kobo/apps/audit_log/tests/test_project_history_logs.py
  kpi/fixtures/asset_with_settings_and_qa.json
  kpi/views/v2/asset.py
Labels: Back end

#5215 [Task-979] Remove submission counter and add organization name to header if MMO is enabled
  jsapp/js/components/header/mainHeader.component.tsx
  jsapp/js/components/header/mainHeaderBase.component.tsx
  jsapp/js/components/header/organizationBadge.component.tsx
  jsapp/js/components/header/organizationBadge.module.scss
  jsapp/scss/components/_kobo.navigation.scss
Labels: Front end
