Repository kobotoolbox/kpi, pull requests merged in 2024-09, with the labels that each got.

#5081 Create access logs for authorized applications authenticating users
  kobo/apps/audit_log/models.py
  kobo/apps/audit_log/tests/test_models.py
  kobo/apps/audit_log/tests/test_one_time_auth.py
  kpi/constants.py
  kpi/models/authorized_application.py
  kpi/urls/__init__.py
  kpi/views/__init__.py
  kpi/views/v2/user.py
Labels: Back end

#5100 Fix asset clone UI crash
  jsapp/js/components/formLanding.js
Labels: Front end

#5096 Fix misalignment of columns in data table after paginating
  jsapp/js/components/submissions/table.tsx
Labels: bug-fix, Front end

#5105 Fix bad performance introduced in `2.024.25`
  kobo/apps/openrosa/apps/logger/migrations/0035_add_index_on_logger_xform__kpi_asset_uid.py
  kobo/apps/openrosa/apps/logger/models/xform.py
  kpi/migrations/0057_add_index_on_kpi_asset__deployment_data__formid.py
  kpi/models/asset.py
Labels: bug-fix, Back end

#5110 Remove unused field in audit log API responses
  kobo/apps/audit_log/serializers.py
  kobo/apps/audit_log/tests/api/v2/test_api_audit_log.py
  kobo/apps/audit_log/views.py
Labels: API, Back end

#5083 Add Python linter to GitHub Actions
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/darker.yml
  dependencies/pip/dev_requirements.in
  dependencies/pip/dev_requirements.txt
  format-python.sh
  pyproject.toml
Labels: enhancement, Back end

#5108 [TASK-858] UniversalTable component
  jsapp/js/universalTable/paginatedQueryUniversalTable.component.tsx
  jsapp/js/universalTable/universalTable.component.tsx
  jsapp/js/universalTable/universalTable.module.scss
  jsapp/svg-icons/angle-bar-left.svg
  jsapp/svg-icons/angle-bar-right.svg
  jsapp/svg-icons/angle-down.svg
  jsapp/svg-icons/angle-left.svg
  jsapp/svg-icons/angle-right.svg
  jsapp/svg-icons/angle-up.svg
  package-lock.json
  package.json
Labels: Front end

#5114 Fix Python formatter error with owner discrepancy in the container
  .github/workflows/darker.yml
  format-python.sh
Labels: Back end

#5092 Refactor access logs
  kobo/apps/audit_log/migrations/0010_accesslog.py
  kobo/apps/audit_log/mixins.py
  kobo/apps/audit_log/models.py
  kobo/apps/audit_log/signals.py
  kobo/apps/audit_log/tests/api/v2/test_api_audit_log.py
  kobo/apps/audit_log/tests/test_models.py
  kobo/apps/audit_log/tests/test_signals.py
  kobo/apps/audit_log/views.py
  kpi/constants.py
  kpi/views/__init__.py
Labels: Back end

#5119 Fix ignore list for flake8
  .github/workflows/darker.yml
Labels: Back end

#5106 Log out user from all devices
  kobo/settings/base.py
  kpi/tests/api/v2/test_api_logout_all.py
  kpi/urls/__init__.py
  kpi/views/v2/logout.py
Labels: API, Back end

#4986 Add django-import-export for organization users
  dependencies/pip/dev_requirements.txt
  dependencies/pip/requirements.in
  dependencies/pip/requirements.txt
  kobo/apps/organizations/admin.py
  kobo/settings/base.py
Labels: Back end

#5127 Clean-up `pytz` import removal
  dependencies/pip/dev_requirements.txt
  dependencies/pip/requirements.in
  dependencies/pip/requirements.txt
  kpi/views/v2/asset.py
  pip-compile.sh
Labels: Back end

#5124 Canceled subscription date fix
  dependencies/pip/dev_requirements.in
  dependencies/pip/dev_requirements.txt
  kobo/apps/organizations/utils.py
  kobo/apps/stripe/tests/test_organization_usage.py
Labels: Back end

#5123 Update NLP README to include information on API calls
  jsapp/js/components/processing/README.md
Labels: Front end, documentation

#5079 Typescriptize reports files
  jsapp/js/actions.d.ts
  jsapp/js/actions.es6
  jsapp/js/components/common/modal.tsx
  jsapp/js/components/reports/chartColorsPicker.es6
  jsapp/js/components/reports/chartTypePicker.component.tsx
  jsapp/js/components/reports/customReportEditor.component.tsx
  jsapp/js/components/reports/customReportForm.es6
  jsapp/js/components/reports/questionGraphSettings.es6
  jsapp/js/components/reports/reportColorsEditor.component.tsx
  jsapp/js/components/reports/reportContents.component.tsx
  jsapp/js/components/reports/reportContents.es6
  jsapp/js/components/reports/reportStyleSettings.component.tsx
  jsapp/js/components/reports/reportStyleSettings.es6
  jsapp/js/components/reports/reportStyleSettingsSingleQuestion.component.tsx
  jsapp/js/components/reports/reportTypeEditor.component.tsx
  jsapp/js/components/reports/reportTypeEditor.module.scss
  jsapp/js/components/reports/reportViewItem.component.tsx
  jsapp/js/components/reports/reports.scss
  jsapp/js/components/reports/reports.tsx
  jsapp/js/components/reports/reports.utils.ts
  jsapp/js/components/reports/reportsConstants.ts
  jsapp/js/components/reports/reportsModalTabs.component.tsx
  jsapp/js/dataInterface.ts
  jsapp/js/formbuild/containers/KoboMatrix.es6
  jsapp/js/popoverMenu.scss
  jsapp/js/utils.ts
  jsapp/xlform/src/model.choices.coffee
  jsapp/xlform/src/model.configs.coffee
  jsapp/xlform/src/model.row.coffee
  jsapp/xlform/src/model.survey.coffee
  jsapp/xlform/src/model.surveyFragment.coffee
  jsapp/xlform/src/model.utils.coffee
Labels: Front end

#5132 Change access log endpoint names
  kobo/apps/audit_log/urls.py
  kobo/apps/audit_log/views.py
Labels: API, Back end

#5021 Replace default values with (invalid) placeholders
  .github/workflows/pytest.yml
  kobo/settings/base.py
Labels: Back end
