Repository kobotoolbox/kpi, pull requests merged in 2025-01, with the labels that each got.

#5406 chore(api): add missing fetch utility functions
  jsapp/js/api.ts
Labels: Front end

#5403 fix(BugFixes) Fix error handling for invalid XLS forms TASK-1353
  jsapp/js/actions.es6
  kpi/serializers/v2/deployment.py
  kpi/tests/api/v2/test_api_assets.py
Labels: bug-fix, Back end

#5366 refactor(SimpleTable): drop BEM, use Mantine TASK-1377
  jsapp/js/bemComponents.ts
  jsapp/js/components/common/SimpleTable.module.scss
  jsapp/js/components/common/SimpleTable.stories.tsx
  jsapp/js/components/common/SimpleTable.tsx
  jsapp/js/components/modalForms/bulkEditSubmissionsForm.es6
  jsapp/js/components/modalForms/bulkEditSubmissionsForm.scss
  jsapp/js/components/projectDownloads/projectExportsList.es6
  jsapp/js/components/submissions/submissionDataTable.tsx
  jsapp/js/theme/kobo/Table.ts
  jsapp/js/theme/kobo/index.ts
  jsapp/scss/components/_kobo.project-downloads.scss
  jsapp/scss/components/_kobo.simple-table.scss
  jsapp/scss/main.scss
Labels: UI & UX, Front end, refactor

#5405 refactor(library locking): migrate files to TypeScript
  jsapp/js/components/locking/formLockedMessage.tsx
  jsapp/js/components/locking/lockingConstants.es6
  jsapp/js/components/locking/lockingConstants.ts
  jsapp/js/components/locking/lockingUtils.es6
  jsapp/js/components/locking/lockingUtils.mocks.es6
  jsapp/js/components/locking/lockingUtils.mocks.ts
  jsapp/js/components/locking/lockingUtils.tests.ts
  jsapp/js/components/locking/lockingUtils.ts
  jsapp/js/components/metadataEditor.es6
  jsapp/js/components/modalForms/projectSettings.es6
  jsapp/js/components/modalForms/translationSettings.es6
  jsapp/js/components/modalForms/translationTable.es6
  jsapp/js/dataInterface.ts
  jsapp/js/editorMixins/editableForm.es6
  jsapp/xlform/src/view.row.coffee
  jsapp/xlform/src/view.surveyApp.coffee
Labels: Front end

#5410 feat(organizations): add mantine menu theme/story TASK-1382
  jsapp/js/components/common/dropdownmenu.stories.tsx
  jsapp/js/theme/kobo/index.ts
  jsapp/js/theme/kobo/menu.module.css
  jsapp/js/theme/kobo/menu.ts
Labels: Front end

#5413 fix(OpenRosa): assign default `openrosa` model-level permissions to the correct database
  kpi/deployment_backends/kc_access/utils.py
Labels: CRITICAL

#5404 feat(projectHistoryLog): record submission modifications
  kobo/apps/audit_log/audit_actions.py
  kobo/apps/audit_log/base_views.py
  kobo/apps/audit_log/migrations/0015_add_submission_audit_actions.py
  kobo/apps/audit_log/models.py
  kobo/apps/audit_log/signals.py
  kobo/apps/audit_log/tests/test_project_history_logs.py
  kobo/apps/audit_log/utils.py
  kobo/apps/audit_log/views.py
  kobo/apps/openrosa/apps/logger/utils/instance.py
  kpi/views/v2/asset_snapshot.py
  kpi/views/v2/data.py
Labels: Back end

#5393 feat(organizations): handle user removes itself flow TASK-1354
  jsapp/js/account/organization/MemberActionsDropdown.tsx
  jsapp/js/account/organization/MemberRemoveModal.tsx
  jsapp/js/account/organization/membersQuery.ts
  jsapp/js/account/organization/organizationQuery.ts
  jsapp/js/stores/useSession.tsx
Labels: Front end

#5415 test: rename admin user in fixture
  kobo/apps/audit_log/tests/api/v2/test_api_audit_log.py
  kobo/apps/audit_log/tests/test_project_history_logs.py
  kobo/apps/organizations/tests/admin/test_organization_admin.py
  kobo/apps/trash_bin/tests/test_utils.py
  kpi/fixtures/test_data.json
  kpi/tests/api/v1/test_api_permissions.py
  kpi/tests/api/v2/test_api_asset_bulk_actions.py
  kpi/tests/api/v2/test_api_asset_permission_assignment.py
  kpi/tests/api/v2/test_api_assets.py
  kpi/tests/api/v2/test_api_permissions.py
  kpi/tests/api/v2/test_api_users.py
  kpi/tests/test_permissions.py
  kpi/tests/test_token.py
Labels: Back end

#5417 fix: handle case sensitivity for "Settings" sheet name with explicit error TASK-1353
  kpi/mixins/xls_exportable.py
  kpi/serializers/v2/deployment.py
  kpi/tests/api/v2/test_api_assets.py
Labels: bug-fix, Back end

#5418 fix(auditLogs): correctly serialize audit logs from deleted users
  kobo/apps/audit_log/serializers.py
  kobo/apps/audit_log/tests/api/v2/test_api_audit_log.py
Labels: Back end

#5344 refactor(frontend): Mantine Component Library PoC
  .storybook/main.js
  .storybook/preview.js
  jsapp/js/app.jsx
  jsapp/js/bemComponents.ts
  jsapp/js/components/common/ButtonNew.tsx
  jsapp/js/components/common/SimpleTable.module.scss
  jsapp/js/components/common/SimpleTable.stories.tsx
  jsapp/js/components/common/SimpleTable.tsx
  jsapp/js/components/common/button.stories.tsx
  jsapp/js/components/common/checkbox.scss
  jsapp/js/components/common/dropdownmenu.stories.tsx
  jsapp/js/components/drawer.es6
  jsapp/js/components/modalForms/bulkEditSubmissionsForm.es6
  jsapp/js/components/modalForms/bulkEditSubmissionsForm.scss
  jsapp/js/components/projectDownloads/projectExportsList.es6
  jsapp/js/components/submissions/submissionDataTable.tsx
  jsapp/js/global.d.ts
  jsapp/js/theme/index.ts
  jsapp/js/theme/kobo/Button.module.css
  jsapp/js/theme/kobo/Button.ts
  jsapp/js/theme/kobo/Table.ts
  jsapp/js/theme/kobo/Tooltip.ts
  jsapp/js/theme/kobo/index.ts
  jsapp/js/theme/kobo/menu.module.css
  jsapp/js/theme/kobo/menu.ts
  jsapp/postcss.config.cjs
  jsapp/scss/components/_kobo.project-downloads.scss
  jsapp/scss/components/_kobo.simple-table.scss
  jsapp/scss/main.scss
  kpi.code-workspace
  package-lock.json
  package.json
Labels: Front end

#5416 feat(projectHistoryLogs): log new submissions
  kobo/apps/audit_log/models.py
  kobo/apps/audit_log/signals.py
  kobo/apps/audit_log/tests/test_project_history_logs.py
  kobo/apps/audit_log/views.py
  kobo/apps/openrosa/apps/api/viewsets/xform_submission_api.py
Labels: Back end

#5427 fix(mantine): adjust theme color hsl formatting
  jsapp/js/theme/kobo/index.ts
Labels: Front end

#5423 feat(projectHistoryLogs): log deleted submissions
  kobo/apps/audit_log/middleware.py
  kobo/apps/audit_log/models.py
  kobo/apps/audit_log/signals.py
  kobo/apps/audit_log/tests/test_project_history_logs.py
  kobo/apps/audit_log/utils.py
  kobo/apps/audit_log/views.py
  kpi/tests/api/v2/test_api_submissions.py
  kpi/views/v2/data.py
Labels: Back end

#5430 feat(projectHistoryLogs): export project history logs TASK-1056
  kobo/apps/audit_log/tests/api/v2/test_api_audit_log.py
  kobo/apps/audit_log/views.py
  kpi/migrations/0062_create_projecthistorylogexporttask.py
  kpi/models/import_export_task.py
  kpi/tests/test_access_logs_export_task.py
  kpi/tests/test_audit_logs_export_task.py
  kpi/utils/data_exports.py
Labels: API, Back end

#5431 fix(auditLogs): do not try to create logs after 404s
  kobo/apps/audit_log/middleware.py
Labels: Back end

#5422 feat(organizations): add wrapped mantine alert component TASK-1380
  jsapp/js/components/common/alert.stories.tsx
  jsapp/js/components/common/alert.tsx
  jsapp/js/components/common/inlineMessage.stories.tsx
  jsapp/js/theme/kobo/Alert.module.css
  jsapp/js/theme/kobo/Alert.ts
  jsapp/js/theme/kobo/index.ts
Labels: Front end

#5425 feat(organizations): add theming/story for Mantine Loader and LoadingOverlay TASK-1464
  jsapp/js/components/common/loader.stories.tsx
  jsapp/js/components/common/loadingOverlay.stories.tsx
  jsapp/js/theme/kobo/Loader.tsx
  jsapp/js/theme/kobo/index.ts
Labels: Front end

#5428 feat(projectHistory): handle submission related audit actions TASK-1409
  jsapp/js/components/activity/activity.constants.ts
  jsapp/js/components/activity/activityLogs.query.ts
Labels: Front end

#5433 feat(activityLogs): add API call for export button and remove feature flag for it TASK-1411 TASK-1410
  jsapp/js/api.endpoints.ts
  jsapp/js/components/activity/activityLogs.query.ts
  jsapp/js/components/activity/formActivity.tsx
  jsapp/js/featureFlags.ts
Labels: blocked, Front end

#5426 refactor(projectDownloads): migrate files to TypeScript
  jsapp/js/actions.d.ts
  jsapp/js/assetUtils.ts
  jsapp/js/components/common/checkbox.tsx
  jsapp/js/components/common/multiCheckbox.tsx
  jsapp/js/components/formSubScreens.js
  jsapp/js/components/locking/lockingConstants.ts
  jsapp/js/components/locking/lockingUtils.mocks.ts
  jsapp/js/components/projectDownloads/AnonymousExports.tsx
  jsapp/js/components/projectDownloads/ExportTypeSelector.tsx
  jsapp/js/components/projectDownloads/LegacyExports.tsx
  jsapp/js/components/projectDownloads/ProjectDownloads.tsx
  jsapp/js/components/projectDownloads/ProjectExportsCreator.tsx
  jsapp/js/components/projectDownloads/ProjectExportsList.tsx
  jsapp/js/components/projectDownloads/exportsConstants.ts
  jsapp/js/components/projectDownloads/exportsStore.es6
  jsapp/js/components/projectDownloads/exportsStore.ts
  jsapp/js/components/projectDownloads/exportsUtils.ts
  jsapp/js/components/submissions/tableUtils.mocks.ts
  jsapp/js/dataInterface.ts
  jsapp/js/utils.ts
  jsapp/scss/components/_kobo.project-downloads.scss
Labels: Front end

#5395 feat(organizations): create endpoints to handle organization invitations TASK-969
  kobo/apps/organizations/constants.py
  kobo/apps/organizations/migrations/0010_add_status_and_invitee_role_to_organization_invitation.py
  kobo/apps/organizations/models.py
  kobo/apps/organizations/permissions.py
  kobo/apps/organizations/serializers.py
  kobo/apps/organizations/tasks.py
  kobo/apps/organizations/templates/emails/accepted_invite.html
  kobo/apps/organizations/templates/emails/accepted_invite.txt
  kobo/apps/organizations/templates/emails/declined_invite.html
  kobo/apps/organizations/templates/emails/declined_invite.txt
  kobo/apps/organizations/templates/emails/expired_invite.html
  kobo/apps/organizations/templates/emails/expired_invite.txt
  kobo/apps/organizations/templates/emails/registered_user_invite.html
  kobo/apps/organizations/templates/emails/registered_user_invite.txt
  kobo/apps/organizations/templates/emails/unregistered_user_invite.html
  kobo/apps/organizations/templates/emails/unregistered_user_invite.txt
  kobo/apps/organizations/tests/test_organization_invitations.py
  kobo/apps/organizations/tests/test_organization_members_api.py
  kobo/apps/organizations/views.py
  kobo/settings/base.py
  kpi/urls/router_api_v2.py
  kpi/utils/mailer.py
  kpi/utils/placeholders.py
Labels: Back end

#5409 feat(invites): query file for handling API TASK-1092 TASK-991
  jsapp/js/account/organization/membersInviteQuery.ts
  jsapp/js/account/organization/membersQuery.ts
  jsapp/js/api.endpoints.ts
  jsapp/js/query/queryKeys.ts
Labels: Front end

#5443 fix(billing): require org id for service/asset usage TASK-1476
  jsapp/js/account/usage/usage.api.ts
  jsapp/js/account/usage/usageProjectBreakdown.tsx
  jsapp/js/account/usage/useUsage.hook.ts
Labels: Front end

#5449 feat(billing): remove feature flag for one time addons TASK-1479
  jsapp/js/account/accountSidebar.tsx
  jsapp/js/account/addOns/addOnList.component.tsx
  jsapp/js/featureFlags.ts
Labels: Front end

#5448 feat(organization): export organization users asynchronously from Admin interface TASK-1478
  dependencies/pip/dev_requirements.txt
  dependencies/pip/requirements.in
  dependencies/pip/requirements.txt
  kobo/apps/organizations/admin.py
  kobo/apps/organizations/models.py
  kobo/settings/base.py
Labels: enhancement, Back end

#5439 fix(submissions): avoid adding XML declaration when rewriting submission XML and creating asset snapshot
  kobo/apps/openrosa/apps/logger/tests/test_set_meta_function.py
  kobo/apps/openrosa/apps/logger/xform_instance_parser.py
Labels: Back end

#5434 feat: back-fill submission unique identifier - TASK 1459
  kobo/apps/long_running_migrations/jobs/0005_back_fill_logger_instance_root_uuid.py
  kobo/apps/long_running_migrations/migrations/0005_back_fill_logger_instance_root_uuid.py
  kpi/signals.py
Labels: Back end

#5452 chore(organizations): add search field to organization user admin page
  kobo/apps/organizations/admin.py
Labels: enhancement, Back end

#5454 refactor(frontend): move landing, summary and map files into separate directories
  jsapp/js/components/formLanding/formLanding.js
  jsapp/js/components/formSubScreens.js
  jsapp/js/components/formSummary/formSummary.js
  jsapp/js/components/formSummary/formSummary.scss
  jsapp/js/components/formSummary/formSummaryProjectInfo.tsx
  jsapp/js/components/map/map.es6
  jsapp/js/components/map/map.marker-colors.scss
  jsapp/js/components/map/map.scss
  jsapp/js/components/map/mapSettings.es6
  jsapp/js/router/router.tsx
Labels: Front end, refactor

#5432 feat(organizations): add theming/story for Mantine Modal TASK-1423
  jsapp/js/components/common/modal.stories.tsx
  jsapp/js/components/modals/koboModal.stories.tsx
  jsapp/js/theme/kobo/Modal.module.css
  jsapp/js/theme/kobo/Modal.tsx
  jsapp/js/theme/kobo/index.ts
Labels: Front end

#5456 fix(billing): correct addon modal usage calculations TASK-1483
  jsapp/js/account/usage/oneTimeAddOnUsageModal/oneTimeAddOnUsageModal.component.tsx
Labels: Front end

#5436 fix(exports): tasks stuck in processing TASK-1243
  kobo/apps/audit_log/views.py
  kobo/apps/project_views/views.py
  kobo/settings/base.py
  kpi/serializers/v2/export_task.py
  kpi/tasks.py
  kpi/tests/api/v1/test_api_assets.py
  kpi/tests/api/v2/test_api_exports.py
  kpi/views/v1/export_task.py
Labels: Back end

#5442 chore: upgrade pyxform TASK-1467
  dependencies/pip/dev_requirements.txt
  dependencies/pip/requirements.in
  dependencies/pip/requirements.txt
  kobo/apps/openrosa/apps/logger/xform_instance_parser.py
  kobo/apps/openrosa/apps/viewer/models/data_dictionary.py
  kobo/apps/openrosa/apps/viewer/pandas_mongo_bridge.py
  kobo/apps/openrosa/libs/data/query.py
  kobo/apps/openrosa/libs/utils/export_tools.py
Labels: Back end

#5437 feat(helpBubble): add Academy link and update text of existing links
  jsapp/js/components/support/helpBubble.tsx
  jsapp/js/envStore.ts
  jsapp/svg-icons/forum.svg
  jsapp/svg-icons/help-academy.svg
  jsapp/svg-icons/help-articles.svg
  jsapp/svg-icons/help-forum.svg
  kobo/settings/base.py
  kpi/tests/api/test_api_environment.py
  kpi/views/environment.py
Labels: Front end

#5424 feat(organizations): add theming/story for Mantine TextInput TASK-1378
  jsapp/js/components/common/textBox.stories.tsx
  jsapp/js/components/common/textBox.tsx
  jsapp/js/components/common/textInput.stories.tsx
  jsapp/js/theme/kobo/InputBase.module.css
  jsapp/js/theme/kobo/InputBase.ts
  jsapp/js/theme/kobo/index.ts
Labels: Front end

#5455 fix(NLP): 500 error when transcribing audio TASK-1485
  kobo/apps/stripe/tests/test_organization_usage.py
  kobo/apps/stripe/utils.py
Labels: Back end

#5459 fix(organizations): adjust self-ownership check logic TASK-1490
  jsapp/js/assetUtils.ts
  jsapp/js/components/formSummary/formSummaryProjectInfo.tsx
  jsapp/js/components/modalForms/projectSettings.es6
  jsapp/js/projects/projectsTable/projectsTableRow.tsx
Labels: Front end

#5457 feat(organizations): Add isEmpty to avatar component and use it for members table TASK-1420
  jsapp/js/components/common/avatar.module.scss
  jsapp/js/components/common/avatar.stories.tsx
  jsapp/js/components/common/avatar.tsx
Labels: Front end
