Repository kobotoolbox/kpi, pull requests merged in 2025-09, with the labels that each got.

#6201 fix(exports): use empty object for empty payload DEV-959
  jsapp/js/account/security/accessLogs/accessLogs.query.ts
Labels: Front end

#5875 fix(frontend): ensure country list respects RTL languages DEV-841
  jsapp/js/assetUtils.ts
  package-lock.json
  package.json
Labels: Front end

#6202 fix(languageSelector): remove native cancel button on chrome DEV-360
  jsapp/js/components/languages/languageSelector.scss
Labels: Front end

#6205 feat(removeAttachments): add remove attachment activity constants DEV-962
  jsapp/js/components/activity/activity.constants.ts
Labels: Front end

#6204 feat(reversion): optimize version removal task DEV-946
  kpi/tasks.py
Labels: Back end

#6150 ci(releases): generate changelog DEV-301
  .github/workflows/release-2-stabilize.yml
  .gitignore
  cliff.toml
  package-lock.json
  package.json
  scripts/find_releases.sh
Labels: workflow

#6207 fix(audioRecording): background audio file being soft deleted on creation DEV-976
  kobo/apps/openrosa/libs/utils/logger_tools.py
Labels: Back end

#6213 ci(releases): set git config for committing DEV-301
  .github/workflows/release-1-branch.yml
  .github/workflows/release-2-stabilize.yml
Labels: workflow

#6206 docs(migrations): improve instructions to add NOT NULL constraints manually to large `logger_attachment` tables
  kobo/apps/openrosa/apps/logger/migrations/0044_alter_attachment_to_remove_null_values.py
Labels: Back end

#6218 fix(mapView): fix disaggregate button not working DEV-991
  jsapp/js/components/formSubScreens.js
  jsapp/js/components/map/index.tsx
Labels: Front end

#6197 feat(dataCollectors): update enketo links when assigning assets to groups DEV-798
  kobo/apps/data_collectors/admin.py
  kpi/deployment_backends/base_backend.py
  kpi/deployment_backends/mock_backend.py
  kpi/deployment_backends/openrosa_backend.py
  kpi/models/asset.py
  kpi/signals.py
  kpi/tests/test_assets.py
Labels: Back end

#6219 chore: add psutil and objgraph
  dependencies/pip/dev_requirements.txt
  dependencies/pip/requirements.in
  dependencies/pip/requirements.txt
Labels: Back end

#6224 fix(billing): remove days filter on usage counter updates DEV-1001
  kobo/apps/stripe/tasks.py
  kobo/apps/stripe/tests/test_celery_tasks.py
Labels: Back end

#6244 chore(dependencies): bump package-lock
  package-lock.json
Labels: dependencies, Front end

#6238 fix(sso): do not allow sso users to change email from account settings DEV-1005
  kobo/apps/accounts/serializers.py
  kobo/apps/accounts/tests/test_email.py
Labels: Back end

#6256 chore(reversion): turn off reversion vacuum
  kobo/settings/base.py
Labels: Back end

#6254 feat(usageLimits): conditional over usage limit error message DEV-993
  kobo/apps/openrosa/libs/utils/logger_tools.py
Labels: Back end

#6250 fix(sso): update primary email when enabling SSO DEV-1005
  kobo/apps/accounts/apps.py
  kobo/apps/accounts/serializers.py
  kobo/apps/accounts/signals.py
  kobo/apps/accounts/tests/test_email.py
  kobo/apps/accounts/tests/test_signals.py
Labels: Back end

#6233 fix(docs): Use a shared type for service usage balances values DEV-954
  jsapp/js/api/models/organizationServiceUsageResponseBalances.ts
  jsapp/js/api/models/organizationServiceUsageResponseBalancesAsrSeconds.ts
  jsapp/js/api/models/organizationServiceUsageResponseBalancesMtCharacters.ts
  jsapp/js/api/models/organizationServiceUsageResponseBalancesStorageBytes.ts
  jsapp/js/api/models/organizationServiceUsageResponseBalancesSubmission.ts
  jsapp/js/api/models/serviceUsageBalanceData.ts
  jsapp/js/api/models/serviceUsageResponseBalances.ts
  jsapp/js/api/models/serviceUsageResponseBalancesAsrSeconds.ts
  jsapp/js/api/models/serviceUsageResponseBalancesStorageBytes.ts
  jsapp/js/api/models/serviceUsageResponseBalancesSubmission.ts
  kpi/schema_extensions/v2/organizations/extensions.py
  kpi/schema_extensions/v2/service_usage/extensions.py
  kpi/schema_extensions/v2/service_usage/fields.py
  static/openapi/schema_v2.json
  static/openapi/schema_v2.yaml
Labels: Back end, documentation

#6237 chore(sass): update sass and sass-loader DEV-999
  jsapp/js/components/common/button.scss
  jsapp/js/components/common/koboSelect.scss
  jsapp/js/components/common/tooltip.scss
  jsapp/js/components/newFeatureDialog.module.scss
  jsapp/js/popoverMenu.scss
  jsapp/scss/components/_kobo.bem.ui.scss
  jsapp/scss/components/_kobo.button.scss
  jsapp/scss/components/_kobo.drawer.scss
  jsapp/scss/components/_kobo.form-builder.scss
  jsapp/scss/components/_kobo.form-view.scss
  jsapp/scss/components/_kobo.lib-list.scss
  jsapp/scss/components/_kobo.navigation.scss
  jsapp/scss/components/_kobo.tooltips-big.scss
  jsapp/scss/libs/_mdl.scss
  jsapp/scss/libs/alertify.overrides.scss
  jsapp/scss/libs/react-select.overrides.scss
  jsapp/scss/main.scss
  jsapp/scss/stylesheets/pages/form_builder.scss
  jsapp/scss/stylesheets/partials/_base.scss
  jsapp/scss/stylesheets/partials/_misc.scss
  jsapp/scss/stylesheets/partials/_registration.scss
  jsapp/scss/stylesheets/partials/_select2_override.scss
  jsapp/scss/stylesheets/partials/_tagsinput_override.scss
  jsapp/scss/stylesheets/partials/form_builder/_card.scss
  jsapp/scss/stylesheets/partials/form_builder/_card_multichoice.scss
  jsapp/scss/stylesheets/partials/form_builder/_card_settings.scss
  jsapp/scss/stylesheets/partials/form_builder/_common.scss
  jsapp/scss/stylesheets/partials/form_builder/_group.scss
  jsapp/scss/stylesheets/partials/form_builder/_misc.scss
  jsapp/scss/stylesheets/partials/form_builder/_params_view.scss
  jsapp/scss/stylesheets/partials/form_builder/_row_questiontypes.scss
  jsapp/scss/stylesheets/partials/form_builder/_survey_row.scss
  kpi/static/css/main.css
  package-lock.json
  package.json
Labels: Front end

#6257 fix(api): restore default renderers for API `v1` DEV-1006
  kobo/apps/openrosa/apps/api/viewsets/data_viewset.py
  kobo/apps/openrosa/apps/api/viewsets/xform_viewset.py
Labels: API, Back end

#6260 ci(storybook): Prevent Storybook cache from interfering with CI runs DEV-892
  .github/filters.yml
  .github/workflows/npm-test.yml
Labels: Front end, github actions

#6264 fix(usageLimits): transfer button blocking when enforcing config is false
  jsapp/js/components/permissions/transferProjects/transferProjects.component.tsx
Labels: bug

#6199 fix(frontend): roboto font loading DEV-887
  jsapp/js/main.js
  jsapp/scss/fonts/_roboto.scss
  jsapp/scss/main.scss
  package-lock.json
  package.json
Labels: Front end

#6287 ci(openApi): enforce drf-spectacular warnings as errors DEV-1069
  .github/workflows/openapi.yml
Labels: workflow

#6284 fix(api): type /organizations/:id/service_usage response DEV-1062
  jsapp/js/api/models/nullableServiceUsageBalanceData.ts
  jsapp/js/api/models/organizationServiceUsageResponse.ts
  jsapp/js/api/models/organizationServiceUsageResponseBalances.ts
  jsapp/js/api/models/serviceUsageBalanceData.ts
  jsapp/js/api/models/serviceUsageBalances.ts
  jsapp/js/api/models/serviceUsageResponse.ts
  kpi/schema_extensions/v2/generic/schema.py
  kpi/schema_extensions/v2/organizations/extensions.py
  kpi/schema_extensions/v2/organizations/serializers.py
  kpi/schema_extensions/v2/service_usage/extensions.py
  static/openapi/schema_v2.json
  static/openapi/schema_v2.yaml
Labels: Back end, documentation

#6294 refactor(ts): handle scss imports DEV-1076
  jsapp/js/theme/kobo/Button.module.css
  tsconfig.json
Labels: Front end

#6300 ci(biome): filter for and lint tsconfig.json also DEV-1080
  .github/filters.yml
  tsconfig.json
Labels: Front end

#6306 fix(reactQuery): handle empty requests by Orval DEV-1091
  jsapp/js/api.ts
Labels: Front end

#6135 fix(nlp): Permission error in qualitative analysis UI DEV-162
  jsapp/js/components/processing/analysis/utils.ts
  jsapp/js/components/processing/transcript/stepBegin.component.tsx
  jsapp/js/components/processing/transcript/stepEditor.component.tsx
  jsapp/js/components/processing/transcript/stepViewer.component.tsx
  jsapp/js/components/processing/translations/stepEditor.component.tsx
  jsapp/js/components/processing/translations/stepSingleViewer.component.tsx
  kpi/permissions.py
  kpi/tests/api/v2/test_api_assets.py
Labels: Back end, Front end
