Repository kobotoolbox/kpi, pull requests merged in 2025-02, with the labels that each got.

#5453 refactor(RESTServices): migrate code to TypeScript
  jsapp/js/actions.d.ts
  jsapp/js/components/RESTServices/RESTServiceLogs.tsx
  jsapp/js/components/RESTServices/RESTServices.scss
  jsapp/js/components/RESTServices/RESTServicesForm.tsx
  jsapp/js/components/RESTServices/RESTServicesList.tsx
  jsapp/js/components/RESTServices/index.tsx
  jsapp/js/dataInterface.ts
  jsapp/scss/components/_kobo.service-row.scss
Labels: Front end, refactor

#5465 fix(submissions): deletion issue after project transfer TASK-1504
  kobo/apps/openrosa/apps/logger/utils/database_query.py
  kobo/apps/openrosa/apps/viewer/models/parsed_instance.py
  kpi/tests/api/v2/test_api_submissions.py
Labels: bug-fix, Back end

#5451 feat(organizations): narrow down `My projects` list of the organization owner TASK-1187
  kobo/apps/project_ownership/models/transfer.py
  kpi/filters.py
  kpi/migrations/0062_add_is_excluded_from_projects_list_to_asset.py
  kpi/models/asset.py
  kpi/serializers/v2/asset.py
  kpi/tests/test_assets.py
  kpi/views/v2/asset.py
Labels: Back end

#5478 fix(SSO): only allow SSO email when registering TASK-1493
  kobo/apps/accounts/forms.py
  kobo/apps/accounts/tests/test_forms.py
  kobo/settings/base.py
Labels: Back end, Front end

#5484 ci: failed Github Actions notify Zulip
  .github/workflows/ci-main.yml
  .github/workflows/ci-pr.yml
  .github/workflows/npm-test.yml
  .github/workflows/pytest.yml
Labels: workflow

#5487 build(frontend): use pinned, active and current node version
  .github/workflows/npm-test.yml
Labels: Front end

#5486 fix(frontend): conditional router error message
  jsapp/js/router/accessDenied.tsx
Labels: Front end

#5458 fix(organizations): include `organization_id` in the organization invitation link TASK-1491
  kobo/apps/organizations/models.py
  kobo/apps/organizations/serializers.py
  kobo/apps/organizations/templates/emails/registered_user_invite.html
  kobo/apps/organizations/templates/emails/registered_user_invite.txt
  kobo/apps/organizations/templates/emails/unregistered_user_invite.html
  kobo/apps/organizations/templates/emails/unregistered_user_invite.txt
Labels: Back end

#5492 fix(organization)!: allow external users to GET their invitation before joining the organization TASK-1500
  kobo/apps/organizations/permissions.py
  kobo/apps/organizations/renderers.py
  kobo/apps/organizations/serializers.py
  kobo/apps/organizations/tests/test_organization_invitations.py
  kobo/apps/organizations/views.py
Labels: Back end

#5477 feat(organizations): restrict duplicate invitations and allow role updates by organization owner or admin TASK-1500
  kobo/apps/organizations/constants.py
  kobo/apps/organizations/serializers.py
  kobo/apps/organizations/tests/test_organization_invitations.py
  kobo/apps/organizations/views.py
Labels: Back end

#5485 style(frontend): add Biome formatter
  .eslintignore
  .eslintrc.js
  .github/CODEOWNERS
  .github/filters.yml
  .github/workflows/npm-test.yml
  .prettierrc.js
  CODING_STYLE_BE.md
  CODING_STYLE_FE.md
  CONTRIBUTING.md
  biome.jsonc
  eslint.config.mjs
  jsapp/js/i18nMissingStrings.js
  jsapp/js/libs/xlform_with_deps.js
  kpi.code-workspace
  package-lock.json
  package.json
  scripts/eslintBiome.mjs
Labels: Front end

#5480 feat(organizations): adjust members table for invitees TASK-1499
  jsapp/js/account/organization/MemberRoleSelector.tsx
  jsapp/js/account/organization/MembersRoute.tsx
  jsapp/js/account/organization/membersInviteQuery.ts
  jsapp/js/account/organization/membersQuery.ts
  jsapp/js/constants.ts
  jsapp/js/theme/kobo/Select.module.css
Labels: Front end

#5495 fix(organization)!: when admins resent an invitation, its status is reset to pending TASK-1513
  kobo/apps/organizations/models.py
  kobo/apps/organizations/serializers.py
  kobo/apps/organizations/tests/test_organization_invitations.py
  kobo/settings/base.py
Labels: Back end

#5491 fix(submissions): verify submission exists before adding or modifying extras
  kobo/apps/subsequences/api_view.py
  kobo/apps/subsequences/tests/test_submission_extras_api_post.py
Labels: Back end

#5503 fix(organization): return HTTP 429 when retrying to resend an invitation too quickly TASK-1513
  kobo/apps/organizations/serializers.py
  kobo/apps/organizations/tests/test_organization_invitations.py
  kobo/settings/base.py
  kpi/exceptions.py
  kpi/utils/drf_exceptions.py
Labels: enhancement, API, Back end

#5494 feat(organizations): add UI actions to resend and remove invitations TASK-1372
  jsapp/js/account/organization/InviteeActionsDropdown.tsx
  jsapp/js/account/organization/MemberActionsDropdown.tsx
  jsapp/js/account/organization/MembersRoute.tsx
  jsapp/js/account/organization/membersInviteQuery.ts
  jsapp/js/theme/kobo/Menu.module.css
  jsapp/js/theme/kobo/Menu.ts
Labels: Front end

#5501 docs: fix some formatting
  kobo/apps/audit_log/views.py
Labels: API, Back end

#5476 feat(submissions): frontend support for 'uuid:' prefix in 'meta/rootUuid'
  jsapp/js/actions/submissions.ts
  jsapp/js/components/processing/singleProcessingStore.ts
  jsapp/js/components/submissions/table.tsx
  jsapp/js/dataInterface.ts
  jsapp/js/utils.ts
Labels: Front end

#5502 feat(OpenRosa)!: exclude forms owned by inactive users from `formList`
  kobo/apps/openrosa/apps/api/tests/viewsets/test_xform_list_api.py
  kobo/apps/openrosa/apps/api/viewsets/xform_list_api.py
Labels: Back end

#5493 feature(organizations): add functionality to the MMO invite modal TASK-1373
  jsapp/js/account/organization/InviteModal.tsx
  jsapp/js/components/common/Select.tsx
  jsapp/js/theme/kobo/Select.module.css
  jsapp/js/utils.ts
  package-lock.json
  package.json
Labels: Front end

#5435 feat(submissions)!: add submission unique identifier (`meta/rootUuid`) in data API response TASK-1458
  jsapp/js/actions/submissions.ts
  jsapp/js/components/processing/singleProcessingStore.ts
  jsapp/js/components/submissions/table.tsx
  jsapp/js/dataInterface.ts
  jsapp/js/utils.ts
  kobo/apps/openrosa/apps/logger/xform_instance_parser.py
  kobo/apps/openrosa/apps/viewer/models/parsed_instance.py
  kobo/apps/openrosa/apps/viewer/tests/test_pandas_mongo_bridge.py
  kobo/apps/openrosa/libs/utils/common_tags.py
  kobo/apps/subsequences/migrations/0004_increase_subsequences_submission_uuid.py
  kobo/apps/subsequences/models.py
  kobo/apps/subsequences/utils/__init__.py
  kpi/deployment_backends/base_backend.py
  kpi/deployment_backends/openrosa_backend.py
  kpi/migrations/0062_increase_asset_snapshot_submission_uuid.py
  kpi/migrations/0063_add_is_excluded_from_projects_list_to_asset.py
  kpi/models/asset_snapshot.py
  kpi/tests/api/v1/test_api_submissions.py
  kpi/tests/api/v2/test_api_submissions.py
  kpi/views/v2/data.py
Labels: API, Back end

#5479 feat(organizationInvites): UI for accepting invite TASK-1093
  jsapp/js/account/organization/invites/OrgInviteAcceptedBanner.tsx
  jsapp/js/account/organization/invites/OrgInviteModal.tsx
  jsapp/js/account/organization/invites/OrgInviteModalWrapper.tsx
  jsapp/js/account/organization/membersInviteQuery.ts
  jsapp/js/account/organization/membersQuery.ts
  jsapp/js/components/newFeatureDialog.component.tsx
  jsapp/js/hooks/useSafeUsernameStorageKey.ts
  jsapp/js/projects/universalProjectsRoute.tsx
  jsapp/js/query/queryKeys.ts
  jsapp/js/theme/kobo/Modal.tsx
Labels: Front end

#5507 fix(projectTransferOwnership): typo causing attachment transfers to fail
  kobo/apps/project_ownership/management/commands/resume_failed_transfers_2_024_33f_fix.py
  kobo/apps/project_ownership/models/transfer.py
  kobo/apps/project_ownership/utils.py
Labels: bug-fix, Back end

#5511 refactor(projectTransferOwnership): update comments and rename tasks for clarity
  kobo/apps/project_ownership/tasks.py
  kobo/settings/base.py
Labels: enhancement, Back end

#5515 chores(projectOwnership): add migration to remove old task name
  kobo/apps/project_ownership/migrations/0003_remove_old_task.py
Labels: Back end

#5512 fix(frontend): modal width on large screens TASK-1551
  jsapp/js/components/common/modal.scss
Labels: bug-fix, Front end

#5504 feat(organizations): optimistic updates for members table changes TASK-1520
  jsapp/js/account/organization/MemberRoleSelector.tsx
  jsapp/js/account/organization/membersInviteQuery.ts
  jsapp/js/account/organization/membersQuery.ts
Labels: Front end

#5489 feat(projectHistoryLogs): record logs for QA data changes TASK-1506
  kobo/apps/audit_log/audit_actions.py
  kobo/apps/audit_log/base_views.py
  kobo/apps/audit_log/migrations/0016_add_modify_qa_data_action.py
  kobo/apps/audit_log/models.py
  kobo/apps/audit_log/tests/test_project_history_logs.py
  kobo/apps/audit_log/views.py
  kobo/apps/subsequences/api_view.py
Labels: API, Back end

#5505 feat(organizations): implement 'retry later' message for resend TASK-1532
  jsapp/js/account/organization/InviteeActionsDropdown.tsx
  jsapp/js/api.ts
  jsapp/js/dataInterface.ts
Labels: Front end

#5516 fix(frontend root): redirect to log in
  jsapp/js/app.jsx
  jsapp/js/router/requireAuth.tsx
Labels: Front end

#5513 fix(organization)!: Ensure email is sent on invitation resent status TASK-1549
  kobo/apps/organizations/serializers.py
  kobo/apps/organizations/tests/test_organization_invitations.py
Labels: Back end

#5519 fix(organization): ensure data transfer occurs upon invite acceptance TASK-1556
  kobo/apps/organizations/serializers.py
  kobo/apps/organizations/tests/test_organization_invitations.py
Labels: Back end

#5282 chore: remove unused import to pass flake8 on main
  kobo/apps/hook/tasks.py
Labels: Back end

#5464 fix(billing): remove quantity dropdown from frontend for nlp add-ons TASK-1482
  jsapp/js/account/addOns/addOnList.component.tsx
  jsapp/js/account/addOns/oneTimeAddOnRow.component.tsx
  jsapp/js/account/security/securityRoute.module.scss
  jsapp/js/account/usage/oneTimeAddOnUsageModal/oneTimeAddOnList/oneTimeAddOnList.component.tsx
  jsapp/js/components/special/koboAccessibleSelect.module.scss
Labels: Front end

#5522 feat(OrgInviteModal): better handling of custom errors TASK-1093
  jsapp/js/account/organization/invites/OrgInviteModal.tsx
  jsapp/js/account/organization/membersInviteQuery.ts
  jsapp/js/api.ts
Labels: Front end

#5532 fix(invitations): hide invitation accepted banner for users who are no longer members of organization TASK-1585
  jsapp/js/account/organization/invites/OrgInviteAcceptedBanner.tsx
Labels: Front end

#5533 fix(billing): billing period detection for end-of-month cancellations
  kobo/apps/organizations/utils.py
  kobo/apps/stripe/tests/test_organization_usage.py
Labels: Back end

#5535 fix(organizations: remove invite params on accept/decline TASK-1582
  jsapp/js/account/organization/invites/OrgInviteModal.tsx
  jsapp/js/account/organization/invites/OrgInviteModalWrapper.tsx
Labels: Front end

#5514 fix(trashBin): ensure projects are fully deleted and add a task restarter to restart task abruptly stopped
  kobo/apps/long_running_migrations/jobs/0005_back_fill_logger_instance_root_uuid.py
  kobo/apps/long_running_migrations/jobs/0006_fix_not_deleted_xform_from_trash_bin.py
  kobo/apps/long_running_migrations/migrations/0006_fix_not_deleted_xform_from_trash_bin.py
  kobo/apps/openrosa/apps/logger/models/xform.py
  kobo/apps/trash_bin/exceptions.py
  kobo/apps/trash_bin/tasks.py
  kobo/apps/trash_bin/utils.py
  kobo/settings/base.py
  kpi/deployment_backends/openrosa_backend.py
  kpi/utils/mongo_helper.py
Labels: Back end

#5523 fix(frontend): add `background-geopoint` question type to display in data table TASK-1457
  jsapp/js/components/submissions/submissionDataTable.tsx
  jsapp/js/constants.ts
Labels: bug-fix, Front end

#5527 fix(translations): use trimmed in all blocktrans blocks TASK-1553
  kobo/apps/accounts/templates/account/email/email_confirmation_message.txt
  kobo/apps/accounts/templates/account/email/email_confirmation_signup_message.txt
  kobo/apps/accounts/templates/account/email/email_confirmation_signup_subject.txt
  kobo/apps/accounts/templates/account/email/email_confirmation_subject.txt
  kobo/apps/accounts/templates/account/email/password_reset_key_message.txt
  kobo/apps/accounts/templates/account/email/password_reset_key_subject.txt
  kobo/apps/accounts/templates/account/email/unknown_account_message.txt
  kobo/apps/accounts/templates/account/email/unknown_account_subject.txt
  kobo/apps/accounts/templates/account/email_confirm.html
  kobo/apps/accounts/templates/socialaccount/authentication_error.html
  kobo/apps/accounts/templates/socialaccount/connections.html
  kobo/apps/accounts/templates/socialaccount/login.html
  kobo/apps/accounts/templates/socialaccount/signup.html
  kobo/apps/accounts/tests/test_email_content.py
  kobo/apps/openrosa/apps/main/templates/restricted_access.html
  kobo/apps/openrosa/apps/viewer/templates/export_list.html
  kobo/apps/organizations/templates/emails/accepted_org_invite.html
  kobo/apps/organizations/templates/emails/accepted_org_invite.txt
  kobo/apps/organizations/templates/emails/declined_org_invite.html
  kobo/apps/organizations/templates/emails/declined_org_invite.txt
  kobo/apps/organizations/templates/emails/expired_org_invite.html
  kobo/apps/organizations/templates/emails/expired_org_invite.txt
  kobo/apps/organizations/templates/emails/registered_user_invite.html
  kobo/apps/organizations/templates/emails/registered_user_invite.txt
  kobo/apps/organizations/templates/emails/unregistered_user_invite.html
  kobo/apps/organizations/templates/emails/unregistered_user_invite.txt
  kobo/apps/project_ownership/templates/emails/accepted_invite.html
  kobo/apps/project_ownership/templates/emails/accepted_invite.txt
  kobo/apps/project_ownership/templates/emails/declined_invite.html
  kobo/apps/project_ownership/templates/emails/declined_invite.txt
  kobo/apps/project_ownership/templates/emails/expired_invite.html
  kobo/apps/project_ownership/templates/emails/expired_invite.txt
  kobo/apps/project_ownership/templates/emails/new_invite.html
  kobo/apps/project_ownership/templates/emails/new_invite.txt
  kobo/apps/project_ownership/templates/emails/new_invite_org.html
  kobo/apps/project_ownership/templates/emails/new_invite_org.txt
Labels: Back end

#5536 fix(invites): display banner immediately upon accepting invitation TASK-1583
  jsapp/js/account/organization/invites/OrgInviteModal.tsx
  jsapp/js/account/organization/membersInviteQuery.ts
  jsapp/js/account/organization/membersQuery.ts
  jsapp/js/account/organization/organizationQuery.ts
Labels: Front end

#5510 docs(frontend): update t() docstring
  jsapp/js/global.d.ts
Labels: Front end

#5528 fix(frontend): improve paddings on Project Landing Page TASK-1565
  jsapp/js/components/formLanding/formLanding.js
  jsapp/js/components/library/assetContentSummary.tsx
  jsapp/scss/components/_kobo.form-view.scss
Labels: Front end

#5438 chore(OpenRosa): remove some deprecated endpoints of v1 not called anymore by KPI TASK-1356
  kobo/apps/openrosa/README.md
  kobo/apps/openrosa/REMOVALS.md
  kobo/apps/openrosa/apps/api/tests/viewsets/test_data_viewset.py
  kobo/apps/openrosa/apps/api/tests/viewsets/test_user.py
  kobo/apps/openrosa/apps/api/viewsets/data_viewset.py
Labels: Back end

#5128 Regenerate snapshots when downloading XForm XML
  kpi/renderers.py
Labels: Back end

#5542 test(snapshots): add a simple unit test to snapshot regeneration
  kpi/tests/test_asset_snapshots.py
Labels: Back end

#5541 fix(organization): assign invitations to members correctly TASK-1600
  kobo/apps/organizations/serializers.py
  kobo/apps/organizations/tests/test_organization_invitations.py
  kobo/apps/organizations/tests/test_organization_members_api.py
  kobo/apps/organizations/views.py
Labels: API, Back end

#5540 fix(organization)!: restrict invite details to the user's current organization TASK-1590
  kobo/apps/organizations/tests/test_organization_members_api.py
Labels: Back end

#5546 fix(notifications): use toast instead of alertify
  jsapp/js/account/organization/InviteeActionsDropdown.tsx
  jsapp/js/account/organization/MemberRemoveModal.tsx
  jsapp/js/actions/mfaActions.ts
  jsapp/js/alertify.ts
  jsapp/js/components/processing/processingActions.ts
  jsapp/js/global.d.ts
Labels: Front end

#5529 feat(activityLogs): handle modify-qa-data action in UI
  jsapp/js/components/activity/activity.constants.ts
Labels: Front end

#5461 chore(SuperuserStats): remove obsolete report - users count by organization TASK-1329
  kobo/apps/superuser_stats/tasks.py
  kobo/apps/superuser_stats/templates/superuser_stats_change_list.html
  kobo/apps/superuser_stats/urls.py
  kobo/apps/superuser_stats/views.py
Labels: Back end

#5548 fix(Frontend) update android instructions TASK-1563
  jsapp/js/components/formLanding.js
Labels: Front end

#5539 feat(permissions): incomplete permission removal with “Removed shared project” TASK-1494
  kpi/tests/api/v2/test_api_asset_permission_assignment.py
  kpi/views/v2/asset_permission_assignment.py
Labels: API, Back end

#5550 fix(projectTransfer)!: fix incorrect in-app message for project transfers
  kobo/apps/help/serializers.py
Labels: Back end

#5547 fix(organizations): adjust loading process for invite responses TASK-1602
  jsapp/js/account/organization/invites/OrgInviteModal.tsx
  jsapp/js/projects/universalProjectsRoute.tsx
Labels: Front end

#5545 fix(invites): display invite accepted banner for users who join another organization TASK-1601
  jsapp/js/account/organization/invites/OrgInviteAcceptedBanner.tsx
  jsapp/js/hooks/useSafeUsernameStorageKey.ts
  jsapp/js/projects/universalProjectsRoute.tsx
Labels: Front end

#5554 fix(billing): plan page always redirecting to settings (BACKPORT #5440)
  jsapp/js/account/plans/plan.component.tsx
Labels: Front end

#5551 fix(projectTransfer)!: fix asset visibility issue when user joins another organization
  kpi/filters.py
  kpi/tests/test_assets.py
Labels: Back end

#5555 fix(billing): remove indent of last item in nlp add-ons dropdown TASK-15
  jsapp/js/account/addOns/addOnList.module.scss
Labels: Front end

#5556 fix(billing): expand add-on section to full page width TASK-14
  jsapp/js/account/addOns/addOnList.module.scss
  jsapp/js/account/addOns/oneTimeAddOnRow.component.tsx
Labels: Front end

#5553 fix(organizations): keep invite acceptance loading spinner in 'accept' button TASK-1603
  jsapp/js/account/organization/invites/OrgInviteModal.tsx
Labels: Front end

#5544 feat(massEmail): create new models for mass email TASK-751
  kobo/apps/mass_emails/__init__.py
  kobo/apps/mass_emails/admin.py
  kobo/apps/mass_emails/apps.py
  kobo/apps/mass_emails/migrations/0001_initial.py
  kobo/apps/mass_emails/migrations/__init__.py
  kobo/apps/mass_emails/models.py
  kobo/apps/mass_emails/signals.py
  kobo/apps/mass_emails/tests.py
  kobo/apps/mass_emails/views.py
  kobo/settings/base.py
Labels: Back end

#5560 chore(frontend): delete xlform_with_deps
  jsapp/js/libs/xlform_with_deps.js
Labels: Front end

#5552 feat(organizations): show subscription plan in organization view TASK-1605
  kobo/apps/organizations/admin/organization.py
  kobo/apps/organizations/models.py
Labels: Back end
