Repository kobotoolbox/kpi, pull requests merged in 2025-10, with the labels that each got.

#6316 ci(releases): run version even if a test fails DEV-1109
  .github/workflows/release-2-stabilize.yml
Labels: workflow

#6317 ci(npm): assert up to date package-lock.json DEV-1109
  .github/workflows/npm-test.yml
  package-lock.json
  scripts/ci_locally.sh
Labels: Front end

#6309 test(storybook): handle useOrganizationAssumed DEV-873
  jsapp/js/account/DeleteAccountBanner.stories.tsx
  jsapp/js/endpoints/me.mocks.ts
  jsapp/js/endpoints/organization.mocks.ts
Labels: Front end

#6319 fix(swaggerUI): restore search bar functionality with collapsed tags
  kpi/static/js/swagger/swagger-smart-search.js
Labels: Front end, documentation

#6320 feat(api): add basic HTML renderer to API endpoints
  kobo/apps/audit_log/views.py
  kobo/apps/organizations/views.py
  kobo/settings/base.py
  kpi/negotiation.py
  kpi/renderers.py
  kpi/static/js/swagger/swagger-smart-search.js
  kpi/templates/renderers/basic.html
  kpi/urls/router_api_v2.py
  kpi/views/v2/asset.py
  kpi/views/v2/data.py
Labels: API, Back end

#6325 fix(api): respect the rendering format when it is provided DEV-1115
  kobo/settings/base.py
  kpi/negotiation.py
  kpi/tests/api/v2/test_api_renderers.py
Labels: API, Back end

#6315 fix(api): make MemberListResponse.invite nullable DEV-1093
  jsapp/js/api/models/memberListResponse.ts
  jsapp/js/api/models/memberListResponseInvite.ts
  kobo/apps/organizations/serializers.py
  kobo/apps/organizations/tests/test_organization_members_api.py
  kpi/schema_extensions/v2/members/serializers.py
  static/openapi/schema_v2.json
  static/openapi/schema_v2.yaml
Labels: Back end, documentation

#6314 fix(openApi): reuse MemberRoleEnum and InviteResponse DEV-1092
  jsapp/js/api/models/memberListResponse.ts
  jsapp/js/api/models/memberListResponseInvite.ts
  jsapp/js/api/models/memberListResponseInviteInviteeRole.ts
  jsapp/js/api/models/memberListResponseInviteStatus.ts
  kobo/apps/organizations/serializers.py
  kobo/apps/organizations/tests/test_organization_members_api.py
  kpi/schema_extensions/v2/members/extensions.py
  kpi/schema_extensions/v2/members/fields.py
  kpi/schema_extensions/v2/members/serializers.py
  static/openapi/schema_v2.json
  static/openapi/schema_v2.yaml
Labels: Back end, documentation

#6331 chores(openAPI): update HTML template title and text body
  kpi/renderers.py
  kpi/templates/renderers/basic.html
Labels: API

#6332 ci(releases): don't spam non-release branches DEV-1127
  .github/workflows/release-2-stabilize.yml
Labels: workflow

#6258 feat(dataCollectors): allow DCs access to read-only OpenRosa endpoints DEV-788
  kobo/apps/openrosa/apps/api/tests/fixtures/formList_for_dc.xml
  kobo/apps/openrosa/apps/api/tests/fixtures/formList_with_both_for_dcs.xml
  kobo/apps/openrosa/apps/api/tests/viewsets/test_xform_list_api.py
  kobo/apps/openrosa/apps/api/viewsets/xform_list_api.py
  kobo/apps/openrosa/apps/main/urls.py
  kobo/apps/openrosa/docs/api/v2/formlist/data_collector.md
  kobo/apps/openrosa/docs/api/v2/manifest/data_collector.md
  kobo/apps/openrosa/libs/serializers/xform_serializer.py
  kobo/apps/openrosa/libs/utils/middleware.py
  kpi/utils/spectacular_processing.py
Labels: Back end

#6337 feat(dataCollectors): improve Django Admin UX for data collector groups DEV-920
  kobo/apps/data_collectors/admin.py
Labels: Back end
