Repository kobotoolbox/kpi, pull requests merged in 2025-03, with the labels that each got.

#5564 fix(openRosa): correct project lookup fallback between OpenRosa and KPI TASK-1645
  kobo/apps/openrosa/apps/logger/models/xform.py
  kobo/apps/openrosa/apps/logger/tests/models/test_xform.py
Labels: Back end

#5559 fix(NLP): missing suggested language in language selector DEV-17
  jsapp/js/components/languages/languageSelector.tsx
Labels: Front end

#5565 chore(trashBin): add management command to fix partially restored projects
  kobo/apps/trash_bin/management/__init__.py
  kobo/apps/trash_bin/management/commands/__init__.py
  kobo/apps/trash_bin/management/commands/fix_xform_not_put_back_from_trash.py
Labels: Back end

#5561 fix(organizations): use correct teams MMO label in invite feature TASK-1644
  jsapp/js/account/organization/InviteModal.tsx
  jsapp/js/account/organization/MembersRoute.tsx
Labels: Front end

#5562 feat(massEmail): query for users reaching their maximum storage limit TASK-1454
  kobo/apps/mass_emails/migrations/0002_alter_massemailconfig_query.py
  kobo/apps/mass_emails/models.py
  kobo/apps/mass_emails/tests.py
  kobo/apps/mass_emails/tests/__init__.py
  kobo/apps/mass_emails/tests/test_usage_limit_user_queries.py
  kobo/apps/mass_emails/user_queries.py
  kobo/apps/stripe/tests/test_organization_usage.py
  kobo/apps/stripe/tests/utils.py
  kobo/apps/stripe/utils.py
  kpi/tests/api/v2/test_api_service_usage.py
  kpi/tests/test_usage_calculator.py
  kpi/utils/usage_calculator.py
Labels: Back end

#5571 fix(frontend): unable to access "Data" and "Settings" pages TASK-20
  jsapp/js/components/map/map.js
Labels: bug-fix, Front end

#5543 feat(permissions): use `delete-all` permissions endpoint on frontend TASK-1494
  jsapp/js/actions/permissions.js
  jsapp/js/assetQuickActions.tsx
  jsapp/js/components/permissions/userPermissionRow.component.tsx
  jsapp/js/dataInterface.ts
  kpi/views/v2/asset_permission_assignment.py
Labels: bug-fix, Front end

#5569 feat(massEmail): query for identifying inactive users based on login, form activity, and submissions TASK-1581
  kobo/apps/mass_emails/migrations/0003_alter_massemailconfig_query.py
  kobo/apps/mass_emails/models.py
  kobo/apps/mass_emails/tests/test_user_inactive_query.py
  kobo/apps/mass_emails/user_queries.py
Labels: Back end

#5579 fix(stripe): only import Product when stripe is enabled
  kobo/apps/stripe/tests/test_organization_usage.py
  kobo/apps/stripe/utils.py
Labels: Back end

#5581 fix(assets): do not update date_modified when viewing asset page TASK-1672
  kpi/deployment_backends/base_backend.py
  kpi/deployment_backends/openrosa_backend.py
  kpi/tests/test_deployment_backends.py
Labels: Back end

#5572 feat(massEmails): query for users approaching submission limits TASK-1579
  kobo/apps/mass_emails/migrations/0004_add_submission_to_queries.py
  kobo/apps/mass_emails/models.py
  kobo/apps/mass_emails/tests/test_usage_limit_user_queries.py
  kobo/apps/mass_emails/user_queries.py
  kobo/apps/organizations/utils.py
  kobo/apps/stripe/tests/test_organization_usage.py
  kobo/apps/stripe/utils.py
  kpi/tests/test_usage_calculator.py
  kpi/utils/usage_calculator.py
Labels: Back end

#5586 refactor(billing): remove unused UpdateBadge component DEV-21
  jsapp/js/account/addOns/updateBadge.component.tsx
Labels: Front end

#5582 fix(abstractTimestampedModel): restore `date_modified` saving behavior
  kobo/apps/accounts/mfa/models.py
  kobo/apps/accounts/mfa/signals.py
  kobo/apps/long_running_migrations/models.py
  kobo/apps/openrosa/apps/logger/utils/instance.py
  kobo/apps/project_ownership/models/transfer.py
  kobo/apps/trash_bin/tasks.py
  kpi/deployment_backends/openrosa_backend.py
  kpi/models/abstract_models.py
  kpi/models/asset.py
  kpi/models/asset_file.py
  kpi/tests/test_abstract_timestamped_model.py
Labels: Back end

#5589 feat(organization): allow organization ownership transfer from Admin UI
  kobo/apps/organizations/admin/organization_owner.py
  kobo/apps/organizations/admin/organization_user.py
  kobo/apps/organizations/static/admin/js/organization_user_autocomplete.js
Labels: Back end

#5575 feat(attachments): add xform and user fields to Attachment model TASK-927
  jsapp/js/components/map/map.js
  kobo/apps/openrosa/apps/logger/migrations/0042_attachment_user_attachment_xform.py
  kobo/apps/openrosa/apps/logger/models/attachment.py
  kobo/apps/openrosa/apps/logger/tests/models/test_attachment.py
Labels: Back end

#5576 feat(attachments): add date_created and date_modified fields to Attachment model TASK-1533
  kobo/apps/openrosa/apps/logger/migrations/0043_attachment_date_created_attachment_date_modified.py
  kobo/apps/openrosa/apps/logger/models/attachment.py
Labels: Back end

#5592 test(organization): fix linting and wrong previous merge
  kobo/apps/organizations/static/admin/js/organization_user_autocomplete.js
Labels: Front end

#5580 feat(attachments): add KPI UidField to Attachment model TASK-1523
  kobo/apps/openrosa/apps/logger/migrations/0044_attachment_uid.py
  kobo/apps/openrosa/apps/logger/models/attachment.py
  kobo/apps/openrosa/apps/logger/tests/models/test_attachment.py
Labels: Back end

#5577 feat(attachments): create query file for removing attachments and a way to test it TASK-570 TASK-572
  jsapp/js/api.endpoints.ts
  jsapp/js/attachments/AttachmentActionsDropdown.mocks.ts
  jsapp/js/attachments/AttachmentActionsDropdown.module.scss
  jsapp/js/attachments/AttachmentActionsDropdown.stories.tsx
  jsapp/js/attachments/AttachmentActionsDropdown.tsx
  jsapp/js/attachments/attachmentsQuery.ts
  jsapp/js/components/submissions/submissionDataTable.tsx
  jsapp/js/dataInterface.ts
  jsapp/js/featureFlags.ts
Labels: Front end

#5598 ci: fix unit test (one more time) for cancelled plan last month
  kobo/apps/stripe/tests/test_organization_usage.py
Labels: bug-fix, Back end

#5597 refactor(attachments): simplify using arrow functions TASK-572
  jsapp/js/attachments/AttachmentActionsDropdown.tsx
Labels: Front end

#5602 fix(frontend): use kobo default line-height again DEV-22
  jsapp/js/app.jsx
  jsapp/js/main.js
  jsapp/js/theme/kobo/index.ts
Labels: Front end

#5603 chore(frontend): remove unused getSubmissionsQuery function
  jsapp/js/dataInterface.ts
Labels: Front end

#5599 feat(attachments): add download and delete buttons TASK-571
  jsapp/js/actions.d.ts
  jsapp/js/attachments/AttachmentActionsDropdown.tsx
  jsapp/js/components/common/audioPlayer.scss
  jsapp/js/components/common/audioPlayer.tsx
  jsapp/js/components/processing/sidebar/processingSidebar.tsx
  jsapp/js/components/processing/sidebar/sidebarSubmissionMedia.tsx
  jsapp/js/components/processing/singleProcessingStore.ts
  jsapp/js/components/submissions/mediaCell.scss
  jsapp/js/components/submissions/mediaCell.tsx
  jsapp/js/components/submissions/submissionDataTable.scss
  jsapp/js/components/submissions/submissionDataTable.tsx
  jsapp/js/components/submissions/submissionModal.tsx
  jsapp/js/components/submissions/submissionUtils.ts
  jsapp/js/components/submissions/table.tsx
  jsapp/js/components/submissions/tableBulkCheckbox.tsx
  jsapp/js/components/submissions/tableConstants.ts
  jsapp/js/components/submissions/tableMediaPreview.js
Labels: Front end

#5604 feat(massEmail): add admin action to enqueue mass email records for scheduled sending TASK-1691
  kobo/apps/mass_emails/admin.py
  kobo/apps/mass_emails/migrations/0005_add_related_name_for_massemailjob_and_massemailrecord.py
  kobo/apps/mass_emails/models.py
  kobo/apps/mass_emails/tasks.py
  kobo/apps/mass_emails/tests/admin/__init__.py
  kobo/apps/mass_emails/tests/admin/test_enqueue_mass_email_records.py
Labels: Back end

#5606 fix(billing): improve default free plan identification TASK-1702
  jsapp/js/account/stripe.api.ts
  kobo/apps/stripe/tests/test_organization_usage.py
  kobo/apps/stripe/tests/utils.py
  kobo/apps/stripe/utils.py
Labels: Back end, Front end

#5609 fix(accessLogs): button spacing
  jsapp/js/account/security/accessLogs/accessLogsSection.component.tsx
  jsapp/js/account/security/securityRoute.module.scss
Labels: Front end

#5616 fix(export): restore supplement details columns with (nested) groups
  dependencies/pip/dev_requirements.txt
  dependencies/pip/requirements.in
  dependencies/pip/requirements.txt
Labels: CRITICAL, Back end

#5617 fix(longRunningMigration): fix crash in long-running migration when multiple submissions share the same UUID
  kobo/apps/long_running_migrations/jobs/0005_backfill_logger_instance_root_uuid.py
  kobo/apps/openrosa/apps/logger/management/commands/clean_duplicated_submissions.py
Labels: bug-fix, Back end

#5621 fix(avatar): avoid initials shrinking
  jsapp/js/components/common/avatar.module.scss
Labels: Front end

#5623 fix(organizations): projects of users with no previous organization were not transferred to a new one TASK-1716
  kobo/apps/organizations/admin/organization.py
Labels: Back end

#5624 chore(projectOwnershipTransfer): Remove stale reference to renamed Celery task TASK-1718
  kobo/apps/project_ownership/migrations/0005_remove_deprecated_mark_stuck_tasks_as_failed_task.py
Labels: Back end

#5618 fix: add activity log implementation into release branch 2.025.02 TASK-1714
  jsapp/js/api.endpoints.ts
  jsapp/js/components/activity/activity.constants.ts
  jsapp/js/components/activity/activityLogs.query.ts
  jsapp/js/components/activity/activityMessage.component.tsx
  jsapp/js/components/activity/formActivity.tsx
  kobo/apps/audit_log/tests/api/v2/test_api_audit_log.py
  kobo/apps/audit_log/views.py
  kpi/migrations/0064_create_projecthistorylogexporttask.py
  kpi/models/import_export_task.py
  kpi/tests/test_access_logs_export_task.py
  kpi/tests/test_audit_logs_export_task.py
  kpi/utils/data_exports.py
Labels: Back end, Front end

#5574 feat(massEmail): create/register celery tasks mass emails TASK-750
  .gitignore
  kobo/apps/mass_emails/admin.py
  kobo/apps/mass_emails/tasks.py
  kobo/apps/mass_emails/tests/test_celery_tasks.py
  kobo/settings/base.py
Labels: Back end

#5625 fix(NLP): correct paths for grouped questions
  jsapp/js/components/submissions/submissionUtils.ts
Labels: CRITICAL, Front end

#5611 feat(gallery): handle deleted attachments TASK-566
  jsapp/js/components/formGallery/formGallery.component.scss
  jsapp/js/components/formGallery/formGallery.component.tsx
Labels: Front end

#5612 feat(nlp): handle deleted audiofile TASK-566
  jsapp/js/components/processing/sidebar/sidebarSubmissionMedia.module.scss
  jsapp/js/components/processing/sidebar/sidebarSubmissionMedia.tsx
Labels: Front end

#5622 feat(dataview): handle deleted attachments TASK-566
  jsapp/js/components/submissions/submissionDataTable.tsx
Labels: Front end

#5605 feat(attachments): handle deleted attachments in repeat groups TASK-933
  jsapp/js/attachments/AttachmentActionsDropdown.mocks.ts
  jsapp/js/components/submissions/RepeatGroupCell.module.scss
  jsapp/js/components/submissions/RepeatGroupCell.tsx
  jsapp/js/components/submissions/submissionModal.tsx
  jsapp/js/components/submissions/submissionUtils.tsx
  jsapp/js/components/submissions/table.tsx
  jsapp/js/dataInterface.ts
Labels: Front end

#5619 feat(datatable): handle deleted audio attachment TASK-566
  jsapp/js/components/submissions/audioCell.tsx
Labels: Front end

#5620 feat(datatable): handle deleted file attachment TASK-566
  jsapp/js/attachments/deletedAttachment.component.tsx
  jsapp/js/components/submissions/mediaCell.tsx
Labels: Front end

#5627 test(nlp): getSubmissionDisplayData with nested groups
  jsapp/js/components/submissions/submissionUtils.mocks.es6
  jsapp/js/components/submissions/submissionUtils.tests.es6
  jsapp/js/components/submissions/submissionUtils.ts
Labels: Front end

#5613 perf(attachments): backfill attachments in chunks to optimize queries TASK-1534
  kobo/apps/long_running_migrations/jobs/0007_backfill_attachment_model.py
  kobo/apps/openrosa/apps/logger/models/attachment.py
Labels: Back end

#5628 fix(massEmails): Use default plan name in templates TASK-1712
  kobo/apps/mass_emails/tasks.py
  kobo/apps/stripe/tests/test_utils.py
  kobo/apps/stripe/utils.py
Labels: Back end

#5614 refactor(attachments): make Attachment inherit from `AbstractTimeStampedModel` TASK-1681
  kobo/apps/openrosa/apps/logger/models/attachment.py
Labels: Back end

#5615 refactor(attachments): enforce non-nullable uid on Attachment model TASK-1680
  kobo/apps/openrosa/apps/logger/models/attachment.py
Labels: Back end

#5629 feat(nlp): disable ASR for deleted attachment TASK-573
  jsapp/js/components/processing/sidebar/sidebarSubmissionMedia.tsx
  jsapp/js/components/processing/transcript/stepConfig.component.tsx
  jsapp/js/components/processing/transcript/stepConfigAuto.component.tsx
  jsapp/js/components/processing/transcript/transcript.utils.ts
  jsapp/js/components/processing/translations/stepConfig.component.tsx
  jsapp/js/components/processing/transxAutomaticButton.tsx
Labels: Front end

#5638 chore(frontend): put back removed storybook script
  package.json
Labels: Front end

#5639 fix(massEmails): fix plan name
  kobo/apps/mass_emails/tasks.py
  kobo/apps/mass_emails/tests/test_celery_tasks.py
  kobo/apps/stripe/tests/test_stripe_utils.py
  kobo/apps/stripe/tests/test_utils.py
  kobo/apps/stripe/tests/utils.py
  kobo/apps/stripe/utils.py
Labels: Back end

#5635 refactor(trashBin): standardize status toggling via abstract base method TASK-1525
  hub/admin/extend_user.py
  kobo/apps/trash_bin/admin.py
  kobo/apps/trash_bin/constants.py
  kobo/apps/trash_bin/migrations/0004_attachmenttrash.py
  kobo/apps/trash_bin/models/__init__.py
  kobo/apps/trash_bin/models/account.py
  kobo/apps/trash_bin/models/attachment.py
  kobo/apps/trash_bin/models/project.py
  kobo/apps/trash_bin/tests/test_utils.py
  kobo/apps/trash_bin/type_aliases.py
  kobo/apps/trash_bin/utils.py
  kpi/serializers/v2/asset.py
Labels: Back end
