Repository kobotoolbox/kpi, pull requests merged in 2025-05, with the labels that each got.

#5727 perf(projectOwnershipTransfer): optimize database queries to retrieve project names faster in Admin UI
  kobo/apps/project_ownership/admin.py
  kobo/apps/project_ownership/models/invite.py
Labels: Back end

#5729 fix(submissions): fix media question parsing bug causing silent data loss with appearance attribute
  kobo/apps/openrosa/apps/logger/tests/test_parsing.py
  kobo/apps/openrosa/apps/logger/xform_instance_parser.py
  kobo/apps/openrosa/apps/main/tests/fixtures/signature/project_with_ref_after.xml
  kobo/apps/openrosa/apps/main/tests/fixtures/signature/project_with_ref_before.xml
Labels: Back end

#5720 test(projectHistory): FormActivity stories DEV-100
  .storybook/main.js
  jsapp/js/components/activity/FormActivity.stories.tsx
  jsapp/js/components/activity/activity.constants.ts
  jsapp/js/components/activity/activityLogs.query.ts
  jsapp/js/components/activity/activityMessage.component.tsx
  jsapp/js/endpoints/assetHistory.mock.ts
  jsapp/js/endpoints/assetHistoryActions.mock.ts
  jsapp/js/endpoints/languages.mock.ts
  jsapp/js/utils.ts
  package-lock.json
  package.json
Labels: Front end

#5730 fix(trashBin): prevent restarter from restarting tasks still in grace period
  kobo/apps/trash_bin/tasks.py
  kobo/apps/trash_bin/tests/test_utils.py
Labels: Back end

#5731 fix(mongoSync): fix instance logging
  kobo/apps/openrosa/libs/utils/logger_tools.py
Labels: Back end

#5732 fix(organizations): skip stripe-related tests in no-stripe testing DEV-242
  kobo/apps/organizations/tests/test_organizations_api.py
  kobo/apps/stripe/tests/test_organization_usage.py
Labels: Back end

#5686 feat(attachments): update storage counters when attachments are moved to or from trash TASK-590
  kobo/apps/openrosa/apps/logger/utils/attachment.py
  kobo/apps/trash_bin/models/attachment.py
  kobo/apps/trash_bin/tests/test_utils.py
Labels: Back end

#5728 perf(mongoSync): speed up mongo sync
  kobo/apps/openrosa/apps/logger/models/xform.py
  kobo/apps/openrosa/apps/logger/xform_instance_parser.py
  kobo/apps/openrosa/apps/viewer/models/parsed_instance.py
  kobo/apps/openrosa/apps/viewer/tests/test_remongo.py
  kobo/apps/openrosa/libs/utils/logger_tools.py
Labels: Back end

#5722 docs(api): adding API endpoints for access-logs in KPI documentation TASK-1788
  kobo/apps/__init__.py
  kobo/apps/audit_log/__init__.py
  kobo/apps/audit_log/docs/api/v2/access_logs/exports/create.md
  kobo/apps/audit_log/docs/api/v2/access_logs/exports/list.md
  kobo/apps/audit_log/docs/api/v2/access_logs/list.md
  kobo/apps/audit_log/docs/api/v2/access_logs/me/exports/create.md
  kobo/apps/audit_log/docs/api/v2/access_logs/me/exports/list.md
  kobo/apps/audit_log/docs/api/v2/access_logs/me/list.md
  kobo/apps/audit_log/schema_extensions/__init__.py
  kobo/apps/audit_log/schema_extensions/v2/__init__.py
  kobo/apps/audit_log/schema_extensions/v2/access_logs/__init__.py
  kobo/apps/audit_log/schema_extensions/v2/access_logs/extensions.py
  kobo/apps/audit_log/schema_extensions/v2/access_logs/fields.py
  kobo/apps/audit_log/schema_extensions/v2/access_logs/serializers.py
  kobo/apps/audit_log/views.py
  kobo/apps/long_running_migrations/constants.py
  kobo/apps/long_running_migrations/jobs/0009_backfill_attachment_model.py
  kobo/apps/openrosa/apps/logger/management/commands/clean_duplicated_submissions.py
  kpi/migrations/0065_alter_asset_search_field.py
  kpi/models/asset.py
  kpi/permissions.py
  kpi/typing_aliases.py
  kpi/utils/schema_extensions/__init__.py
  kpi/utils/schema_extensions/extensions.py
  kpi/utils/schema_extensions/markdown.py
  kpi/utils/schema_extensions/response.py
Labels: API, Back end, documentation

#5740 fix(massEmails): fix 500 from usage queries
  kobo/apps/mass_emails/user_queries.py
Labels: Back end

#5739 docs(api): adding API endpoints for asset-snapshots in KPI documentation TASK-1791
  kobo/apps/__init__.py
  kpi/docs/__init__.py
  kpi/docs/api/v2/asset_snapshots/create.md
  kpi/docs/api/v2/asset_snapshots/delete.md
  kpi/docs/api/v2/asset_snapshots/list.md
  kpi/docs/api/v2/asset_snapshots/preview.md
  kpi/docs/api/v2/asset_snapshots/retrieve.md
  kpi/docs/api/v2/asset_snapshots/xform.md
  kpi/docs/api/v2/asset_snapshots/xml_with_disclaimer.md
  kpi/docs/api/v2/openrosa/form_list.md
  kpi/docs/api/v2/openrosa/manifest.md
  kpi/docs/api/v2/openrosa/submission.md
  kpi/schema_extensions/imports.py
  kpi/schema_extensions/v2/asset_snapshots/extensions.py
  kpi/schema_extensions/v2/asset_snapshots/fields.py
  kpi/schema_extensions/v2/asset_snapshots/serializers.py
  kpi/schema_extensions/v2/openrosa/extensions.py
  kpi/schema_extensions/v2/openrosa/fields.py
  kpi/schema_extensions/v2/openrosa/serializers.py
  kpi/typing_aliases.py
  kpi/utils/schema_extensions/response.py
  kpi/views/v2/asset_snapshot.py
Labels: API, Back end, documentation

#5743 feat(massEmails): add 80% queries
  kobo/apps/mass_emails/models.py
  kobo/apps/mass_emails/user_queries.py
Labels: Back end

#5745 docs(api): adding correct URL fields to access-logs and asset-snapshots endpoints TASK-1724
  kobo/apps/audit_log/schema_extensions/v2/access_logs/extensions.py
  kobo/apps/audit_log/schema_extensions/v2/access_logs/fields.py
  kobo/apps/audit_log/schema_extensions/v2/access_logs/serializers.py
  kpi/schema_extensions/v2/asset_snapshots/extensions.py
  kpi/schema_extensions/v2/asset_snapshots/fields.py
  kpi/schema_extensions/v2/asset_snapshots/serializers.py
  kpi/schema_extensions/v2/openrosa/extensions.py
  kpi/schema_extensions/v2/openrosa/fields.py
  kpi/schema_extensions/v2/openrosa/serializers.py
Labels: API, Back end, documentation

#5741 fix(projectTransfer): reset legacy project identifier to KPI identifier on transfer conflict DEV-253
  kobo/apps/project_ownership/models/transfer.py
  kobo/apps/project_ownership/tests/api/v2/test_api.py
  kpi/deployment_backends/base_backend.py
  kpi/deployment_backends/openrosa_backend.py
Labels: Back end

#5738 feat(attachments): update admin model to support attachments in trash bin TASK-1546
  kobo/apps/audit_log/migrations/0015_alter_auditlog_log_type.py
  kobo/apps/audit_log/models.py
  kobo/apps/trash_bin/admin.py
  kobo/apps/trash_bin/tests/admin/__init__.py
  kobo/apps/trash_bin/tests/admin/test_attachment_trash_admin.py
  kobo/apps/trash_bin/tests/test_attachment_trash_storage.py
  kobo/apps/trash_bin/tests/test_utils.py
  kobo/apps/trash_bin/utils/attachment.py
  kobo/apps/trash_bin/utils/trash.py
Labels: Back end

#5751 fix(djangoAdmin): make search functional again in admin interface
  hub/admin/extend_user.py
  kobo/apps/openrosa/apps/logger/management/commands/clean_duplicated_submissions.py
Labels: Back end

#5742 docs(api): add README for API documentation setup and usage
  README.md
  docs/README.md
Labels: API, Back end, documentation

#5753 fix(openRosa): list anonymous projects manageable by user
  kobo/apps/openrosa/apps/api/tests/viewsets/test_user.py
  kobo/apps/openrosa/apps/api/tests/viewsets/test_xform_list_api.py
  kobo/apps/openrosa/apps/api/viewsets/xform_list_api.py
Labels: API, Back end

#5755 fix:(reports): Fix infinite reloading failed report DEV-265
  jsapp/js/components/reports/reports.tsx
Labels: Front end

#5749 docs(api): adding API endpoints for asset_subscriptions in KPI documentation TASK-1792
  kpi/docs/api/v2/openrosa/preview.md
  kpi/docs/api/v2/openrosa/xform.md
  kpi/docs/api/v2/openrosa/xml_with_disclaimer.md
  kpi/views/docs/asset_subscription/asset_subscription_doc.py
Labels: API, Back end, documentation

#5733 refactor(attachments): bulk and single attachment deletion endpoints TASK-1822
  kpi/serializers/v2/attachment_bulk_delete.py
  kpi/serializers/v2/attachment_delete.py
  kpi/tests/api/v2/test_api_attachments.py
  kpi/tests/api/v2/test_api_attachments_delete_viewset.py
  kpi/urls/router_api_v2.py
  kpi/views/v2/attachment.py
  kpi/views/v2/attachment_bulk_delete.py
  kpi/views/v2/attachment_delete.py
Labels: Back end

#5762 docs(api): removed unnecessary markdown documentations TASK-1724
  kpi/docs/api/v2/asset_snapshots/list.md
  kpi/docs/api/v2/asset_subscriptions/list.md
Labels: API, Back end, documentation

#5761 docs(api): adding API endpoints for asset_usage in KPI documentation TASK-1793
  kpi/docs/api/v2/asset_usage/list.md
  kpi/schema_extensions/imports.py
  kpi/schema_extensions/v2/asset_usage/extensions.py
  kpi/schema_extensions/v2/asset_usage/fields.py
  kpi/schema_extensions/v2/asset_usage/serializers.py
  kpi/views/v2/asset_usage.py
Labels: API, Back end, documentation

#5759 docs(api): payload format validation - TASK-1724
  kpi/views/v2/asset_snapshot.py
  kpi/views/v2/user_asset_subscription.py
Labels: API, Back end, documentation

#5766 docs(api): API documentation code reformat TASK-1724
  kobo/apps/audit_log/schema_extensions/v2/access_logs/serializers.py
  kobo/apps/audit_log/views.py
  kpi/schema_extensions/v2/asset_snapshots/extensions.py
  kpi/schema_extensions/v2/asset_snapshots/fields.py
  kpi/schema_extensions/v2/asset_snapshots/serializers.py
  kpi/schema_extensions/v2/asset_subscriptions/serializers.py
  kpi/schema_extensions/v2/openrosa/serializers.py
  kpi/utils/schema_extensions/serializers.py
  kpi/views/v2/asset_snapshot.py
  kpi/views/v2/user_asset_subscription.py
Labels: API, Back end, documentation

#5763 docs(api): handle additional responses with drf-spectacular decators
  kpi/utils/schema_extensions/response.py
Labels: API, Back end

#5767 docs(api): handled oneOf TASK-1724
  kobo/apps/stripe/tests/test_organization_usage.py
  kpi/schema_extensions/__init__.py
  kpi/schema_extensions/v2/__init__.py
  kpi/schema_extensions/v2/asset_snapshots/__init__.py
  kpi/schema_extensions/v2/asset_snapshots/extensions.py
  kpi/schema_extensions/v2/asset_snapshots/schema.py
  kpi/schema_extensions/v2/asset_snapshots/serializers.py
  kpi/schema_extensions/v2/asset_subscriptions/__init__.py
  kpi/schema_extensions/v2/asset_subscriptions/fields.py
  kpi/schema_extensions/v2/asset_subscriptions/serializers.py
  kpi/schema_extensions/v2/asset_usage/__init__.py
  kpi/schema_extensions/v2/assets/__init__.py
  kpi/schema_extensions/v2/assets/extensions.py
  kpi/schema_extensions/v2/assets/fields.py
  kpi/schema_extensions/v2/assets/schema.py
  kpi/schema_extensions/v2/openrosa/__init__.py
  kpi/utils/schema_extensions/examples.py
  kpi/utils/schema_extensions/url_builder.py
  kpi/views/v2/asset_snapshot.py
Labels: API, Back end, documentation

#5768 fix(auth): improve validation on user profile updates
  kpi/serializers/current_user.py
  kpi/tests/api/test_api_current_user.py
Labels: API, Back end

#5770 test(billing): fix incorrect billing cycle end date when testing previous month
  kobo/apps/stripe/tests/test_organization_usage.py
Labels: Back end

#5687 fix(attachmentStorage): fix UserProfile storage counter to exclude soft-deleted XForms TASK-1777
  kobo/apps/openrosa/apps/logger/management/commands/update_attachment_storage_bytes.py
  kobo/apps/trash_bin/models/project.py
  kobo/apps/trash_bin/tests/test_utils.py
Labels: bug-fix, Back end

#5747 refactor(trashBin): unify status toggling inside `move_to_trash()` and `put_back()` for all trash models TASK-1826
  hub/admin/extend_user.py
  kobo/apps/trash_bin/admin.py
  kobo/apps/trash_bin/models/account.py
  kobo/apps/trash_bin/tests/test_attachment_trash_storage.py
  kobo/apps/trash_bin/tests/test_utils.py
  kobo/apps/trash_bin/type_aliases.py
  kobo/apps/trash_bin/utils/trash.py
  kpi/deployment_backends/openrosa_backend.py
  kpi/serializers/v2/asset.py
Labels: Back end

#5764 chore(frontend): .git-blame-ignore-revs for Biome DEV-269
  .git-blame-ignore-revs
Labels: Front end

#5750 build(storybook): upgrade to v9 DEV-260
  .storybook/main.js
  .storybook/preview.js
  jsapp/js/attachments/AttachmentActionsDropdown.stories.tsx
  jsapp/js/attachments/deletedAttachment.stories.tsx
  jsapp/js/components/activity/FormActivity.stories.tsx
  jsapp/js/components/common/ButtonNew.stories.tsx
  jsapp/js/components/common/Select.stories.tsx
  jsapp/js/components/common/SimpleTable.stories.tsx
  jsapp/js/components/common/actionIcon.stories.tsx
  jsapp/js/components/common/ariaText.stories.tsx
  jsapp/js/components/common/avatar.stories.tsx
  jsapp/js/components/common/badge.stories.tsx
  jsapp/js/components/common/checkbox.stories.tsx
  jsapp/js/components/common/diffValue.stories.tsx
  jsapp/js/components/common/icon.stories.tsx
  jsapp/js/components/common/inlineMessage.stories.tsx
  jsapp/js/components/common/koboDropdown.stories.tsx
  jsapp/js/components/common/koboRange.stories.tsx
  jsapp/js/components/common/koboSelect.stories.tsx
  jsapp/js/components/common/loader.stories.tsx
  jsapp/js/components/common/loadingOverlay.stories.tsx
  jsapp/js/components/common/loadingSpinner.stories.tsx
  jsapp/js/components/common/miniAudioPlayer.stories.tsx
  jsapp/js/components/common/modal.stories.tsx
  jsapp/js/components/common/multiCheckbox.stories.tsx
  jsapp/js/components/common/radio.stories.tsx
  jsapp/js/components/common/tabs.stories.tsx
  jsapp/js/components/common/textBox.stories.tsx
  jsapp/js/components/common/textInput.stories.tsx
  jsapp/js/components/common/tooltip.stories.tsx
  jsapp/js/components/exportToEmailButton/exportToEmailButton.stories.tsx
  jsapp/js/components/languages/languageSelector.stories.tsx
  jsapp/js/components/languages/regionSelector.stories.tsx
  jsapp/js/components/modals/koboModal.stories.tsx
  jsapp/js/components/modals/koboPrompt.stories.tsx
  jsapp/js/query/queryClient.mock.tsx
  jsapp/js/universalTable/universalTable.stories.tsx
  package-lock.json
  package.json
Labels: Front end

#5756 fix(attachments): fix user profile counter bug on attachment deletion after project transfer TASK-1828
  kobo/apps/project_ownership/utils.py
  kobo/apps/trash_bin/tests/test_attachment_trash_storage.py
Labels: bug-fix, Back end

#5748 refactor(billing): standardize usage naming TASK-1827
  kobo/apps/mass_emails/tests/test_usage_limit_user_queries.py
  kobo/apps/mass_emails/user_queries.py
  kobo/apps/organizations/constants.py
  kobo/apps/organizations/types.py
  kobo/apps/stripe/constants.py
  kobo/apps/stripe/models.py
  kobo/apps/stripe/tests/test_one_time_addons_api.py
  kobo/apps/stripe/tests/test_stripe_utils.py
  kobo/apps/stripe/tests/utils.py
  kobo/apps/stripe/utils.py
  kobo/apps/trackers/tests/test_utils.py
  kobo/apps/trackers/utils.py
  kpi/tests/test_usage_calculator.py
  kpi/utils/usage_calculator.py
Labels: Back end

#5774 fix: backport of kpi#5768 to release 2.024.36
  .github/workflows/npm-test.yml
  .github/workflows/pytest.yml
  kpi/serializers/current_user.py
  kpi/tests/api/test_api_current_user.py
Labels: API, Back end

#5772 fix(longRunningMigration): do not block fresh installs with system checks DEV-272
  kobo/apps/long_running_migrations/app.py
  kobo/apps/long_running_migrations/tests/test_checks.py
Labels: Back end

#5775 doc: update `/me/` endpoint documentation
  kpi/views/current_user.py
Labels: documentation

#5765 feat(removingAttachments): use API instead of mocks TASK-1685
  jsapp/js/api.endpoints.ts
  jsapp/js/api.ts
  jsapp/js/attachments/AttachmentActionsDropdown.tsx
  jsapp/js/attachments/BulkDeleteMediaFiles.tsx
  jsapp/js/attachments/attachmentsQuery.ts
  jsapp/js/dataInterface.ts
Labels: Front end

#5776 fix(frontend): don't install playwright in dockerfile DEV-276
  Dockerfile
Labels: Front end

#5782 refactor(UniversalTable): use hardcoded mock data in stories DEV-277
  jsapp/js/universalTable/universalTable.mocks.tsx
  jsapp/js/universalTable/universalTable.stories.tsx
  package-lock.json
  package.json
Labels: Front end

#5760 feat(massEmails): prioritize recurring sends over one-time TASK-1697
  kobo/apps/mass_emails/models.py
  kobo/apps/mass_emails/tasks.py
  kobo/apps/mass_emails/tests/test_celery_tasks.py
Labels: Back end

#5784 fix(accounts): ensure anonymous user has uid
  scripts/create_anonymous_user.py
Labels: Back end

#5789 fix(storybook): make dates consistent in UniversalTable tests DEV-277
  jsapp/js/universalTable/universalTable.mocks.tsx
Labels: Front end

#5778 fix(billing): direct storage addon holders to Stripe for upgrade DEV-275
  jsapp/js/account/addOns/addOnList.component.tsx
  jsapp/js/account/addOns/addOnProductRow.component.tsx
  jsapp/js/router/requireAuth.tsx
Labels: Front end

#5781 ci(chromatic): run tests daily DEV-103
  .github/workflows/ci-daily.yml
  package-lock.json
  package.json
Labels: Front end

#5792 refactor(frontend): consistent mock files naming DEV-93
  jsapp/js/attachments/AttachmentActionsDropdown.stories.tsx
  jsapp/js/components/activity/FormActivity.stories.tsx
  jsapp/js/components/languages/languageSelector.stories.tsx
  jsapp/js/endpoints/assetHistory.mocks.ts
  jsapp/js/endpoints/assetHistoryActions.mocks.ts
  jsapp/js/endpoints/environment.mocks.ts
  jsapp/js/endpoints/languages.mocks.ts
  jsapp/js/query/queryClient.mocks.tsx
Labels: Front end

#5685 feat(billing): add xform pending_transfer flag (TASK-1638)
  kobo/apps/openrosa/apps/api/tests/viewsets/test_xform_submission_api.py
  kobo/apps/openrosa/apps/logger/migrations/0044_xform_add_pending_transfer.py
  kobo/apps/openrosa/apps/logger/models/instance.py
  kobo/apps/openrosa/apps/logger/models/xform.py
  kobo/apps/openrosa/libs/serializers/xform_serializer.py
  kobo/apps/project_ownership/models/transfer.py
  kpi/deployment_backends/base_backend.py
  kpi/deployment_backends/openrosa_backend.py
Labels: Back end

#5735 chore(cypress): remove code DEV-94
  .github/CODEOWNERS
  .gitignore
  cypress/README.md
  cypress/cypress.json
  cypress/cypress/fixtures/accounts.json
  cypress/cypress/fixtures/questions.json
  cypress/cypress/integration/delete.spec.js
  cypress/cypress/integration/project.spec.js
  cypress/cypress/integration/question.spec.js
  cypress/cypress/plugins/index.js
  cypress/cypress/support/commands.js
  cypress/cypress/support/index.js
  cypress/package-lock.json
  cypress/package.json
  jsapp/js/assetQuickActions.tsx
  jsapp/js/components/common/assetName.tsx
  jsapp/js/components/common/audioPlayer.tsx
  jsapp/js/components/common/button.tsx
  jsapp/js/components/common/checkbox.tsx
  jsapp/js/components/common/inlineMessage.tsx
  jsapp/js/components/common/koboDropdown.tsx
  jsapp/js/components/common/koboImage.tsx
  jsapp/js/components/common/koboRange.tsx
  jsapp/js/components/common/koboSelect.tsx
  jsapp/js/components/common/koboTagsInput.tsx
  jsapp/js/components/common/loadingSpinner.tsx
  jsapp/js/components/common/miniAudioPlayer.tsx
  jsapp/js/components/common/radio.tsx
  jsapp/js/components/common/textBox.stories.tsx
  jsapp/js/components/common/textBox.tsx
  jsapp/js/components/common/toggleSwitch.tsx
  jsapp/js/components/common/wrappedSelect.tsx
  jsapp/js/components/formLanding/formLanding.js
  jsapp/js/components/formSummary/formSummary.js
  jsapp/js/components/modalForms/projectSettings.js
  jsapp/js/components/modals/koboModal.tsx
  jsapp/js/components/modals/koboPrompt.tsx
  jsapp/js/components/submissions/tableMediaPreview.js
  jsapp/js/projects/projectViews/projectsFilterEditor.tsx
  jsapp/js/projects/projectsTable/projectsTableRow.tsx
  jsapp/js/utils.ts
  jsapp/xlform/src/view.choices.coffee
  jsapp/xlform/src/view.choices.templates.coffee
  jsapp/xlform/src/view.rowSelector.templates.coffee
  jsapp/xlform/src/view.surveyApp.templates.coffee
  kobo/settings/cypress.py
  kpi/management/commands/cypress_testserver.py
  kpi/utils/two_database_configuration_checker.py
Labels: Back end, Front end

#5793 feat(attachments): Add tests for `move_to_trash` and `put_back` support for `AttachmentTrash` TASK-1786
  kobo/apps/trash_bin/tests/test_utils.py
Labels: Back end

#5736 fix(permissions): sharing modal correctly reflects asset type in permissions labels DEV-255
  jsapp/js/components/permissions/permConstants.ts
  jsapp/js/components/permissions/sharingForm.component.tsx
  jsapp/js/components/permissions/userAssetPermsEditor.component.tsx
  jsapp/js/components/permissions/userPermissionRow.component.tsx
  jsapp/js/components/permissions/utils.ts
Labels: Front end

#5785 fix(permissions): make sharing form request permissions upon opening DEV-128
  jsapp/js/components/permissions/sharingForm.component.tsx
Labels: Front end

#5798 fix(permissions): uncheckable permission checkboxes DEV-266
  jsapp/js/components/permissions/userAssetPermsEditor.component.tsx
  jsapp/js/components/permissions/userAssetPermsEditor.tests.ts
  jsapp/js/components/permissions/userAssetPermsEditor.utils.ts
Labels: Front end

#5797 fix(billing): fix missing interval dropdown for "File Storage" add-on in some languages DEV-261
  jsapp/js/account/addOns/addOnList.component.tsx
  jsapp/js/account/addOns/oneTimeAddOnRow.component.tsx
Labels: Front end

#5796 feat(massEmails): enable recurring sends TASK-1693
  kobo/apps/mass_emails/admin.py
  kobo/apps/mass_emails/tasks.py
  kobo/apps/mass_emails/tests/admin/test_add_to_send.py
  kobo/apps/mass_emails/tests/admin/test_enqueue_mass_email_records.py
  kobo/apps/mass_emails/tests/test_celery_tasks.py
  kobo/settings/base.py
  kobo/settings/testing.py
Labels: Back end

#5788 feat(attachments): Update mongo documents to expose attachment deleted flag TASK-581
  kobo/apps/openrosa/apps/api/tests/viewsets/test_attachment_viewset.py
  kobo/apps/openrosa/apps/api/tests/viewsets/test_data_viewset.py
  kobo/apps/openrosa/apps/viewer/models/parsed_instance.py
  kobo/apps/trash_bin/admin.py
  kobo/apps/trash_bin/tests/admin/test_attachment_trash_admin.py
  kobo/apps/trash_bin/tests/test_attachment_trash_storage.py
  kobo/apps/trash_bin/tests/test_utils.py
  kpi/deployment_backends/openrosa_backend.py
  kpi/tests/api/v2/test_api_attachments_delete_viewset.py
  kpi/tests/mixins/__init__.py
  kpi/tests/mixins/create_asset_and_submission_mixin.py
Labels: Back end

#5803 test(projectHistoryLogs): backfill some unit tests DEV-109
  kobo/apps/audit_log/tests/test_models.py
Labels: Back end

#5806 refactor(billing): add organization service usage tests TASK-1833
  kobo/apps/organizations/tests/test_organizations_api.py
  kobo/apps/organizations/tests/test_organizations_service_usage_api.py
Labels: Back end
