Repository kobotoolbox/kpi, pull requests merged in 2025-08, with the labels that each got.

#6040 fix(urlPattern): prevent `drf-spectacular` URL route misinterpretation with complex regex
  kobo/apps/accounts/mixins.py
  kobo/apps/accounts/tests/test_social_account.py
  kobo/apps/accounts/urls.py
  kobo/apps/accounts/views.py
  kobo/apps/audit_log/models.py
  kobo/apps/audit_log/tests/test_project_history_logs.py
  kpi/schema_extensions/v2/openrosa/extensions.py
  kpi/tests/api/v1/test_api_asset_snapshots.py
  kpi/tests/api/v1/test_api_submissions.py
  kpi/tests/api/v2/test_api_asset_snapshots.py
  kpi/tests/api/v2/test_api_submissions.py
  kpi/tests/utils/mixins.py
  kpi/urls/__init__.py
  kpi/urls/router_api_v1.py
  kpi/urls/router_api_v2.py
  kpi/utils/schema_extensions/url_builder.py
  kpi/views/current_user.py
  kpi/views/v2/attachment.py
  kpi/views/v2/data.py
Labels: Back end

#6045 fix(activityLogs): export button correctly passes no payload DEV-833
  jsapp/js/components/activity/activityLogs.query.ts
Labels: Front end

#5885 docs(api): adding API endpoints for history in KPI documentation DEV-531
  kobo/apps/audit_log/__init__.py
  kobo/apps/audit_log/docs/api/v2/history/action.md
  kobo/apps/audit_log/docs/api/v2/history/export.md
  kobo/apps/audit_log/docs/api/v2/history/list.md
  kobo/apps/audit_log/schema_extensions/v2/history/__init__.py
  kobo/apps/audit_log/schema_extensions/v2/history/extensions.py
  kobo/apps/audit_log/schema_extensions/v2/history/fields.py
  kobo/apps/audit_log/schema_extensions/v2/history/serializers.py
  kobo/apps/audit_log/views.py
Labels: API, Back end, documentation

#6049 docs(deprecation): fix correct version for `v1` deprecation
  DEPRECATION.md
Labels: API, documentation

#6048 fix(termsOfService): add new `/api/v2/terms-of-service` endpoint to replace deprecated `sitewidemessage` API DEV-807
  jsapp/js/tos/tosForm.component.tsx
  kpi/serializers/v2/tos.py
  kpi/tests/api/test_api_environment.py
  kpi/tests/api/v2/test_api_tos.py
  kpi/urls/router_api_v2.py
  kpi/views/v2/tos.py
Labels: Back end

#5938 feat(attachments): Add celery task to auto delete excess attachments DEV-240
  kobo/apps/trash_bin/tasks/attachment.py
  kobo/apps/trash_bin/tests/storage_cleanup/test_attachment_cleanup.py
  kobo/settings/base.py
Labels: Back end

#6043 docs(api): adding API endpoints for email in KPI documentation DEV-831
  kobo/apps/accounts/docs/api/v2/email/create.md
  kobo/apps/accounts/docs/api/v2/email/list.md
  kobo/apps/accounts/extend_schemas/api/v2/email/serializers.py
  kobo/apps/accounts/views.py
Labels: API, Back end, documentation

#6057 fix(authorized_application): fix typo in urls DEV-848
  kpi/urls/__init__.py
Labels: Back end

#6058 docs(api): adding API endpoints for terms-of-service in KPI documentation DEV-844
  kpi/docs/api/v2/tos/list.md
  kpi/docs/api/v2/tos/retrieve.md
  kpi/schema_extensions/imports.py
  kpi/schema_extensions/v2/tos/__init__.py
  kpi/schema_extensions/v2/tos/extensions.py
  kpi/schema_extensions/v2/tos/fields.py
  kpi/schema_extensions/v2/tos/serializers.py
  kpi/utils/schema_extensions/url_builder.py
  kpi/views/v2/tos.py
Labels: API, Back end, documentation

#6047 docs(api): adding API endpoints for social in KPI documentation DEV-832
  kobo/apps/accounts/docs/api/v2/me/email/create.md
  kobo/apps/accounts/docs/api/v2/me/email/list.md
  kobo/apps/accounts/docs/api/v2/me/social/delete.md
  kobo/apps/accounts/docs/api/v2/me/social/list.md
  kobo/apps/accounts/docs/api/v2/me/social/retrieve.md
  kobo/apps/accounts/views.py
Labels: API, Back end, documentation

#5988 refactor(coffeeScript): fix DS0002 in model.rowDetails.skipLogic.coffee DEV-796
  jsapp/xlform/src/model.rowDetails.skipLogic.coffee
Labels: Front end, refactor

#6059 docs(api): exclude API endpoints for authorized-applications in KPI documentation DEV-845
  kpi/views/v1/authorized_application_user.py
  kpi/views/v2/authorized_application_user.py
Labels: API, Back end, documentation

#6039 feat(billing): disable/enable usage limit enforcement on frontend DEV-805
  jsapp/js/components/processing/transcript/stepConfig.component.tsx
  jsapp/js/components/processing/translations/stepConfig.component.tsx
  jsapp/js/endpoints/environment.mocks.ts
  jsapp/js/envStore.ts
Labels: Front end

#6061 chore(frontend): change package.json versions to use carets for all deps DEV-89
  package-lock.json
  package.json
Labels: dependencies, Front end

#6060 feat(projectOwnership): log errors in transferring attachments DEV-842
  kpi/fields/file.py
  kpi/tests/test_extended_file_field.py
Labels: Back end

#6062 chore(frontend): bump webpack-dev-server to 5.2.2
  package-lock.json
  package.json
Labels: dependencies, Front end

#6064 chore(frontend): delete unused source-map-loader
  package-lock.json
  package.json
Labels: dependencies, Front end

#6065 chore(deps): bum react-cookie from 4.0.1 to 8.0.1
  jsapp/js/stores.js
  package-lock.json
  package.json
Labels: dependencies, Front end

#6066 chore(deps): bump patch-package from 6.5.1 to 8.0.0
  package-lock.json
  package.json
Labels: dependencies, Front end

#6053 chore(permissions): clean up obsolete permissions code DEV-824
  kobo/apps/kobo_auth/models.py
  kobo/apps/openrosa/apps/api/permissions.py
  kobo/apps/openrosa/apps/api/tests/viewsets/test_data_viewset.py
  kobo/apps/openrosa/apps/api/tests/viewsets/test_metadata_viewset.py
  kobo/apps/openrosa/apps/api/tests/viewsets/test_xform_list_api.py
  kobo/apps/openrosa/apps/api/tests/viewsets/test_xform_submission_api.py
  kobo/apps/openrosa/apps/api/tests/viewsets/test_xform_viewset.py
  kobo/apps/openrosa/apps/api/tools.py
  kobo/apps/openrosa/apps/api/viewsets/briefcase_api.py
  kobo/apps/openrosa/apps/logger/management/commands/clean_duplicated_submissions_root_uuid.py
  kobo/apps/openrosa/apps/logger/migrations/0015_add_delete_data_permission.py
  kobo/apps/openrosa/apps/logger/models/xform.py
  kobo/apps/openrosa/apps/logger/tests/test_form_submission.py
  kobo/apps/openrosa/libs/constants.py
  kobo/apps/openrosa/libs/filters.py
  kobo/apps/openrosa/libs/permissions.py
  kobo/apps/openrosa/libs/serializers/metadata_serializer.py
  kobo/apps/openrosa/libs/serializers/note_serializer.py
  kobo/apps/openrosa/libs/utils/logger_tools.py
  kobo/apps/openrosa/libs/utils/user_auth.py
  kpi/deployment_backends/kc_access/utils.py
  kpi/mixins/object_permission.py
  kpi/models/asset.py
Labels: Back end

#5995 docs(api): refactor of drf_spectacular schema DEV-727
  kobo/apps/audit_log/views.py
  kobo/apps/hook/schema_extensions/v2/hooks/fields.py
  kobo/apps/hook/schema_extensions/v2/hooks/logs/fields.py
  kobo/apps/hook/serializers/v2/hook.py
  kobo/apps/hook/serializers/v2/hook_log.py
  kobo/apps/hook/views/v2/hook.py
  kobo/apps/hook/views/v2/hook_log.py
  kobo/apps/openrosa/apps/api/utils/rest_framework/views.py
  kobo/apps/openrosa/apps/api/viewsets/xform_list_api.py
  kobo/apps/openrosa/libs/serializers/xform_serializer.py
  kobo/apps/organizations/serializers.py
  kobo/apps/organizations/views.py
  kobo/apps/project_ownership/schema_extensions/v2/project_ownership/invites/serializers.py
  kobo/apps/project_ownership/views/invite.py
  kobo/apps/project_ownership/views/transfer.py
  kpi/docs/api/v2/data/enketo_edit.md
  kpi/docs/api/v2/data/enketo_view.md
  kpi/models/import_export_task.py
  kpi/schema_extensions/v2/asset_permission_assignments/extensions.py
  kpi/schema_extensions/v2/asset_subscriptions/extensions.py
  kpi/schema_extensions/v2/assets/extensions.py
  kpi/schema_extensions/v2/assets/fields.py
  kpi/schema_extensions/v2/data/extensions.py
  kpi/schema_extensions/v2/data/fields.py
  kpi/schema_extensions/v2/data/serializers.py
  kpi/schema_extensions/v2/export_settings/extensions.py
  kpi/schema_extensions/v2/files/schema.py
  kpi/schema_extensions/v2/organizations/extensions.py
  kpi/schema_extensions/v2/organizations/fields.py
  kpi/schema_extensions/v2/permissions/fields.py
  kpi/serializers/current_user.py
  kpi/serializers/v2/asset.py
  kpi/serializers/v2/permission.py
  kpi/tests/test_mock_data_exports.py
  kpi/urls/router_api_v2.py
  kpi/utils/schema_extensions/fields.py
  kpi/utils/schema_extensions/url_builder.py
  kpi/utils/spectacular_processing.py
  kpi/views/v1/export_task.py
  kpi/views/v1/import_task.py
  kpi/views/v2/asset.py
  kpi/views/v2/asset_counts.py
  kpi/views/v2/asset_export_settings.py
  kpi/views/v2/asset_file.py
  kpi/views/v2/asset_permission_assignment.py
  kpi/views/v2/asset_snapshot.py
  kpi/views/v2/asset_version.py
  kpi/views/v2/attachment.py
  kpi/views/v2/attachment_delete.py
  kpi/views/v2/data.py
  kpi/views/v2/export_task.py
  kpi/views/v2/import_task.py
  kpi/views/v2/paired_data.py
  kpi/views/v2/service_usage.py
Labels: API, Back end, documentation

#6051 refactor(api): add generic fields to schema and extensions DEV-762
  kobo/apps/audit_log/schema_extensions/v2/access_logs/extensions.py
  kobo/apps/audit_log/schema_extensions/v2/audit_logs/extensions.py
  kobo/apps/audit_log/schema_extensions/v2/history/extensions.py
  kobo/apps/audit_log/views.py
  kobo/apps/hook/schema_extensions/v2/hooks/extensions.py
  kobo/apps/hook/schema_extensions/v2/hooks/logs/extensions.py
  kobo/apps/project_ownership/schema_extensions/v2/project_ownership/invites/extensions.py
  kobo/apps/project_ownership/schema_extensions/v2/project_ownership/transfers/extensions.py
  kobo/apps/project_views/schema_extensions/v2/extensions.py
  kpi/models/import_export_task.py
  kpi/schema_extensions/v2/asset_attachments/extensions.py
  kpi/schema_extensions/v2/asset_permission_assignments/extensions.py
  kpi/schema_extensions/v2/asset_permission_assignments/schema.py
  kpi/schema_extensions/v2/asset_snapshots/extensions.py
  kpi/schema_extensions/v2/asset_usage/extensions.py
  kpi/schema_extensions/v2/assets/extensions.py
  kpi/schema_extensions/v2/assets/schema.py
  kpi/schema_extensions/v2/data/extensions.py
  kpi/schema_extensions/v2/data/serializers.py
  kpi/schema_extensions/v2/export_settings/extensions.py
  kpi/schema_extensions/v2/export_tasks/extensions.py
  kpi/schema_extensions/v2/files/extensions.py
  kpi/schema_extensions/v2/files/schema.py
  kpi/schema_extensions/v2/generic/__init__.py
  kpi/schema_extensions/v2/generic/schema.py
  kpi/schema_extensions/v2/imports/extensions.py
  kpi/schema_extensions/v2/invites/extensions.py
  kpi/schema_extensions/v2/me/extensions.py
  kpi/schema_extensions/v2/members/extensions.py
  kpi/schema_extensions/v2/organizations/extensions.py
  kpi/schema_extensions/v2/organizations/schema.py
  kpi/schema_extensions/v2/paired_data/extensions.py
  kpi/schema_extensions/v2/service_usage/extensions.py
  kpi/schema_extensions/v2/service_usage/schema.py
  kpi/schema_extensions/v2/users/extensions.py
  kpi/schema_extensions/v2/versions/extensions.py
  kpi/tests/test_mock_data_exports.py
  kpi/views/v1/export_task.py
  kpi/views/v1/import_task.py
  kpi/views/v2/asset_file.py
  kpi/views/v2/asset_permission_assignment.py
  kpi/views/v2/asset_snapshot.py
  kpi/views/v2/data.py
  kpi/views/v2/import_task.py
Labels: API, Back end, documentation

#6084 ci(backend): run biome for static files too DEV-862
  .github/filters.yml
  .github/workflows/biome.yml
  .github/workflows/ci-main.yml
  .github/workflows/ci-pr.yml
  .github/workflows/npm-test.yml
  .github/workflows/release-2-stabilize.yml
  .github/workflows/release-3-tag.yml
  biome.jsonc
Labels: workflow

#5801 fix(projects): "fields" selector uses same default display list as my projects route DEV-292
  jsapp/js/projects/projectViews/projectsFieldsSelector.tsx
  jsapp/js/projects/universalProjectsRoute.tsx
Labels: Front end

#6085 feat(docs): change status field type to enum DEV-869
  kobo/apps/project_ownership/schema_extensions/v2/project_ownership/invites/extensions.py
  kobo/apps/project_ownership/schema_extensions/v2/project_ownership/invites/fields.py
  kobo/apps/project_ownership/schema_extensions/v2/project_ownership/invites/serializers.py
Labels: API, Back end, documentation

#5800 fix(formbuilder): remove double prompt when existing formbuilder with changes DEV-175 DEV-33
  jsapp/js/editorMixins/editableForm.js
Labels: Front end

#5895 ci: share playwright cache across branches
  .github/workflows/npm-test.yml
Labels: workflow

#6087 fix(docs): fix bad url building DEV-878
  kobo/apps/project_views/schema_extensions/v2/extensions.py
  kpi/schema_extensions/v2/export_tasks/extensions.py
  kpi/utils/schema_extensions/url_builder.py
Labels: API, Back end, documentation

#6093 feat(enketo): allow user media for preview iframe DEV-847
  jsapp/js/components/bigModal/bigModal.js
Labels: Front end

#6088 style(kpi): auto-format with biome DEV-862
  biome.jsonc
  kpi/static/js/swagger/swagger-ui-init.js
Labels: Back end

#6111 fix(docs): fix asset documentation DEV-890
  kpi/docs/api/v2/assets/list.md
Labels: API, Back end, documentation

#6089 feat(schema): add script & management command to generate API schemas (JSON/YAML) into Nginx shared volume DEV-829
  kpi/management/commands/generate_openapi_schema.py
  scripts/generate_openapi_schemas.sh
Labels: API, Back end, documentation

#6114 ci(biome): fix filter syntax DEV-862
  .github/filters.yml
  kobo/apps/form_disclaimer/static/admin/js/disable_per_asset_message.js
Labels: workflow

#6103 refactor(formbuilder): remove implicit returns in some coffeescript files DEV-823
  jsapp/xlform/src/_model.coffee
  jsapp/xlform/src/_view.coffee
  jsapp/xlform/src/_xlform.init.coffee
  jsapp/xlform/src/csv.coffee
  jsapp/xlform/src/model.aliases.coffee
  jsapp/xlform/src/model.base.coffee
  jsapp/xlform/src/model.choices.coffee
  jsapp/xlform/src/model.configs.coffee
  jsapp/xlform/src/model.inputDeserializer.coffee
  jsapp/xlform/src/model.inputParser.coffee
  jsapp/xlform/src/model.row.coffee
  jsapp/xlform/src/model.rowDetail.coffee
  jsapp/xlform/src/model.rowDetail.validationLogic.coffee
  jsapp/xlform/src/model.rowDetailMixins.coffee
  jsapp/xlform/src/model.rowDetails.skipLogic.coffee
  jsapp/xlform/src/model.skipLogicParser.coffee
  jsapp/xlform/src/model.survey.coffee
  jsapp/xlform/src/model.surveyDetail.coffee
  jsapp/xlform/src/model.surveyFragment.coffee
  jsapp/xlform/src/model.utils.coffee
  jsapp/xlform/src/model.utils.markdownTable.coffee
  jsapp/xlform/src/model.validationLogicParser.coffee
  jsapp/xlform/src/view.acceptedFiles.coffee
  jsapp/xlform/src/view.acceptedFiles.templates.coffee
  jsapp/xlform/src/view.choices.coffee
  jsapp/xlform/src/view.choices.templates.coffee
  jsapp/xlform/src/view.icons.coffee
  jsapp/xlform/src/view.mandatorySetting.coffee
  jsapp/xlform/src/view.params.coffee
  jsapp/xlform/src/view.params.templates.coffee
  jsapp/xlform/src/view.pluggedIn.backboneView.coffee
  jsapp/xlform/src/view.row.templates.coffee
  jsapp/xlform/src/view.rowDetail.SkipLogic.coffee
  jsapp/xlform/src/view.rowDetail.templates.coffee
  jsapp/xlform/src/view.rowSelector.coffee
  jsapp/xlform/src/view.rowSelector.templates.coffee
  jsapp/xlform/src/view.surveyApp.templates.coffee
  jsapp/xlform/src/view.templates.coffee
  jsapp/xlform/src/view.utils.coffee
  jsapp/xlform/src/view.widgets.coffee
Labels: Front end

#6117 chore(deps): update autogenerated mockServiceWorker file
  msw-mocks/mockServiceWorker.js
Labels: dependencies, Front end

#6120 fix(docs): fix openrosa and v2 leftover schema errors DEV-891
  kobo/apps/openrosa/__init__.py
  kobo/apps/openrosa/apps/api/viewsets/xform_list_api.py
  kobo/apps/openrosa/apps/api/viewsets/xform_submission_api.py
  kobo/apps/openrosa/apps/apps.py
  kobo/apps/openrosa/apps/main/urls.py
  kobo/apps/openrosa/docs/api/v2/formlist/list.md
  kobo/apps/openrosa/schema_extensions/__init__.py
  kobo/apps/openrosa/schema_extensions/v2/__init__.py
  kobo/apps/openrosa/schema_extensions/v2/formlist/__init__.py
  kobo/apps/openrosa/schema_extensions/v2/formlist/extensions.py
  kobo/apps/openrosa/schema_extensions/v2/formlist/fields.py
  kobo/apps/openrosa/schema_extensions/v2/formlist/serializers.py
  kobo/settings/base.py
  kpi/docs/api/v2/openrosa/form_list.md
  kpi/schema_extensions/v2/invites/serializers.py
  kpi/schema_extensions/v2/openrosa/extensions.py
  kpi/schema_extensions/v2/openrosa/serializers.py
  kpi/utils/schema_extensions/response.py
  kpi/utils/schema_extensions/url_builder.py
Labels: API, Back end, documentation

#6129 feat(auditLogs): optimize search filter for audit log endpoints
  kobo/apps/audit_log/views.py
  kpi/filters.py
Labels: Back end

#6131 feat(massEmails): get name from extra details DEV-903
  kobo/apps/mass_emails/tasks.py
Labels: Back end

#6138 fix(projectSettings): unnecessary modal padding DEV-910
  jsapp/js/components/modalForms/projectSettings.module.scss
Labels: Front end

#6133 fix(attachment): avoid blocking migration
  kobo/apps/openrosa/apps/logger/migrations/0044_alter_attachment_to_remove_null_values.py
Labels: Back end

#6137 fix(docs): fix `organization invite` enum fields DEV-907
  kobo/apps/project_ownership/schema_extensions/v2/project_ownership/invites/extensions.py
  kobo/settings/base.py
  kpi/schema_extensions/v2/invites/extensions.py
  kpi/schema_extensions/v2/invites/fields.py
  kpi/schema_extensions/v2/invites/serializers.py
  kpi/schema_extensions/v2/members/extensions.py
Labels: API, Back end, documentation

#6130 fix(docs): fix member and invite response fields DEV-902
  kobo/apps/organizations/views.py
  kpi/schema_extensions/v2/invites/extensions.py
  kpi/schema_extensions/v2/invites/serializers.py
  static/openapi/schema_v2.json
  static/openapi/schema_v2.yaml
Labels: API, Back end, documentation

#6144 fix(attachments): set attachment `is_deleted` flag in Mongo after auto cleanup DEV-922
  kobo/apps/trash_bin/tasks/attachment.py
  kobo/apps/trash_bin/tests/storage_cleanup/test_attachment_cleanup.py
Labels: Back end

#6143 feat(instanceHistory): add root_uuid to instancehistory DEV-754
  kobo/apps/openrosa/apps/logger/migrations/0047_instancehistory_root_uuid.py
  kobo/apps/openrosa/apps/logger/migrations/0048_alter_instancehistory_root_uuid.py
  kobo/apps/openrosa/apps/logger/models/instance.py
  kobo/apps/openrosa/apps/logger/tests/test_form_submission.py
  kobo/apps/openrosa/libs/utils/logger_tools.py
Labels: Back end

#6145 docs(api): rewrite drf_spectacular documentation `README.md` DEV-912
  docs/README.md
Labels: API, Back end, documentation

#6162 feat(reversion): task to remove version objects DEV-946
  kobo/settings/base.py
  kpi/tasks.py
Labels: Back end

#6185 feat(background-audio-recording): modify messages about bg audio recording on form builder DEV-827
  jsapp/js/components/metadataEditor.js
  jsapp/js/editorMixins/editableForm.js
Labels: Front end

#6165 feat(instanceHistory): Celery task to clean instance history records DEV-753
  kobo/apps/openrosa/apps/logger/tasks.py
  kobo/apps/openrosa/apps/logger/tests/test_tasks.py
  kobo/settings/base.py
Labels: Back end

#6184 fix(nlp): reset polling status after auto translation finishes DEV-915
  jsapp/js/components/processing/singleProcessingStore.ts
Labels: Front end
