Repository kobotoolbox/kpi, pull requests merged in 2025-06, with the labels that each got.

#5814 chore(management): add `repostgres` command to restore data from MongoDB to PostgreSQL
  kobo/apps/openrosa/apps/logger/management/commands/repostgres.py
Labels: Back end

#5754 fix(nlp): handle old qpaths that point at deleted questions TASK-194
  kobo/apps/subsequences/tests/test_proj_advanced_features.py
  kobo/apps/subsequences/utils/deprecation.py
Labels: bug-fix, Back end

#5820 fix(nlp): handle old qpaths that point at deleted questions DEV-194
  kobo/apps/subsequences/tests/test_proj_advanced_features.py
  kobo/apps/subsequences/utils/deprecation.py
Labels: Back end

#5825 refactor(removingAttachments): better success and error handling in bulkDeleteAttachments
  jsapp/js/attachments/BulkDeleteMediaFiles.tsx
Labels: Front end

#5818 fix(projectHistoryLogs): fix 500 when exporting as anonymous user DEV-376
  kobo/apps/audit_log/models.py
  kobo/apps/audit_log/tests/test_project_history_logs.py
Labels: Back end

#5715 feat(projectHistoryLogs): change code to codename for partial perms DEV-218
  kobo/apps/audit_log/signals.py
  kobo/apps/audit_log/tests/test_project_history_logs.py
  kobo/apps/audit_log/tests/test_signals.py
Labels: Back end

#5828 fix(attachments): ignore old MongoDB attachment format when backfilling new attributes
  kobo/apps/long_running_migrations/jobs/0009_backfill_attachment_model.py
Labels: Back end

#5830 fix(massEmails): no error on empty test user list DEV-562
  kobo/apps/mass_emails/user_queries.py
Labels: Back end

#5819 feat(attachments): Update formpack export to handle deleted attachments TASK-575
  dependencies/pip/dev_requirements.txt
  dependencies/pip/requirements.in
  dependencies/pip/requirements.txt
Labels: Back end

#5829 refactor(attachments): use DRF-compliant error format for field-specific validation
  kpi/serializers/v2/attachment_delete.py
  kpi/tests/api/v2/test_api_attachments_delete_viewset.py
Labels: Back end

#5833 fix(nlp): use `root_uuid` to avoid 404 when opening the transcription/translation modal DEV-571
  kobo/apps/subsequences/api_view.py
  kobo/apps/subsequences/tests/test_submission_extras_api_post.py
Labels: Back end

#5837 fix(organization): stop duplicate project transfers when adding a member to an org from Django Admin DEV-558
  kobo/apps/organizations/admin/organization.py
  kobo/apps/organizations/tests/admin/test_organization_admin.py
Labels: Back end

#5843 feat(massEmails): download a CSV of recipients from the last 30 days DEV-587
  kobo/apps/mass_emails/models.py
Labels: Back end

#5817 feat(billing): create useTrackingPeriod hook DEV-494
  jsapp/js/account/stripe.api.ts
  jsapp/js/account/usage/usage.component.tsx
  jsapp/js/account/usage/usageProjectBreakdown.tsx
  jsapp/js/account/usage/useBillingPeriod.tsx
  jsapp/js/account/usage/useUsage.hook.ts
  jsapp/js/components/processing/transcript/stepConfig.component.tsx
  jsapp/js/components/processing/translations/stepConfig.component.tsx
  jsapp/js/components/usageLimits/limitNotifications.component.tsx
  jsapp/js/query/queryKeys.ts
Labels: Front end

#5858 fix(removingAttachments): don't disable automatic translation button DEV-588
  jsapp/js/components/processing/translations/stepConfig.component.tsx
Labels: Front end

#5857 fix(organizations): transfer assets if import updates user DEV-343
  kobo/apps/organizations/admin/organization_user.py
  kobo/apps/organizations/tests/test_organization_user_import.py
Labels: Back end

#5808 feat(billing): add balances to service usage api DEV-488
  kobo/apps/organizations/tests/test_organizations_service_usage_api.py
  kobo/apps/organizations/views.py
  kpi/serializers/v2/service_usage.py
  kpi/views/v2/service_usage.py
Labels: Back end

#5864 fix(organizations): always use username for organization slug DEV-626
  kobo/apps/kobo_auth/models.py
  kobo/apps/organizations/tests/test_organizations.py
Labels: bug, bug-fix, Back end

#5863 fix(projectOwnership): prevent failed transfers caused by race conditions DEV-629
  kobo/apps/organizations/admin/organization_user.py
  kobo/apps/organizations/tests/test_organization_user_import.py
Labels: Back end

#5855 fix(assets): fix empty xml is returned when XLSForm is invalid DEV-576
  kpi/renderers.py
  kpi/tests/api/v2/test_api_asset_snapshots.py
Labels: bug-fix, Back end

#5812 docs(api): override default negotiation to enforce first renderer
  kobo/apps/audit_log/views.py
  kobo/apps/openrosa/apps/api/viewsets/attachment_viewset.py
  kobo/apps/openrosa/apps/api/viewsets/metadata_viewset.py
  kobo/apps/openrosa/libs/renderers/renderers.py
  kobo/apps/organizations/renderers.py
  kobo/apps/organizations/views.py
  kobo/settings/base.py
  kpi/negotiation.py
  kpi/renderers.py
  kpi/views/v2/asset_export_settings.py
  kpi/views/v2/asset_usage.py
  kpi/views/v2/data.py
  kpi/views/v2/export_task.py
  kpi/views/v2/paired_data.py
  kpi/views/v2/service_usage.py
Labels: Back end
