Repository kobotoolbox/kpi, pull requests merged in 2025-04, with the labels that each got.

#5641 fix(massEmails): throttle mass email send
  kobo/apps/mass_emails/tasks.py
  kobo/apps/mass_emails/tests/test_celery_tasks.py
  kobo/settings/base.py
Labels: Back end

#5645 feat(projectHistoryLogs): add project owner to submission logs DEV-29
  kobo/apps/audit_log/models.py
  kobo/apps/audit_log/tests/test_project_history_logs.py
Labels: Back end

#5633 feat(massEmails): Query for users reaching nlp usage limits TASK-152
  kobo/apps/mass_emails/migrations/0007_add_nlp_queries.py
  kobo/apps/mass_emails/models.py
  kobo/apps/mass_emails/tests/test_usage_limit_user_queries.py
  kobo/apps/mass_emails/user_queries.py
  kobo/apps/organizations/types.py
  kobo/apps/stripe/models.py
  kobo/apps/stripe/tests/test_one_time_addons_api.py
  kobo/apps/stripe/tests/test_stripe_utils.py
  kobo/apps/stripe/utils.py
  kpi/tests/api/v2/test_api_service_usage.py
  kpi/tests/test_usage_calculator.py
  kpi/utils/usage_calculator.py
Labels: Back end

#5646 fix(formBuilder): Question Matrix settings crash DEV-39
  jsapp/xlform/src/view.rowDetail.coffee
Labels: Front end

#5648 chore(vscode): exclude compiled js from search
  kpi.code-workspace
Labels: Front end

#5649 fix(stripe): annotate methods requiring stripe functionality
  kobo/apps/mass_emails/tests/test_usage_limit_user_queries.py
  kobo/apps/mass_emails/user_queries.py
  kobo/apps/organizations/utils.py
  kobo/apps/stripe/tests/test_stripe_utils.py
  kobo/apps/stripe/utils.py
  kobo/apps/trackers/utils.py
  kpi/utils/usage_calculator.py
Labels: Back end

#5631 feat(nlp): processing view button conditional rendering TASK-1715
  jsapp/js/components/processing/analysis/constants.ts
  jsapp/js/components/submissions/audioCell.scss
  jsapp/js/components/submissions/audioCell.tsx
  jsapp/js/components/submissions/submissionDataTable.tsx
  jsapp/js/components/submissions/submissionUtils.tests.js
  jsapp/js/components/submissions/submissionUtils.tsx
  jsapp/js/components/submissions/table.tsx
  jsapp/js/dataInterface.ts
Labels: Front end

#5652 refactor(submissionUtils): migrate code to TypeScript TASK-1760
  jsapp/js/assetUtils.mocks.js
  jsapp/js/components/processing/analysis/constants.ts
  jsapp/js/components/submissions/submissionUtils.mocks.ts
  jsapp/js/components/submissions/submissionUtils.tests.ts
  jsapp/js/components/submissions/submissionUtils.tsx
  jsapp/js/dataInterface.ts
Labels: Front end

#5654 refactor(submissionUtils): type improvements TASK-1760
  jsapp/js/components/submissions/submissionUtils.mocks.ts
  jsapp/js/components/submissions/submissionUtils.tests.ts
Labels: Front end

#5640 feat(massEmails): create celery task for generating daily user lists TASK-1690
  kobo/apps/mass_emails/tasks.py
  kobo/apps/mass_emails/tests/test_celery_tasks.py
Labels: Back end

#5653 style(billing): adjust plans page layout TASK-1637
  jsapp/js/account/plans/billingButton.component.tsx
  jsapp/js/account/plans/plan.component.tsx
  jsapp/js/account/plans/plan.module.scss
  jsapp/js/account/plans/planContainer.component.tsx
Labels: Front end

#5567 refactor(storybook): migrate to v8 and update obsolete stories
  .storybook/main.js
  .storybook/preview.js
  jsapp/js/components/common/ButtonNew.tsx
  jsapp/js/components/common/avatar.stories.tsx
  jsapp/js/components/common/badge.stories.tsx
  jsapp/js/components/common/button.stories.tsx
  jsapp/js/components/common/button.tsx
  jsapp/js/components/common/checkbox.stories.tsx
  jsapp/js/components/common/icon.stories.tsx
  jsapp/js/components/common/inlineMessage.stories.tsx
  jsapp/js/components/common/koboDropdown.stories.tsx
  jsapp/js/components/common/koboDropdown.tsx
  jsapp/js/components/common/koboRange.stories.tsx
  jsapp/js/components/common/koboSelect.stories.tsx
  jsapp/js/components/common/loadingSpinner.stories.tsx
  jsapp/js/components/common/miniAudioPlayer.stories.tsx
  jsapp/js/components/common/multiCheckbox.stories.tsx
  jsapp/js/components/common/radio.scss
  jsapp/js/components/common/radio.stories.tsx
  jsapp/js/components/common/tabs.stories.tsx
  jsapp/js/components/common/textBox.stories.tsx
  jsapp/js/components/common/tooltip.stories.tsx
  jsapp/js/components/languages/languageSelector.stories.tsx
  jsapp/js/components/languages/regionSelector.stories.tsx
  jsapp/js/components/modals/koboModal.stories.tsx
  jsapp/js/components/modals/koboModal.tsx
  jsapp/js/components/modals/koboPrompt.stories.tsx
  jsapp/js/components/modals/koboPrompt.tsx
  package-lock.json
  package.json
Labels: Front end

#5558 refactor(map): TypeScriptize Project Data Map files DEV-16
  jsapp/js/actions.d.ts
  jsapp/js/components/formSubScreens.js
  jsapp/js/components/map/MapColorPicker.tsx
  jsapp/js/components/map/MapSettings.tsx
  jsapp/js/components/map/index.tsx
  jsapp/js/components/map/leaflet-omnivore.d.ts
  jsapp/js/dataInterface.ts
  package-lock.json
  package.json
Labels: Front end

#5661 refactor(storybook): reorganize stories DEV-50
  .storybook/preview.js
  jsapp/js/attachments/AttachmentActionsDropdown.stories.tsx
  jsapp/js/attachments/deletedAttachment.stories.tsx
  jsapp/js/components/common/Select.stories.tsx
  jsapp/js/components/common/SimpleTable.stories.tsx
  jsapp/js/components/common/actionIcon.stories.tsx
  jsapp/js/components/common/alert.stories.tsx
  jsapp/js/components/common/ariaText.stories.tsx
  jsapp/js/components/common/avatar.stories.tsx
  jsapp/js/components/common/badge.stories.tsx
  jsapp/js/components/common/button.stories.tsx
  jsapp/js/components/common/checkbox.stories.tsx
  jsapp/js/components/common/diffValue.stories.tsx
  jsapp/js/components/common/dropdownmenu.stories.tsx
  jsapp/js/components/common/icon.stories.tsx
  jsapp/js/components/common/inlineMessage.stories.tsx
  jsapp/js/components/common/koboDropdown.stories.tsx
  jsapp/js/components/common/koboRange.stories.tsx
  jsapp/js/components/common/koboSelect.stories.tsx
  jsapp/js/components/common/loader.stories.tsx
  jsapp/js/components/common/loadingOverlay.stories.tsx
  jsapp/js/components/common/loadingSpinner.stories.tsx
  jsapp/js/components/common/miniAudioPlayer.stories.tsx
  jsapp/js/components/common/modal.stories.tsx
  jsapp/js/components/common/multiCheckbox.stories.tsx
  jsapp/js/components/common/radio.stories.tsx
  jsapp/js/components/common/tabs.stories.tsx
  jsapp/js/components/common/textBox.stories.tsx
  jsapp/js/components/common/textInput.stories.tsx
  jsapp/js/components/common/tooltip.stories.tsx
  jsapp/js/components/exportToEmailButton/exportToEmailButton.stories.tsx
  jsapp/js/components/languages/languageSelector.stories.tsx
  jsapp/js/components/languages/regionSelector.stories.tsx
  jsapp/js/components/modals/koboModal.stories.tsx
  jsapp/js/components/modals/koboPrompt.stories.tsx
  jsapp/js/universalTable/universalTable.stories.tsx
Labels: Front end

#5659 feat(massEmails): Celery task for sending emails TASK-1692
  kobo/apps/mass_emails/tasks.py
  kobo/apps/mass_emails/tests/test_celery_tasks.py
Labels: Back end

#5650 ci: pytest with stripe disabled
  .github/workflows/pytest.yml
  hub/tests/test_globalsettings.py
  kobo/apps/accounts/mfa/tests/test_login.py
  kobo/apps/external_integrations/tests/test_cors.py
  kobo/apps/mass_emails/tests/test_celery_tasks.py
  kobo/apps/mass_emails/tests/test_usage_limit_user_queries.py
  kobo/apps/stripe/utils.py
  kobo/apps/trackers/tests/test_utils.py
  kobo/apps/trackers/utils.py
  kobo/settings/testing_no_stripe.py
  kpi/fixtures/test_data.json
  kpi/tests/api/test_api_environment.py
  kpi/tests/test_usage_calculator.py
  kpi/tests/utils/mixins.py
Labels: Back end

#5658 fix(submissions): ensure atomicity of submissions TASK-1764
  kobo/apps/openrosa/libs/utils/logger_tools.py
Labels: bug-fix, Back end

#5663 refactor(longRunningMigrations): update MongoDB documents alongside PostgreSQL in attachment backfill TASK-1773
  kobo/apps/long_running_migrations/jobs/0007_backfill_attachment_model.py
Labels: Back end

#5651 fix(migrations): refactor blocking migrations to run faster during deployment TASK-1758
  kobo/apps/audit_log/migrations/0012_alter_auditlog_action.py
  kobo/apps/audit_log/migrations/0012_increase_action_length.py
  kobo/apps/audit_log/migrations/0013_add_new_choices_to_action.py
  kobo/apps/audit_log/migrations/0013_alter_auditlog_action.py
  kobo/apps/audit_log/migrations/0014_add_submission_action.py
  kobo/apps/audit_log/models.py
  kobo/apps/openrosa/apps/logger/migrations/0041_add_root_uuid_field_to_instance.py
  kobo/apps/openrosa/apps/logger/models/instance.py
Labels: Back end

#5664 fix: prevent 500 error when submission `root_uuid` is null in data API
  kobo/apps/openrosa/apps/viewer/models/parsed_instance.py
Labels: Back end

#5667 fix(organization): ensure members have permissions to view project forms and submit data TASK-1768
  kobo/apps/openrosa/apps/api/tests/viewsets/test_xform_list_api.py
  kobo/apps/openrosa/libs/filters.py
  kpi/serializers/v2/asset.py
  kpi/tests/api/v1/test_api_assets.py
  kpi/tests/api/v2/test_api_assets.py
Labels: bug-fix, Back end

#5660 refactor(trashBin): group tasks by object type for better organization
  kobo/apps/trash_bin/tasks.py
  kobo/apps/trash_bin/tasks/__init__.py
  kobo/apps/trash_bin/tasks/account.py
  kobo/apps/trash_bin/tasks/project.py
  kobo/apps/trash_bin/tests/test_utils.py
  kobo/apps/trash_bin/type_aliases.py
  kobo/apps/trash_bin/utils.py
  kobo/apps/trash_bin/utils/__init__.py
  kobo/apps/trash_bin/utils/account.py
  kobo/apps/trash_bin/utils/project.py
  kobo/apps/trash_bin/utils/signals.py
  kobo/apps/trash_bin/utils/trash.py
  kpi/deployment_backends/kc_access/utils.py
Labels: Back end

#5642 refactor(attachments): expose uid instead of pk in the data API endpoint TASK-1522
  kpi/deployment_backends/base_backend.py
  kpi/deployment_backends/openrosa_backend.py
  kpi/tests/api/v2/test_api_submissions.py
  kpi/views/v2/attachment.py
  kpi/views/v2/data.py
Labels: Back end

#5626 feature(attachments): add bulk deleting attachments using the row selector in table with mock api TASK-1516 TASK-1710
  jsapp/js/api.endpoints.ts
  jsapp/js/attachments/AttachmentActionsDropdown.tsx
  jsapp/js/attachments/BulkDeleteMediaFiles.tsx
  jsapp/js/attachments/attachmentsQuery.ts
  jsapp/js/components/submissions/submissionUtils.tsx
  jsapp/js/components/submissions/tableBulkOptions.tsx
  jsapp/js/theme/kobo/Button.module.css
Labels: Front end

#5671 refactor(attachments): match FE to the updated response for submission attachments TASK-1778
  jsapp/js/attachments/AttachmentActionsDropdown.mocks.ts
  jsapp/js/attachments/AttachmentActionsDropdown.stories.tsx
  jsapp/js/attachments/AttachmentActionsDropdown.tsx
  jsapp/js/components/formGallery/formGallery.component.tsx
  jsapp/js/components/processing/sidebar/sidebarSubmissionMedia.tsx
  jsapp/js/components/submissions/mediaCell.tsx
  jsapp/js/components/submissions/submissionDataTable.tsx
  jsapp/js/components/submissions/submissionModal.tsx
  jsapp/js/components/submissions/submissionUtils.mocks.ts
  jsapp/js/components/submissions/submissionUtils.tsx
  jsapp/js/dataInterface.ts
Labels: Front end

#5672 fix(attachments): display attachment dropdown additionally to media in single submission modal
  jsapp/js/components/submissions/submissionDataTable.tsx
Labels: Front end

#5647 feat(projectHistoryLogs): add owner to deployment logs DEV-45
  kobo/apps/audit_log/models.py
  kobo/apps/audit_log/tests/test_project_history_logs.py
  kpi/views/v2/asset.py
Labels: Back end

#5675 refactor(backendDeployment): remove fallback logic that retrieved the KPI project from OpenRosa counterpart
  .github/workflows/pytest.yml
  kobo/apps/openrosa/apps/logger/models/xform.py
  kobo/apps/openrosa/apps/logger/tests/models/test_xform.py
  kpi/models/asset.py
Labels: Back end

#5674 fix(projectHistoryLogs): remove query count checks from tests
  kobo/apps/audit_log/tests/test_project_history_logs.py
Labels: Back end

#5681 fix(languageSelector): force refresh languages list after clearing the searchbox DEV-183
  jsapp/js/components/languages/languageSelector.tsx
Labels: Front end

#5682 chore(envStore): remove unused TS interface props
  jsapp/js/envStore.ts
Labels: Front end

#5670 test(storybook): languageSelector search DEV-99
  .storybook/main.js
  .storybook/preview.js
  biome.jsonc
  jsapp/js/components/languages/languageSelector.stories.tsx
  jsapp/js/components/languages/languageSelector.tsx
  jsapp/js/components/languages/languagesListStore.mock.ts
  jsapp/js/envStore.mock.ts
  msw-mocks/mockServiceWorker.js
  package-lock.json
  package.json
Labels: Front end

#5688 fix(migrations): fix null search_fields
  kpi/migrations/0065_alter_asset_search_field.py
  kpi/models/asset.py
Labels: Back end

#5691 fix(massEmails): read MASS_EMAIL_CONDENSE_SEND from env
  kobo/settings/base.py
Labels: Back end

#5679 refactor(select): replace and remove KoboSelect3 DEV-102
  jsapp/js/account/accountFieldsEditor.component.tsx
  jsapp/js/account/addOns/addOnList.module.scss
  jsapp/js/account/addOns/oneTimeAddOnRow.component.tsx
  jsapp/js/account/organization/InviteModal.tsx
  jsapp/js/account/organization/MemberRoleSelector.tsx
  jsapp/js/components/common/Select.stories.tsx
  jsapp/js/components/common/Select.tsx
  jsapp/js/components/special/koboAccessibleSelect.module.scss
  jsapp/js/components/special/koboAccessibleSelect.spec.tsx
  jsapp/js/components/special/koboAccessibleSelect.tsx
Labels: Front end

#5673 feature(attachments): modal displays background audio in player and add remove attachment dropdown TASK-1663
  jsapp/js/assetUtils.ts
  jsapp/js/components/submissions/SubmissionBackgroundAudio.tsx
  jsapp/js/components/submissions/submissionModal.tsx
  jsapp/js/components/submissions/submissionUtils.tsx
Labels: Front end

#5692 refactor(submissions): optimize `clean_duplicated_submissions` command with batching and project scoping
  kobo/apps/long_running_migrations/jobs/0005_backfill_logger_instance_root_uuid.py
  kobo/apps/openrosa/apps/logger/management/commands/clean_duplicated_submissions.py
Labels: Back end

#5695 feature(attachments): make bulk delete attachments account for partial permissions TASK-559
  jsapp/js/attachments/BulkDeleteMediaFiles.tsx
  jsapp/js/components/submissions/submissionUtils.tsx
  jsapp/js/components/submissions/tableBulkOptions.tsx
Labels: Front end

#5676 refactor(storybook): migrate button tests DEV-97
  .github/workflows/npm-test.yml
  jsapp/jest/jest.config.ts
  jsapp/jest/setupJestTest.ts
  jsapp/js/components/common/ButtonNew.stories.tsx
  jsapp/js/components/common/actionIcon.stories.tsx
  jsapp/js/components/common/button.spec.tsx
  jsapp/js/storybookUtils.ts
  package.json
Labels: Front end

#5698 test(projectHistoryLogs): check for project owner on submission logs
  kobo/apps/audit_log/tests/test_project_history_logs.py
Labels: Back end

#5702 refactor(frontend): rename FormActivity files
  jsapp/js/components/activity/FormActivity.module.scss
  jsapp/js/components/activity/FormActivity.tsx
  jsapp/js/components/formSubScreens.js
Labels: Front end

#5701 perf(tasks): reduce the number of stuck tasks restarted to ease DB load
  kobo/apps/project_ownership/tasks.py
  kobo/apps/trash_bin/tasks.py
  kobo/settings/base.py
Labels: Back end

#5700 fix(PyMongo): enforce maxTimeMS using low-level command to ensure query timeout
  kobo/apps/openrosa/apps/logger/management/commands/clean_duplicated_submissions.py
  kobo/apps/openrosa/apps/viewer/models/parsed_instance.py
  kobo/apps/openrosa/apps/viewer/signals.py
  kobo/apps/openrosa/libs/utils/logger_tools.py
  kobo/apps/trash_bin/utils.py
  kpi/deployment_backends/openrosa_backend.py
  kpi/utils/mongo_helper.py
Labels: Back end

#5699 feat(projectHistoryLogs): add owner to permission logs DEV-182
  kobo/apps/audit_log/models.py
  kobo/apps/audit_log/tests/test_models.py
  kobo/apps/audit_log/tests/test_project_history_logs.py
  kpi/views/v2/asset_permission_assignment.py
Labels: Back end

#5708 fix(mongoHelper): use correct MongoDB collection for query operations
  kpi/utils/mongo_helper.py
Labels: bug

#5706 feat(projectHistoryLogs): add project owner to related viewsets
  kobo/apps/audit_log/models.py
  kobo/apps/audit_log/tests/test_models.py
  kobo/apps/audit_log/tests/test_project_history_logs.py
  kobo/apps/hook/views/v2/hook.py
  kpi/views/v2/asset_file.py
  kpi/views/v2/export_task.py
  kpi/views/v2/paired_data.py
Labels: Back end

#5703 fix(billing): filter for plans when querying active subscription details DEV-206
  kobo/apps/organizations/models.py
  kobo/apps/organizations/tests/test_organizations_api.py
  kobo/apps/stripe/tests/test_organization_usage.py
Labels: Back end

#5713 refactor(frontend): query client mock decorator
  jsapp/js/attachments/AttachmentActionsDropdown.stories.tsx
  jsapp/js/query/queryClient.mock.tsx
Labels: Front end

#5714 refactor(frontend): update endpoints list file
  jsapp/js/api.endpoints.ts
  jsapp/js/components/languages/languagesListStore.mock.ts
  jsapp/js/components/languages/languagesListStore.ts
  jsapp/js/components/languages/languagesStore.ts
  jsapp/js/envStore.mock.ts
  jsapp/js/envStore.ts
  jsapp/js/query/queryClient.mock.tsx
Labels: Front end

#5696 test: add query-counting tests to critical endpoints
  kobo/apps/openrosa/apps/api/tests/viewsets/test_data_viewset.py
  kobo/apps/openrosa/apps/api/tests/viewsets/test_xform_submission_api.py
  kpi/models/asset.py
  kpi/serializers/v2/asset.py
  kpi/tests/api/v1/test_api_assets.py
  kpi/tests/api/v2/test_api_assets.py
  kpi/tests/api/v2/test_api_submissions.py
Labels: Back end

#5712 fix(mongo): Update MongoDB utilities to handle documents using the new `_user_formid` value
  kobo/apps/openrosa/apps/logger/models/instance.py
  kobo/apps/openrosa/apps/viewer/models/parsed_instance.py
  kobo/apps/openrosa/apps/viewer/tests/test_remongo.py
  kobo/apps/openrosa/libs/serializers/data_serializer.py
  kobo/apps/openrosa/libs/utils/export_tools.py
  kobo/apps/openrosa/libs/utils/logger_tools.py
  kobo/apps/openrosa/libs/utils/viewer_tools.py
  kobo/apps/reports/report_data.py
  kpi/deployment_backends/openrosa_backend.py
Labels: Back end

#5711 docs(api): prepare API documentation support for KPI v2 endpoints
  dependencies/pip/dev_requirements.txt
  dependencies/pip/requirements.in
  dependencies/pip/requirements.txt
  kobo/apps/audit_log/views.py
  kobo/apps/hook/views/v2/hook.py
  kobo/apps/hook/views/v2/hook_log.py
  kobo/apps/languages/views/language.py
  kobo/apps/languages/views/transcription_service.py
  kobo/apps/languages/views/translation_service.py
  kobo/apps/openrosa/apps/api/urls.py
  kobo/apps/openrosa/libs/renderers/renderers.py
  kobo/apps/organizations/views.py
  kobo/apps/project_ownership/views/invite.py
  kobo/apps/project_ownership/views/transfer.py
  kobo/apps/project_views/views.py
  kobo/apps/reports/serializers.py
  kobo/apps/trash_bin/tasks/__init__.py
  kobo/settings/base.py
  kobo/urls.py
  kpi/docs/api/v2/__init__.py
  kpi/filters.py
  kpi/renderers.py
  kpi/serializers/v2/reports.py
  kpi/utils/spectacular_processing.py
  kpi/utils/viewset_mixins.py
  kpi/views/v2/asset.py
  kpi/views/v2/asset_counts.py
  kpi/views/v2/asset_export_settings.py
  kpi/views/v2/asset_file.py
  kpi/views/v2/asset_permission_assignment.py
  kpi/views/v2/asset_snapshot.py
  kpi/views/v2/asset_usage.py
  kpi/views/v2/asset_version.py
  kpi/views/v2/attachment.py
  kpi/views/v2/data.py
  kpi/views/v2/export_task.py
  kpi/views/v2/import_task.py
  kpi/views/v2/paired_data.py
  kpi/views/v2/permission.py
  kpi/views/v2/service_usage.py
  kpi/views/v2/user.py
  kpi/views/v2/user_asset_subscription.py
Labels: API, Back end, documentation

#5719 refactor(frontend): move endpoints mocks to new directory
  jsapp/js/components/languages/languageSelector.stories.tsx
  jsapp/js/endpoints/environment.mock.ts
  jsapp/js/endpoints/languages.mock.ts
Labels: Front end

#5717 fix(projectOwnershipTransfer): submissions are not transferred to new owner
  kpi/utils/mongo_helper.py
Labels: Back end

#5666 feat(attachments): new endpoint to bulk delete specific attachments on an asset TASK-588
  kobo/settings/base.py
  kpi/deployment_backends/base_backend.py
  kpi/deployment_backends/openrosa_backend.py
  kpi/exceptions.py
  kpi/permissions.py
  kpi/serializers/v2/attachment_bulk_delete.py
  kpi/tests/api/v2/test_api_attachments_bulk_delete_viewset.py
  kpi/urls/router_api_v2.py
  kpi/views/v2/attachment_bulk_delete.py
Labels: Back end

#5705 feat(attachments): new endpoint to bulk delete all attachments from a submission TASK-1524
  kpi/tests/api/v2/test_api_attachments.py
  kpi/views/v2/attachment.py
Labels: Back end

#5724 fix(projectOwnershipTransfer): make transfer more resilient by catching exceptions
  kobo/apps/long_running_migrations/jobs/0003_transfer_members_data_ownership_to_org.py
  kobo/apps/project_ownership/models/transfer.py
  kobo/apps/project_ownership/utils.py
  kpi/fields/file.py
Labels: Back end

#5718 fix(mongoSync): do not double-save new parsed instances
  kobo/apps/openrosa/libs/utils/logger_tools.py
Labels: Back end
